-- APP_SCL_ALTAMIRA.CP_NOTIFICATIONS definition

CREATE TABLE "APP_SCL_ALTAMIRA"."CP_NOTIFICATIONS" 
   (	"IDNOTIF" NUMBER(*,0) DEFAULT 0, 
	"RECIPIENTS" VARCHAR2(2000) NOT NULL ENABLE, 
	"NOTIFYSUCCESS" NUMBER(*,0) DEFAULT 0 NOT NULL ENABLE, 
	"NOTIFYFAILURE" NUMBER(*,0) DEFAULT 0 NOT NULL ENABLE, 
	"NAME" VARCHAR2(200), 
	 CONSTRAINT "CP_NOTIFICATIONS_PK" PRIMARY KEY ("IDNOTIF")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SCL_DATA"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SCL_DATA" ;

CREATE UNIQUE INDEX "APP_SCL_ALTAMIRA"."CP_NOTIFICATIONS_PK" ON "APP_SCL_ALTAMIRA"."CP_NOTIFICATIONS" ("IDNOTIF") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SCL_DATA" ;

COMMENT ON COLUMN APP_SCL_ALTAMIRA.CP_NOTIFICATIONS.RECIPIENTS IS 'Mails comma separated.';