INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(457, 5, 'lol', 'dwes', 'srggsd', 'er', 'tgrtg', 'ert5wer', 'ertwe', 1, 4, 2, 'Activo', 0, 6, 0, 69, 'node', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(456, 1, 'nombre', 'desc', 'path', NULL, NULL, NULL, NULL, 0, 3, 5, 'Activo', 0, 1, 0, 63, 'node', 3);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(455, 4, 'name', 'desc', 'path', NULL, NULL, NULL, NULL, 1, 3, 1, 'Activo', 0, 2, 0, 69, 'node', 2);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(454, 0, 'RPT_BUZONEROS_GAC.sh', 'Reporte Buzoneros GAC - Solicita: Fidelizacion 1/04/2024', '${PATH_DIRECTOR_SH}', '${PATH_DIRECTOR_ENTRADA}', 'to_char(''RPT_BUZONEROS_GAC_'' || to_char(sysdate - 2, ''YYYYMM'') || ''.txt'')', NULL, NULL, 0, 1, 0, 'Activo', 0, 0, 0, 56, 'lnxni0230', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(453, 0, 'RPT_MTH_COUNT_TRANSACTIONS.sh', 'Conteo mensual transacciones fallidas,no validas, exitosas  MTH - AppSupport (GDRC-45752)', '${PATH_DIRECTOR_SH}', '${PATH_DIRECTOR_ENTRADA}', 'RPT_MTH_ConteoTransacciones_', 'To_Char(Add_Months(Sysdate, -1),''YYYYMM'')', NULL, 0, 1, 0, 'Activo', 0, 0, 0, 59, 'LNXNI0230', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(452, 0, 'RPT_MTH_FAILED_TRANSACTIONS.sh', 'Reporte mensual transacciones fallidas MTH - AppSupport', '${PATH_DIRECTOR_SH}', '${PATH_DIRECTOR_ENTRADA}', 'RPT_MTH_TransaccionesFallidas_', 'to_char(add_months(sysdate, -1),''YYYYMM'')', NULL, 0, 1, 0, 'Activo', 0, 0, 0, 42, 'LNXNI0230', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(451, 0, 'SOX_11_2_start.sh', 'Proceso de conciliacion ROAMING VS TRAFICO', '/home/appextractor/Director/Sh/EXTRACTORES_SOX/SOX_11_2', NULL, NULL, NULL, NULL, 0, 1, 0, 'Inactivo', 0, 0, 0, 36, 'sunni005', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(450, 0, 'ELT_SiteInfoMerge.sh', 'ETL from 01ni0148 to Venus, MergeSiteInfo GDRC-44812', '/sharenfs02/procs/etls/Digital_SiteInfoMerge/scripts', NULL, NULL, NULL, NULL, 0, 2, 3600, 'Internal', 0, 0, 0, 28, 'lnxni0230', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(449, 0, 'ETL_Digital_PaymGtwy_S3.sh', 'ETL Digital_PaymGtwy from S3 to SMB(01ni040a) GDRC-44899', '/sharenfs02/procs/etls/Digital_PaymGtwy/scripts', NULL, NULL, NULL, NULL, 0, 2, 3600, 'Activo', 0, 0, 0, 34, 'lnxni0230', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(448, 0, 'rpt_fact_nociclo_rao_month.sh', 'Proceso RAO de facturacion no ciclos MES', '${PATH_DIRECTOR_SH}', NULL, NULL, NULL, NULL, 0, 1, 0, 'Activo', 0, 0, 0, 36, 'lnxni0230', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(447, 0, 'rpt_fact_ciclo_rao_month.sh', 'Proceso RAO de los ciclos de facturacion MES', '${PATH_DIRECTOR_SH}', NULL, NULL, NULL, NULL, 0, 1, 0, 'Activo', 1, 0, 0, 36, 'lnxni0230', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(446, 0, 'rpt_fact_ciclo_rao.sh', 'Proceso RAO DE los ciclos de facturacion', '${PATH_DIRECTOR_SH}', NULL, NULL, NULL, NULL, 0, 1, 0, 'Activo', 0, 0, 0, 36, 'lnxni0230', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(445, 0, 'base_bancarizada_start.sh', 'Proceso Base Bancarizada', '/export/home/appextractor/Director/Sh/PROC_BASE_BANCARIZADA', NULL, NULL, NULL, NULL, 0, 5, 60, 'Activo', 0, 0, 0, 36, 'sunni005', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(444, 0, 'Test.sh', 'Conexión', '${PATH_DIRECTOR_SH}', 'to_char(sysdate-1,''yyyymmdd'')', 'to_char(sysdate-1,''mmyyyy'')', NULL, NULL, 0, 5, 60, 'Internal', 0, 0, 0, 40, 'lnxni0230', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(443, 0, 'SOX_2_2_CONCILIADOR.sh', 'Proceso que genera los csv conciliados.', '/home/appextractor/Director/Sh/EXTRACTORES_SOX/SOX_2_2', NULL, NULL, NULL, NULL, 1, 5, 60, 'Activo', 0, 0, 0, 36, 'sunni005', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(442, 0, 'SOX_2_2_CARGA_SCL_CBS.sh', 'Proceso que extrae abonados de SCL y CBS y sus planes', '/home/appextractor/Director/Sh/EXTRACTORES_SOX/SOX_2_2', NULL, NULL, NULL, NULL, 1, 5, 60, 'Activo', 0, 0, 0, 32, 'sunni005', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(441, 0, 'SOX_2_2_CARGA_HSS.sh', 'Proceso que extrae archivo DUMP de RAO y lo carga en VENUS', '/home/appextractor/Director/Sh/EXTRACTORES_SOX/SOX_2_2', NULL, NULL, NULL, NULL, 0, 5, 60, 'Activo', 0, 0, 0, 17, 'sunni005', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(439, 6, 'GSM_DET_SIMCARD_TO_SPOOL.sql', 'Extracción tabla GSM_DET_SIMCARD_TO', '/home/appextractor/Director/Sql', NULL, NULL, NULL, NULL, 0, 600, 60, 'Inactivo', 0, 7, 0, 26, 'sunni005', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(438, 17, 'EXPORT_ACTIVACIONES.sql', 'Exportacion Reporte Activaciones', '${PATH_DIRECTOR_SQL}', 'to_char(sysdate-3,''yyyymm'')', '${PATH_DIRECTOR_ENTRADA}/ACTIVACIONES_', NULL, NULL, 0, 3, 3600, 'Activo', 1, 7, 0, 31, 'lnxni0230', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(437, 0, 'ALARMA_SOX.sh', 'ALARMA CONTROL SOX 12.1 Y 15.1', '/home/appextractor/Director/Sh/EXTRACTORES_SOX/ALARMA_SOX', NULL, NULL, NULL, NULL, 1, 5, 60, 'Activo', 0, 0, 0, 32, 'sunni005', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(436, 0, 'EXECUTE_SOX_15_1.sh', 'CONTROL SOX 15.1', '/home/appextractor/Director/Sh/EXTRACTORES_SOX/SOX_15_1', NULL, NULL, NULL, NULL, 0, 5, 60, 'Inactivo', 0, 0, 0, 32, 'sunni005', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(435, 0, 'EXECUTE_SOX_11_1.sh', 'Reporte SOX 11.1 GDRC-39917', '/export/home/appextractor/Director/Sh/EXTRACTORES_SOX/SOX_11_1', NULL, NULL, NULL, NULL, 0, 10, 60, 'Activo', 0, 0, 0, 31, 'sunni005', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(434, 0, 'EXECUTE_SOX_12_1.SH', 'CONTROL SOX 12.1', '/home/appextractor/Director/Sh/EXTRACTORES_SOX/SOX_12_1', NULL, NULL, NULL, NULL, 0, 5, 60, 'Activo', 0, 0, 0, 32, 'sunni005', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(433, 6, 'activaciones_completacioncam.sql', 'Reporte Activaciones Completacion de Campos. GDRC-40353', '${PATH_DIRECTOR_SQL}', 'to_char(sysdate-3,''yyyymm'')', '${PATH_DIRECTOR_ENTRADA}/ACTIVACIONESCAMPOS_', NULL, NULL, 1, 1, 0, 'Activo', 1, 7, 0, 26, 'lnxni0230', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(432, 3, 'TRAFROAM_ENCUESTASNPS.sql', 'Extractor Full TRAFROAM_ENCUESTASNPS. GDRC-37999 ', '${PATH_DIRECTOR_SQL}', NULL, NULL, NULL, NULL, 1, 1, 300, 'Activo', 0, 0, 0, 33, 'lnxni0230', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(431, 3, 'DWD_CATEGORIA_CLIENTE.sql', 'Extractor Full DWD_CATEGORIA_CLIENTE solicita JosueV. GDRC-38004', '${PATH_DIRECTOR_SQL}', NULL, NULL, NULL, NULL, 1, 1, 300, 'Activo', 0, 0, 0, 28, 'lnxni0230', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(430, 3, 'script_reciclados.sh', 'Proceso para armas bases lineas a reciclar en CBS', '/oradata1/aplicaciones/VENUS/PRO_RECICLADOS_CBS', NULL, NULL, NULL, NULL, 1, 12, 60, 'Inactivo', 0, 0, 0, 24, 'sunni005', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(429, 3, 'PRC_SEGMENTO_SAP_DWH_COPY.sql', 'Proceso migrado ControlM TCN_SEGMENTACION/segmentacion.sh ahora para uso DWH', '${PATH_DIRECTOR_SQL}', NULL, NULL, NULL, NULL, 1, 1, 0, 'Activo', 0, 0, 0, 26, 'lnxni0230', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(428, 6, 'PRC_SEGMENTO_SAP_DWH_TRUNCATE.sql', 'Proceso migrado ControlM TCN_SEGMENTACION/segmentacion.sh ahora para uso DWH', '${PATH_DIRECTOR_SQL}', NULL, NULL, NULL, NULL, 1, 1, 0, 'Activo', 0, 0, 0, 26, 'lnxni0230', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(427, 3, 'PRC_SEGMENTO_SAP_DWH.sql', 'Proceso migrado ControlM TCN_SEGMENTACION/segmentacion.sh ahora para uso DWH', '${PATH_DIRECTOR_SQL}', NULL, NULL, NULL, NULL, 1, 2, 5400, 'Activo', 0, 0, 0, 26, 'lnxni0230', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(426, 3, 'PRC_RISK_CHURN.sql', 'Procedimiento Utilizado para riesgo de churn- APP_DGTL_MAN_CHURN', '${PATH_DIRECTOR_SQL}', NULL, NULL, NULL, NULL, 0, 1, 0, 'Activo', 0, 0, 0, 14, 'lnxni0230', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(425, 0, 'PRUEBA_VEN_PROD.sh', 'Shell de Prueba en Venus Produccion', '/home/appextractor/Director/Sh', NULL, NULL, NULL, NULL, 0, 10, 60, 'Activo', 0, 0, 0, 11, 'sunni005', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(424, 5, 'RPT_TRASPASOS_MENSUAL.sql', 'Reporte de Traspasos Mensual SCL', '/home/appextractor/Director/Sql', '/home/appextractor/Director/Entrada/REPORTE_DE_TRASPASOS_MENSUAL_', 'TO_CHAR(sysdate,''yyyymmdd'')', NULL, NULL, 1, 10, 60, 'Activo', 1, 7, 0, 11, 'sunni005', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(423, 0, 'REP_TCN_TIPO_CAMBIO_PREP_AA.sh', 'Crea replica de TCN_TIPO_CAMBIO_PREP en RLPPGAN y RLPPCSN', '/home/appextractor/Director/Sh', NULL, NULL, NULL, NULL, 1, 1, 60, 'Inactivo', 0, 0, 0, 11, 'sunni005', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(422, 0, 'sftp_brightstar.sh', 'Copia reportes de log a server sftp brightstar', '/home/appextractor/Director/Sh', '/users/TigoNicaragua/Inventario', 'TO_CHAR(sysdate-1,''yyyymmdd'')', '/users/TigoNicaragua/Movimientos', 'TO_CHAR(sysdate-1,''yyyymm'')', 1, 20, 10, 'Activo', 0, 0, 0, 11, 'sunni005', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(420, 18, 'TCN_RPT_PERMISO_ROL_MS.sql', 'Reporte de Permisos por Rol Modulo de seguridad', '${PATH_DIRECTOR_SQL}', '${PATH_DIRECTOR_ENTRADA}/REPORTE_PERMISOS_ROL_', 'TO_CHAR(sysdate,''YYYYMM'')', NULL, NULL, 0, 1, 0, 'Activo', 1, 7, 1, 11, 'lnxni0230', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(419, 5, 'RPT_TRASPASOS.sql', 'Reporte de Traspasos SCL', '/home/appextractor/Director/Sql', '/home/appextractor/Director/Entrada/REPORTE_DE_TRASPASOS_DIARIOS_', 'TO_CHAR(sysdate,''yyyymmdd'')', NULL, NULL, 1, 10, 60, 'Activo', 1, 7, 0, 11, 'sunni005', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(418, 3, 'RPT_SALIDAS_SIMCARD.sh', 'Reporte Salida Definitiva de Simcard', '${PATH_DIRECTOR_SH}', '${PATH_DIRECTOR_ENTRADA}/RPT_SALIDAS_SIMCARD_', 'to_char(sysdate-1,''yyyymm'')', NULL, NULL, 1, 1, 0, 'Activo', 1, 7, 1, 11, 'lnxni0230', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(417, 3, 'PRC_SALIDAS_SIMCARD.sql', 'Proceso Salida Definitiva de Simcard', '${PATH_DIRECTOR_SQL}', 'to_char(sysdate-1,''yyyymm'')', NULL, NULL, NULL, 1, 1, 0, 'Activo', 0, 0, 0, 11, 'lnxni0230', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(416, 6, 'AL_VENTAS', 'Extractor SCL', 'Extractor Full', NULL, NULL, NULL, NULL, 1, 1, 300, 'Activo', 0, 0, 0, 26, 'lnxni0230', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(415, 5, 'RPT_SUSPENSIONES_DIA.sql', 'Reporte de Suspensiones diarias por cobro', '/home/appextractor/Director/Sql', '/home/appextractor/Director/Entrada/20_REPORTE_DE_SUSPENSIONES_DIARIAS_', 'TO_CHAR(sysdate,''yyyymmdd'')', NULL, NULL, 0, 10, 60, 'Inactivo', 1, 7, 0, 15, 'sunni005', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(412, 3, 'dwd_celda.sql', 'Proceso de Celdas DWH por DBLINK', '${PATH_DIRECTOR_SQL}', NULL, NULL, NULL, NULL, 1, 1, 0, 'Activo', 0, 0, 0, 11, 'lnxni0230', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(411, 0, 'Abonado_Nicaragua_prueba.sh', 'spool abonado', '/home/appextractor/Director/Sh', NULL, NULL, NULL, NULL, 0, 5, 60, 'Inactivo', 0, 0, 0, 11, 'sunni005', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(410, 17, 'APP_VALIDADWH_NIC.DWD_PQ_FACT_PARA_VENUS', 'Catalogo Parque para FACT NPW', 'Extractor Full', NULL, NULL, NULL, NULL, 1, 1, 0, 'Activo', 0, 0, 0, 11, 'lnxni0230', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(409, 3, 'DWD_PQ_FACT_PARA_VENUS.sql', 'Interfaz', '${PATH_DIRECTOR_SQL}', 'TO_CHAR(sysdate-2,''yyyymmdd'')', NULL, NULL, NULL, 1, 1, 0, 'Activo', 0, 0, 0, 11, 'lnxni0230', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(408, 0, 'ConexionDWHCAM.sh', 'Conexión', '${PATH_DIRECTOR_SH}', 'TO_CHAR(sysdate-2,''yyyymmdd'')', NULL, NULL, NULL, 0, 1, 0, 'Activo', 0, 0, 0, 11, 'lnxni0230', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(407, 17, 'BDDWH.DWD_DIA', 'Dimension de tiempo del SIEM por dia.', 'Extractor Full', NULL, NULL, NULL, NULL, 1, 1, 0, 'Activo', 0, 0, 0, 11, 'lnxni0230', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(406, 17, 'APP_VALIDADWH_NIC.DWD_EQUIPOS_GSMA', 'Catalogo GSMA de equipos por TAC', 'Extractor Full', NULL, NULL, NULL, NULL, 1, 1, 0, 'Activo', 0, 0, 0, 11, 'lnxni0230', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(405, 15, 'PAY_SALDO_INICIAL_RECARGA.sql', 'Proceso obtiene el saldo inicial de recarga por punto de venta en Payment', '${PATH_DIRECTOR_SQL}', NULL, NULL, NULL, NULL, 1, 1, 0, 'Activo', 0, 0, 0, 11, 'lnxni0230', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(404, 15, 'PAY_SALDO_RETIRADO_RECARGA.sql', 'Proceso obtiene el saldo retirado de recarga por punto de venta en Payment', '${PATH_DIRECTOR_SQL}', NULL, NULL, NULL, NULL, 1, 1, 0, 'Activo', 0, 0, 0, 11, 'lnxni0230', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(403, 15, 'PAY_SALDO_ASIGNADO.sql', 'Proceso obtiene el saldo asignado al punto de venta en Payment', '${PATH_DIRECTOR_SQL}', NULL, NULL, NULL, NULL, 1, 1, 0, 'Activo', 0, 0, 0, 11, 'lnxni0230', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(402, 15, 'PAY_SALDO_TRASPASADO.sql', 'Proceso obtiene el saldo traspasado por punto de venta en Payment', '${PATH_DIRECTOR_SQL}', NULL, NULL, NULL, NULL, 1, 1, 0, 'Activo', 0, 0, 0, 11, 'lnxni0230', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(401, 15, 'PAY_ULTIMO_TRASPASO.sql', 'Proceso encargado de crear el ultimo traspaso de Payment por punto de venta', '${PATH_DIRECTOR_SQL}', NULL, NULL, NULL, NULL, 1, 1, 0, 'Activo', 0, 0, 0, 28, 'lnxni0230', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(400, 15, 'PAY_ULTIMA_RECARGA.sql', 'Proceso encargado de crear la ultima recarga de Payment por punto de venta', '${PATH_DIRECTOR_SQL}', NULL, NULL, NULL, NULL, 1, 1, 0, 'Activo', 0, 0, 0, 28, 'lnxni0230', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(399, 6, 'RPT_GARANTIAS_EN_CUENTA_CORRIENTE.sql', 'Reporte de Cobranza GARANTIAS_EN_CUENTA_CORRIENTE', '${PATH_DIRECTOR_SQL}', '${PATH_DIRECTOR_ENTRADA}/17_GARANTIAS_EN_CUENTA_CORRIENTE_', 'TO_CHAR(sysdate,''yyyymmdd'')', NULL, NULL, 0, 1, 0, 'Activo', 1, 7, 1, 38, 'lnxni0230', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(398, 6, 'RPT_CARTA_DE_PAGOS.sql', 'Reporte de Cobranza CARTA_DE_PAGOS', '${PATH_DIRECTOR_SQL}', '${PATH_DIRECTOR_ENTRADA}/16_CARTA_DE_PAGOS_', 'TO_CHAR(sysdate,''yyyymmdd'')', NULL, NULL, 0, 1, 0, 'Activo', 1, 7, 1, 38, 'lnxni0230', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(397, 6, 'RPT_GARANTIAS_ACTIVADAS.sql', 'Reporte de Cobranza GARANTIAS_ACTIVADAS', '${PATH_DIRECTOR_SQL}', '${PATH_DIRECTOR_ENTRADA}/15_GARANTIAS_ACTIVADAS_', 'TO_CHAR(sysdate,''yyyymmdd'')', NULL, NULL, 0, 1, 0, 'Activo', 1, 7, 1, 38, 'lnxni0230', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(396, 6, 'RPT_FACTURA_CICLO.sql', 'Reporte de Cobranza FACTURA_CICLO', '/home/appextractor/Director/Sql', '/home/appextractor/Director/Entrada/14_FACTURA_CICLO_', 'TO_CHAR(sysdate,''yyyymmdd'')', NULL, NULL, 0, 10, 60, 'Inactivo', 1, 7, 0, 38, 'sunni005', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(395, 6, 'RPT_RESPALDO_DE_INGRESOS.sql', 'Reporte de Cobranza RESPALDO_DE_INGRESOS', '${PATH_DIRECTOR_SQL}', '${PATH_DIRECTOR_ENTRADA}/13_RESPALDO_DE_INGRESOS_', 'TO_CHAR(sysdate,''yyyymmdd'')', NULL, NULL, 0, 1, 0, 'Activo', 1, 7, 1, 38, 'lnxni0230', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(394, 6, 'RPT_PAGOS_MENSUALES.sql', 'Reporte de Cobranza PAGOS_MENSUALES', '${PATH_DIRECTOR_SQL}', '${PATH_DIRECTOR_ENTRADA}/12_PAGOS_MENSUALES_', 'TO_CHAR(sysdate,''yyyymmdd'')', NULL, NULL, 0, 1, 0, 'Activo', 1, 7, 1, 38, 'lnxni0230', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(393, 6, 'RPT_FACTURAS_DE_CONTADO.sql', 'Reporte de Cobranza FACTURAS_DE_CONTADO', '${PATH_DIRECTOR_SQL}', '${PATH_DIRECTOR_ENTRADA}/11_FACTURAS_DE_CONTADO_', 'TO_CHAR(sysdate,''yyyymmdd'')', NULL, NULL, 0, 1, 0, 'Activo', 1, 7, 1, 38, 'lnxni0230', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(392, 6, 'RPT_NOTAS_CREDITO_DEBITO_INTERNA.sql', 'Reporte de Cobranza NOTAS_CREDITO_DEBITO_INTERNA', '${PATH_DIRECTOR_SQL}', '${PATH_DIRECTOR_ENTRADA}/10_NOTAS_CREDITO_DEBITO_INTERNA_', 'TO_CHAR(sysdate,''yyyymmdd'')', NULL, NULL, 0, 1, 0, 'Activo', 1, 7, 1, 38, 'lnxni0230', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(391, 6, 'RPT_NOTAS_DE_CREDITO_Y_DEBITO.sql', 'Reporte de Cobranza NOTAS_DE_CREDITO_Y_DEBITO', '${PATH_DIRECTOR_SQL}', '${PATH_DIRECTOR_ENTRADA}/09_NOTAS_DE_CREDITO_Y_DEBITO_FACT_', 'TO_CHAR(sysdate,''yyyymmdd'')', NULL, NULL, 0, 1, 0, 'Activo', 1, 7, 1, 38, 'lnxni0230', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(390, 6, 'RPT_REPORTE_DE_PRORROGAS.sql', 'Reporte de Cobranza REPORTE_DE_PRORROGAS', '${PATH_DIRECTOR_SQL}', '${PATH_DIRECTOR_ENTRADA}/06_REPORTE_DE_PRORROGAS_', 'TO_CHAR(sysdate,''yyyymmdd'')', NULL, NULL, 0, 1, 0, 'Activo', 1, 7, 1, 38, 'lnxni0230', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(389, 6, 'RPT_REPORTE_DE_CLIENTES_SALTA.sql', 'Reporte de Cobranza REPORTE_DE_CLIENTES_SALTA', '${PATH_DIRECTOR_SQL}', '${PATH_DIRECTOR_ENTRADA}/05_REPORTE_DE_CLIENTES_SALTA_', 'TO_CHAR(sysdate,''yyyymmdd'')', NULL, NULL, 0, 1, 0, 'Activo', 1, 7, 1, 38, 'lnxni0230', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(388, 6, 'RPT_RESUMEN_CARTERA_INACTIVA.sql', 'Reporte de Cobranza RESUMEN_CARTERA_INACTIVA', '${PATH_DIRECTOR_SQL}', '${PATH_DIRECTOR_ENTRADA}/04_RESUMEN_CARTERA_INACTIVA_', 'TO_CHAR(sysdate,''yyyymmdd'')', NULL, NULL, 0, 1, 0, 'Activo', 1, 7, 1, 38, 'lnxni0230', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(387, 6, 'RPT_DETALLE_CARTERA_INACTIVA.sql', 'Reporte de Cobranza DETALLE_CARTERA_INACTIVA', '${PATH_DIRECTOR_SQL}', '${PATH_DIRECTOR_ENTRADA}/03_DETALLE_CARTERA_INACTIVA_', 'TO_CHAR(sysdate,''yyyymmdd'')', NULL, NULL, 0, 1, 0, 'Activo', 1, 7, 1, 38, 'lnxni0230', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(386, 6, 'RPT_REPORTE_DE_FINANCIAMIENTO.sql', 'Reporte de Cobranza REPORTE_DE_FINANCIAMIENTO', '${PATH_DIRECTOR_SQL}', '${PATH_DIRECTOR_ENTRADA}/18_REPORTE_DE_FINANCIAMIENTO_', 'TO_CHAR(sysdate,''yyyymmdd'')', NULL, NULL, 0, 1, 0, 'Activo', 1, 7, 1, 38, 'lnxni0230', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(385, 6, 'RPT_REPORTE_DE_CO_CARTERA.sql', 'Reporte de Cobranza REPORTE_DE_CO_CARTERA', '${PATH_DIRECTOR_SQL}', '${PATH_DIRECTOR_ENTRADA}/07_REPORTE_DE_CO_CARTERA_', 'TO_CHAR(sysdate,''yyyymmdd'')', NULL, NULL, 0, 1, 0, 'Activo', 1, 7, 1, 38, 'lnxni0230', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(384, 6, 'RPT_DETALLE_CARTERA_ACTIVA.sql', 'Reporte de Cobranza DETALLE_CARTERA_ACTIVA', '${PATH_DIRECTOR_SQL}', '${PATH_DIRECTOR_ENTRADA}/01_DETALLE_CARTERA_ACTIVA_', 'TO_CHAR(sysdate,''yyyymmdd'')', NULL, NULL, 0, 1, 0, 'Activo', 1, 7, 1, 38, 'lnxni0230', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(383, 6, 'RPT_Resumen_Cartera_Activa.sql', 'Reporte de Cobranza Resumen_Cartera_Activa', '${PATH_DIRECTOR_SQL}', '${PATH_DIRECTOR_ENTRADA}/02_RESUMEN_CARTERA_ACTIVA_', 'TO_CHAR(sysdate,''yyyymmdd'')', NULL, NULL, 0, 1, 0, 'Activo', 1, 7, 1, 38, 'lnxni0230', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(382, 6, 'RPT_REPORTE_DE_PAGOS_DIARIOS.sql', 'Reporte de Cobranza REPORTE_DE_PAGOS_DIARIOS', '/home/appextractor/Director/Sql', '/home/appextractor/Director/Entrada/08_REPORTE_DE_PAGOS_DIARIOS_', 'TO_CHAR(sysdate,''yyyymmdd'')', NULL, NULL, 0, 10, 60, 'Inactivo', 1, 7, 0, 38, 'sunni005', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(381, 0, 'MataProcesos.sh', 'Proceso encargado de dar kill a procesos en Unix', '/home/appextractor/Director/Sh', NULL, NULL, NULL, NULL, 0, 5, 60, 'Inactivo', 0, 0, 0, 11, 'sunni005', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(380, 15, 'RPT_IMAGEN_SALDO_PAYMENT.sql', 'Reporte de imagen de saldos Payment', '${PATH_DIRECTOR_SQL}', '${PATH_DIRECTOR_ENTRADA}/IMAGEN_SALDO_PAYMENT_', 'TO_CHAR(sysdate-1,''yyyymmdd'')', NULL, NULL, 0, 1, 0, 'Activo', 1, 7, 1, 28, 'lnxni0230', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(379, 15, 'RPT_TRANSACCIONES_PAYMENT.sql', 'Reporte de transacciones de Payment', '${PATH_DIRECTOR_SQL}', '${PATH_DIRECTOR_ENTRADA}/TRANSACCIONES_', 'TO_CHAR(sysdate-1,''yyyymmdd'')', NULL, NULL, 0, 1, 0, 'Activo', 1, 7, 1, 28, 'lnxni0230', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(378, 0, 'ConexionPMNIPayment.sh', 'Conexión', '${PATH_DIRECTOR_SH}', 'to_char(sysdate-1,''yyyymmdd'')', NULL, NULL, NULL, 0, 1, 0, 'Activo', 0, 0, 0, 26, 'lnxni0230', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(377, 15, 'RPT_ACTIVIDAD_PTOS_VENTA.sql', 'Reporte saldos de puntos de venta de distribuidores de Payment', '${PATH_DIRECTOR_SQL}', '${PATH_DIRECTOR_ENTRADA}/ACTIVIDAD_PTOS_VENTA_', 'TO_CHAR(sysdate-1,''yyyymmdd'')', NULL, NULL, 0, 1, 0, 'Activo', 1, 7, 1, 28, 'lnxni0230', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(376, 0, 'DEPURA_BAJAS_CHIPITOS_VENUS.sh', 'Realiza bajas de chipitos por cambio de linea de negocio', '/home/appextractor/Director/Sh', NULL, NULL, NULL, NULL, 1, 600, 60, 'Inactivo', 0, 0, 0, 11, 'sunni005', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(375, 0, 'ACTUALIZA_CHIPITOS_RECARGAS_VENUS.sh', 'Actualiza las recargas para lineas en chipitos', '/home/appextractor/Director/Sh', NULL, NULL, NULL, NULL, 1, 600, 60, 'Inactivo', 0, 0, 0, 11, 'sunni005', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(374, 3, 'facturas_pendientes_proc', 'Alarma Facturas Pendientes SCL', '/home/appextractor/Director/Sql', NULL, NULL, NULL, NULL, 0, 600, 60, 'Inactivo', 0, 0, 0, 27, 'sunni005', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(373, 13, 'TCN_CDR_GSM_NICMS_CRONOS2.sql', 'EXTRACTOR2 TRAFICO DE APOLO CDR', '/home/appextractor/Director/Sql', 'TO_CHAR(sysdate-3,''yyyymmdd'')', NULL, NULL, NULL, 0, 600, 60, 'Inactivo', 0, 0, 0, 11, 'sunni005', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(372, 0, 'RPT_FACT_RETAILERS.sh', 'Reporte de Facturas Retailers Payment (Ilse, Dina)', '${PATH_DIRECTOR_SH}', '${PATH_DIRECTOR_ENTRADA}/RPT_FACT_RETAILERS_PAYM_', 'TO_CHAR(sysdate-2,''yyyymm'')', 'TO_CHAR(sysdate-2,''yyyymm'')', NULL, 1, 1, 0, 'Activo', 1, 7, 1, 11, 'lnxni0230', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(371, 3, 'RPT_ADS_VENUS.sql', 'Reporte ADS Conoceme, DWH - Mercadeo', '/home/appextractor/Director/Sql', '/home/appextractor/Director/Entrada/BASE_ADS_', 'TO_CHAR(sysdate-1,''yyyymm'')', NULL, NULL, 1, 10, 60, 'Inactivo', 1, 7, 1, 11, 'sunni005', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(370, 3, 'PRC_ADS_VENUS.sql', 'Proceso ADS Conoceme, DWH - Mercadeo', '/home/appextractor/Director/Sql', NULL, NULL, NULL, NULL, 1, 5, 60, 'Inactivo', 0, 0, 0, 11, 'sunni005', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(369, 0, 'RPT_TARJETA_MOVISTAR_CREDOMATIC.sh', 'Reportes de tarjeta movistar credomatic', '/oradata2/oracle/aplicaciones/Director/Sh', '/oradata2/oracle/aplicaciones/Director/Entrada/', '/RepDWH/Reportes_Tarjeta_Movistar_Credomatic', 'TO_CHAR(SYSDATE-1,''yyyymm'')', 'TO_CHAR(SYSDATE-1,''yyyymm'')', 1, 10, 60, 'Activo', 0, 0, 0, 11, 'sunni005', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(367, 0, 'ALTAS_PREPAGO_SH.sh', 'Reporte de altas prepago SCL -- Activaciones', '/home/appextractor/Director/Sh', '/home/appextractor/Director/Entrada/ACTIVACION_PREPAGO_', 'TO_CHAR(sysdate-1,''yyyymm'')', 'TO_CHAR(sysdate-1,''yyyymm'')', NULL, 1, 10, 60, 'Inactivo', 1, 7, 1, 11, 'sunni005', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(364, 3, 'RPT_SMS_MOVIL.sql', 'Reportes de Consulta por Móvil - Crédito', '/home/appextractor/Director/Sql', '/home/appextractor/Director/Entrada/', 'RPT_SMS_MOVIL_', 'TO_CHAR(sysdate-1,''yyyymm'')', NULL, 0, 10, 60, 'Inactivo', 1, 7, 1, 11, 'sunni005', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(363, 3, 'RPT_SMS_IDENTIFICACION.sql', 'Reportes de Consulta por Identificación - Crédito', '${PATH_DIRECTOR_SQL}', '${PATH_DIRECTOR_ENTRADA}/', 'RPT_SMS_IDENTIFICACION_', 'TO_CHAR(sysdate-1,''yyyymm'')', NULL, 0, 1, 0, 'Activo', 1, 7, 1, 11, 'lnxni0230', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(362, 13, 'TCN_CDR_GSM_NICMS_CRONOS.sh', 'EXTRACTOR TRAFICO DE APOLO CDR', '${PATH_DIRECTOR_SH}', 'TO_CHAR(sysdate-1,''YYYYMMDD'')', NULL, NULL, NULL, 0, 1, 0, 'Activo', 0, 0, 0, 11, 'lnxni0230', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(361, 3, 'RPT_ASIGNACION_CARTERA.sql', 'Reporte Asignaci¿n de cartera morosa - Cobranzas', '${PATH_DIRECTOR_SQL}', '${PATH_DIRECTOR_ENTRADA}/RPT_ASIGNACION_CARTERA_', 'TO_CHAR(sysdate-1,''yyyymm'')', NULL, NULL, 1, 1, 0, 'Activo', 1, 7, 1, 11, 'lnxni0230', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(360, 3, 'PRC_ASIGCARTERA_CORREO_VENUS.sql', 'Proceso de Asignaci¿n de Cartera Correo - Cobranzas', '${PATH_DIRECTOR_SQL}', NULL, NULL, NULL, NULL, 1, 1, 0, 'Activo', 0, 0, 0, 11, 'lnxni0230', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(359, 6, 'PRC_ASIGNACION_CARTERA_INACTIVA.sql', 'Proceso de Asignaci¿n de Cartera Morosa Inactiva - Cobranzas', '${PATH_DIRECTOR_SQL}', NULL, NULL, NULL, NULL, 1, 1, 0, 'Activo', 0, 0, 0, 26, 'lnxni0230', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(358, 6, 'PRC_ASIGNACION_CARTERA_ACTIVA.sql', 'Proceso de Asignaci¿n de Cartera Morosa activa - Cobranzas', '${PATH_DIRECTOR_SQL}', NULL, NULL, NULL, NULL, 1, 1, 0, 'Activo', 0, 0, 0, 26, 'lnxni0230', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(352, 0, 'CONCILIA_SISTEMA.sh', 'Proceso Shell de Conciliación de Sistemas SCL y Altamira - Área de Ingresos', '/home/appextractor/Director/Sh', NULL, NULL, NULL, NULL, 1, 5, 60, 'Inactivo', 0, 0, 0, 24, 'sunni005', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(347, 6, 'RPT_CONCILIA_SCL.sql', 'Reporte Concilia SCL', '/home/appextractor/Director/Sql', '/home/appextractor/Director/Entrada/RPT_CONCILIA_SCL_', 'to_char(sysdate-1,''yyyymmdd'')', NULL, NULL, 1, 10, 60, 'Inactivo', 1, 7, 1, 26, 'sunni005', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(346, 1, 'RPT_CONCILIA_ALTAMIRA.sql', 'Reporte Concilia Altamira', '/home/appextractor/Director/Sql', '/home/appextractor/Director/Entrada/RPT_CONCILIA_ALTAMIRA_', 'to_char(sysdate-1,''yyyymmdd'')', NULL, NULL, 1, 10, 60, 'Inactivo', 1, 7, 1, 11, 'sunni005', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(345, 3, 'VJ_PRC_GAC_BUZON_GESTION.sql', 'Proceso', '${PATH_DIRECTOR_SQL}', 'to_char(sysdate-1, ''yyyymm'')||''01''', 'to_char(sysdate-1,''yyyymmdd'')', NULL, NULL, 1, 1, 0, 'Activo', 0, 0, 0, 11, 'lnxni0230', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(344, 3, 'VJ_PRC_GAC_CALLBACK.sql', 'Proceso', '/home/appextractor/Director/Sql', 'to_char(sysdate - 1, ''yyyymm'')||''01''', 'to_char(sysdate-1,''yyyymmdd'')', NULL, NULL, 1, 5, 60, 'Inactivo', 0, 0, 0, 11, 'sunni005', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(342, 3, 'RPT_GAC_CASOSCERRADOS.sql', 'Reporte casos cerrados - Clientes', '/home/appextractor/Director/Sql', '/home/appextractor/Director/Entrada/', 'CasosCerradosGAC_', 'to_char(sysdate-1,''yyyymm'')', NULL, 1, 10, 60, 'Inactivo', 1, 7, 1, 11, 'sunni005', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(341, 3, 'PRC_GAC_CASOSCERRADOS.sql', 'Proceso casos cerrados - Clientes', '/home/appextractor/Director/Sql', NULL, NULL, NULL, NULL, 0, 5, 60, 'Inactivo', 0, 0, 0, 11, 'sunni005', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(340, 3, 'APP_VALIDADWH_NIC.TMP_TOP10PREPAGO.sql', 'Extractor DWH', '/home/appextractor/Director/Sql', NULL, NULL, NULL, NULL, 1, 600, 60, 'Inactivo', 0, 0, 0, 11, 'sunni005', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(339, 3, 'RPT_IVR_SERIES_EQUIPOS.sql', 'Reporte Series Equipos IVR Altas Postpago', '${PATH_DIRECTOR_SQL}', '${PATH_DIRECTOR_ENTRADA}/RPT_IVR_series_equipos_', 'TO_CHAR(sysdate-1,''yyyymm'')', NULL, NULL, 0, 1, 0, 'Activo', 1, 7, 1, 11, 'lnxni0230', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(338, 3, 'RPT_IVR_STATUS_BURO.sql', 'Reporte Status Buró IVR Altas Postpago', '/home/appextractor/Director/Sql', '/home/appextractor/Director/Entrada/RPT_IVR_status_buro_', 'TO_CHAR(sysdate-1,''yyyymm'')', NULL, NULL, 0, 10, 60, 'Inactivo', 1, 7, 1, 11, 'sunni005', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(337, 3, 'RPT_IVR_STATUS_CONSULTAS.sql', 'Reporte de Status Consultas IVR Altas Postpago', '/home/appextractor/Director/Sql', '/home/appextractor/Director/Entrada/RPT_IVR_status_consultas_', 'TO_CHAR(sysdate-1,''yyyymm'')', NULL, NULL, 0, 10, 60, 'Inactivo', 1, 7, 1, 11, 'sunni005', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(336, 3, 'RPT_IVR_TIPO_CONSULTAS.sql', 'Reporte Tipos de Consulta IVR Altas Postpago', '${PATH_DIRECTOR_SQL}', '${PATH_DIRECTOR_ENTRADA}/RPT_IVR_tipo_consultas_', 'TO_CHAR(sysdate-1,''yyyymm'')', NULL, NULL, 0, 1, 0, 'Activo', 1, 7, 1, 11, 'lnxni0230', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(335, 0, 'UNIDADESF_MOVGEO.sh', 'Proceso Shell Unidades Fijas Movilidad Geográfica', '/home/appextractor/Director/Sh', '/home/appextractor/Director/Entrada/', 'traf_fijo_celdas_', 'TO_CHAR(sysdate-1,''yyyymmdd'')', '/RepDWH', 1, 5, 60, 'Inactivo', 0, 0, 0, 11, 'sunni005', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(333, 0, 'PRC_PAYMENT_DIST_ALL.sh', 'Proceso de Payment', '${PATH_DIRECTOR_SH}', NULL, NULL, NULL, NULL, 0, 1, 0, 'Activo', 0, 0, 0, 28, 'lnxni0230', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(332, 0, 'CREDIT_BUREAU_SH.sh', 'Proceso Shell del Buró Crédito Sin Riesgos', '/home/appextractor/Director/Sh', '/home/appextractor/Director/Entrada/', 'RPT_SINRIESGOS_', 'TO_CHAR(sysdate-1,''yyyymmdd'')', '/RepDWH/ARCHIVOS_BURO_CREDITO', 1, 10, 60, 'Inactivo', 0, 0, 0, 11, 'sunni005', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(331, 3, 'RPT_CREDITBUREAU.sql', 'Reporte de crédito sin riesgos -  Área Crédito', '/home/appextractor/Director/Sql', '/home/appextractor/Director/Entrada/RPT_SINRIESGOS_', 'TO_CHAR(sysdate-1,''yyyymmdd'')', 'TO_CHAR(sysdate-1,''yyyymmdd'')', NULL, 1, 10, 60, 'Inactivo', 1, 7, 1, 11, 'sunni005', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(330, 3, 'PRC_CLIENTSTATUS.sql', 'Proceso de crédito sin riesgos -  Área Crédito', '/home/appextractor/Director/Sql', NULL, NULL, NULL, NULL, 1, 5, 60, 'Inactivo', 0, 0, 0, 11, 'sunni005', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(329, 3, 'RPT_AMIGOS_MOVISTAR.sql', 'Reporte Amigos Movistar Fide-Mercadeo', '/home/appextractor/Director/Sql', '/home/appextractor/Director/Entrada/RPT_Amigos_Movistar', NULL, NULL, NULL, 1, 10, 60, 'Inactivo', 1, 7, 1, 11, 'sunni005', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(328, 3, 'RPT_IMEIS_DISTINTOS.sql', 'Reporte de Imeis Distintos - Area Fraude', '${PATH_DIRECTOR_SQL}', '${PATH_DIRECTOR_ENTRADA}/TRAF_LINEAS_DIVERSIDAD_IMEI_', 'TO_CHAR(sysdate-1,''yyyymmdd'')', NULL, NULL, 1, 1, 0, 'Inactivo', 1, 7, 1, 11, 'lnxni0230', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(327, 3, 'PRC_IMEIS_DISTINTOS.sql', 'Proceso de Imeis Distintos - Area Fraude', '${PATH_DIRECTOR_SQL}', NULL, NULL, NULL, NULL, 0, 1, 0, 'Inactivo', 0, 0, 0, 11, 'lnxni0230', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(326, 3, 'RPT_SERIES_SIMCARD.sql', 'Reporte de Serie de Ventas Individuales', '/home/appextractor/Director/Sql', '/home/appextractor/Director/Entrada/RPT_FACT_NPW_SIMCARD_', 'TO_CHAR(sysdate-1,''yyyymm'')', NULL, NULL, 1, 10, 60, 'Inactivo', 1, 7, 1, 11, 'sunni005', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(325, 3, 'PRC_SERIES_SIMCARD_2.sql', 'Proceso de Serie 2 de Ventas Individuales', '/home/appextractor/Director/Sql', 'TO_CHAR(sysdate-1,''yyyymm'')', NULL, NULL, NULL, 1, 5, 60, 'Inactivo', 0, 0, 0, 11, 'sunni005', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(324, 6, 'PRC_SERIES_SIMCARD_1.sql', 'Proceso de Serie 1 de Ventas Individuales', '${PATH_DIRECTOR_SQL}', 'TO_CHAR(sysdate-1,''yyyymm'')', NULL, NULL, NULL, 0, 1, 0, 'Inactivo', 0, 0, 0, 26, 'lnxni0230', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(323, 3, 'RPT_DETALLE_AMIGOS_MOVISTAR.sql', 'Reporte de Detalle del Servicio Amigos Movistar Fide', '/home/appextractor/Director/Sql', '/home/appextractor/Director/Entrada/RPT_Detalle_Amigos_Movistar_', 'TO_CHAR(sysdate-1,''yyyymm'')', NULL, NULL, 0, 10, 60, 'Inactivo', 1, 7, 1, 11, 'sunni005', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(322, 3, 'RPT_RESUMEN_AMIGOS_MOVISTAR.sql', 'Reporte de Resumen del Servicio Amigos Movistar Fide', '/home/appextractor/Director/Sql', '/home/appextractor/Director/Entrada/RPT_Resumen_Amigos_Movistar_', 'TO_CHAR(sysdate-1,''yyyymm'')', NULL, NULL, 0, 10, 60, 'Inactivo', 1, 7, 1, 11, 'sunni005', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(321, 3, 'RPT_BONOSANTIGUEDAD_PREPAGO.sql', 'Reporte Bonos de Antiguedad Mercadeo', '/home/appextractor/Director/Sql', '/home/appextractor/Director/Entrada/RPT_Seguimiento_BonosAntiguedad_', 'TO_CHAR(sysdate-1,''yyyymm'')', NULL, NULL, 0, 10, 60, 'Inactivo', 1, 7, 0, 11, 'sunni005', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(320, 3, 'RPT_ESTATUS_PINES_PREPAGO.sql', 'Reporte Estado de Pines Mercadeo', '/home/appextractor/Director/Sql', '/home/appextractor/Director/Entrada/RPT_Seguimiento_PinesPrepago_', 'TO_CHAR(sysdate-1,''yyyymm'')', NULL, NULL, 0, 10, 60, 'Inactivo', 1, 7, 0, 11, 'sunni005', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(319, 3, 'RPT_SIMCARD_NPW_FACTURADAS.sql', 'Reporte Simcards NPW Facturadas', '/home/appextractor/Director/Sql', '/home/appextractor/Director/Entrada/RPT_SIMCARDS_NPW_FACTURADAS', NULL, NULL, NULL, 1, 10, 60, 'Inactivo', 1, 7, 1, 11, 'sunni005', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(318, 6, 'PRC_SIMCARD_NPW_FACTURADAS.sql', 'Proceso Simcards NPW Facturadas', '${PATH_DIRECTOR_SQL}', NULL, NULL, NULL, NULL, 1, 1, 0, 'Activo', 0, 0, 0, 26, 'lnxni0230', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(315, 6, 'RPT_ABONADOS_POSPERSONALIZADOS.sql', 'Reporte de Clientes Post Personalizados', '${PATH_DIRECTOR_SQL}', '${PATH_DIRECTOR_ENTRADA}/Abonados_Postpersonalizados_', 'TO_CHAR(sysdate-1,''yyyymmdd'')', NULL, NULL, 1, 1, 0, 'Activo', 1, 7, 1, 26, 'lnxni0230', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(314, 6, 'RPT_ABONADOS_PREPERSONALIZADOS.sql', 'Reporte de Clientes Pre Personalizados', '${PATH_DIRECTOR_SQL}', '${PATH_DIRECTOR_ENTRADA}/Abonados_Prepersonalizados_', 'TO_CHAR(sysdate-1,''yyyymmdd'')', NULL, NULL, 1, 1, 0, 'Activo', 1, 7, 1, 26, 'lnxni0230', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(313, 6, 'RPT_SS_BAJAS_DIARIAS.sql', 'Reporte de Bajas Diarias', '${PATH_DIRECTOR_SQL}', '${PATH_DIRECTOR_ENTRADA}/SS_BajasAbonados_', 'TO_CHAR(sysdate-5,''yyyymm'')', NULL, NULL, 1, 1, 0, 'Activo', 1, 7, 1, 26, 'lnxni0230', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(312, 6, 'RPT_SS_ALTAS_DIARIAS.sql', 'Reporte de Altas Diarias', '${PATH_DIRECTOR_SQL}', '${PATH_DIRECTOR_ENTRADA}/SS_AltasAbonados_', 'TO_CHAR(sysdate-1,''yyyymm'')', NULL, NULL, 1, 1, 0, 'Activo', 1, 7, 1, 26, 'lnxni0230', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(311, 6, 'PRC_SSFACTURADOS.sql', 'Proceso', '${PATH_DIRECTOR_SQL}', NULL, NULL, NULL, NULL, 1, 1, 0, 'Activo', 0, 0, 0, 26, 'lnxni0230', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(310, 0, 'Carga_Posinfo_Xius.sh', 'Carga archivo Posinfo de Xius', '/home/appextractor/Director/Sh', 'to_char(sysdate, ''ddmmyyyy'') ', NULL, NULL, NULL, 1, 600, 60, 'Inactivo', 0, 0, 0, 24, 'sunni005', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(309, 3, 'valida_ult_evento.sql', 'VALIDA ULTIMO EVENTO EN APOLO ', '/home/appextractor/Director/Sql', NULL, NULL, NULL, NULL, 1, 600, 60, 'Inactivo', 0, 0, 0, 11, 'sunni005', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(308, 6, 'RPT_PAGOS_RECEXT_NOAPLICADOS.sql', 'Reporte de Pagos Recaudacion Externa No Aplicados', '${PATH_DIRECTOR_SQL}', '${PATH_DIRECTOR_ENTRADA}/PagosRecaudacionExternaNoAplicados_', 'TO_CHAR(sysdate-1,''yyyymmdd'')', NULL, NULL, 1, 1, 0, 'Activo', 1, 7, 0, 26, 'lnxni0230', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(307, 6, 'RPT_PAGOS_RECEXT_APLICADOS.sql', 'Reporte de Pagos Recaudacion Externa Aplicados', '${PATH_DIRECTOR_SQL}', '${PATH_DIRECTOR_ENTRADA}/PagosRecaudacionExternaAplicados_', 'TO_CHAR(sysdate-1,''yyyymm'')', NULL, NULL, 1, 1, 0, 'Activo', 1, 7, 0, 26, 'lnxni0230', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(306, 6, 'RPT_PAGOS_RECEXT_ANOMALIAS.sql', 'Reporte de Pagos Recaudacion Externa Con Anomalías', '${PATH_DIRECTOR_SQL}', '${PATH_DIRECTOR_ENTRADA}/PagosRecaudacionExternaConAnomalias_', 'TO_CHAR(sysdate-1,''yyyymmdd'')', NULL, NULL, 1, 1, 0, 'Activo', 1, 7, 0, 26, 'lnxni0230', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(305, 3, 'PRC_PREPAID_CUSTOMER_IVR.sql', 'Proceso', '/home/appextractor/Director/Sql', NULL, NULL, NULL, NULL, 1, 5, 60, 'Inactivo', 0, 0, 0, 11, 'sunni005', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(304, 5, 'AL_FABRICANTES', 'Extractor SCL', 'Extractor Full', NULL, NULL, NULL, NULL, 1, 1, 300, 'Activo', 0, 0, 0, 11, 'lnxni0230', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(303, 5, 'GE_TIPDIRECCION', 'Extractor SCL', 'Extractor Full', NULL, NULL, NULL, NULL, 1, 1, 300, 'Activo', 0, 0, 0, 11, 'lnxni0230', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(302, 5, 'GA_CATRIBUTCLIE', 'Extractor SCL', 'Extractor Full', NULL, NULL, NULL, NULL, 1, 1, 300, 'Activo', 0, 0, 0, 11, 'lnxni0230', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(301, 3, 'RPT_PAGOSREV_SCL.sql', 'Reporte Pagos Revision SCL', '/home/appextractor/Director/Sql', '/home/appextractor/Director/Entrada/PagosRevSCL_', 'to_char(sysdate-1,''yyyymm'')', NULL, NULL, 1, 5, 60, 'Inactivo', 1, 7, 0, 11, 'sunni005', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(300, 3, 'RPT_NUMBERS_NOTFOUND_ALTAMIRA.sql', 'Reporte números no encontrados Estados Numeración Altamira', '/home/appextractor/Director/Sql', '/home/appextractor/Director/Entrada/RPT_NumerosNoEncontrados_Altamira_', NULL, NULL, NULL, 1, 10, 60, 'Inactivo', 1, 7, 1, 11, 'sunni005', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(299, 3, 'RPT_REVALUATION_INVENTORIES.sql', 'Reporte Revaluación Inventario', '${PATH_DIRECTOR_SQL}', '${PATH_DIRECTOR_ENTRADA}/RPT_Terminales_Revalorizacion', NULL, NULL, NULL, 1, 1, 0, 'Activo', 1, 7, 1, 11, 'lnxni0230', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(298, 3, 'RPT_STATE_NUMBERING_ALTAMIRA.sql', 'Reporte estado de numeración Altamira', '/home/appextractor/Director/Sql', '/home/appextractor/Director/Entrada/RPT_Consolidado_Estados_Altamira_', NULL, NULL, NULL, 1, 10, 60, 'Inactivo', 1, 7, 1, 11, 'sunni005', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(297, 3, 'RPT_PAGOS_SCL.sql', 'Reporte Pagos SCL', '${PATH_DIRECTOR_SQL}', '${PATH_DIRECTOR_ENTRADA}/PagosSCL_', 'to_char(sysdate-1,''yyyymm'')', NULL, NULL, 1, 1, 0, 'Activo', 1, 7, 0, 11, 'lnxni0230', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(296, 6, 'PRC_PAGOS_SCL.sql', 'Proceso', '${PATH_DIRECTOR_SQL}', 'to_char(sysdate-1,''yyyymm'')', NULL, NULL, NULL, 1, 1, 0, 'Activo', 0, 0, 0, 26, 'lnxni0230', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(295, 3, 'pagos_web.sql', 'REPORTE DE TELEPAGOS SE LE CONOCE COMO PagosAplicacionWEB', '${PATH_DIRECTOR_SQL}', 'to_char(sysdate-1,''yyyymmdd'')', '${PATH_DIRECTOR_ENTRADA}/', NULL, NULL, 1, 1, 0, 'Activo', 1, 7, 0, 11, 'lnxni0230', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(294, 3, 'rpt_estado_chipitos.sql', 'Reporte genera listado de chipitos con su monto de recarga', '/home/appextractor/Director/Sql', '/home/appextractor/Director/Entrada/RPT_ESTADO_CHIPITOS_', NULL, NULL, NULL, 1, 600, 60, 'Inactivo', 1, 7, 1, 11, 'sunni005', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(293, 6, 'RPT_NPW_DEVOLUCIONES.sql', 'Reporte de NPW Devoluciones', '${PATH_DIRECTOR_SQL}', '${PATH_DIRECTOR_ENTRADA}/RPT_NPW_DEVOLUCIONES', 'to_char(sysdate -1,''YYYY'')', NULL, NULL, 1, 1, 0, 'Activo', 1, 7, 1, 11, 'lnxni0230', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(292, 5, 'GA_INFACCEL', 'Extractor SCL', 'Extractor Full', NULL, NULL, NULL, NULL, 0, 1, 300, 'Activo', 0, 0, 0, 11, 'lnxni0230', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(291, 5, 'TA_NUMNACIONAL', 'Extractor SCL', 'Extractor Full', NULL, NULL, NULL, NULL, 0, 1, 300, 'Activo', 0, 0, 0, 11, 'lnxni0230', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(290, 5, 'TOL_BOLSA_PLAN', 'Extractor SCL', 'Extractor Full', NULL, NULL, NULL, NULL, 0, 1, 300, 'Activo', 0, 0, 0, 11, 'lnxni0230', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(289, 3, 'RPT_SALE_CHIPITOS.sql', 'Reporte Chipitos Marcados OUT', '/home/appextractor/Director/Sql', 'to_char(sysdate-1,''yyyymmdd'')', '/home/appextractor/Director/Entrada/CHIPITOS_MARCADOS_OUT_', NULL, NULL, 1, 600, 60, 'Inactivo', 1, 7, 0, 11, 'sunni005', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(288, 3, 'EXTRACT_GPRS_APOLO.sql', 'EXTRACTOR TRAFICO DE APOLO GPRS', '/home/appextractor/Director/Sql', 'to_char(sysdate-1,''yyyymmdd'')', NULL, NULL, NULL, 1, 600, 60, 'Inactivo', 0, 0, 0, 11, 'sunni005', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(287, 6, 'debito_automatico.sql', 'Reporte de debito automatico para ventas individuales', '${PATH_DIRECTOR_SQL}', 'to_char(sysdate-1,''yyyymm'')', '${PATH_DIRECTOR_ENTRADA}/ALTAS_DEBITO_ATUO_', NULL, NULL, 1, 1, 0, 'Activo', 1, 7, 0, 26, 'lnxni0230', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(286, 3, 'RPT_VENTAS_FINANCIADAS.sql', 'Reporte de ventas financiadas', '/home/appextractor/Director/Sql', '/home/appextractor/Director/Entrada/RPT_VENTAS_FINANCIADAS_', NULL, NULL, NULL, 1, 10, 60, 'Inactivo', 1, 7, 1, 11, 'sunni005', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(285, 5, 'CO_CANCELADOS', 'Extractor SCL', 'Extractor Full', NULL, NULL, NULL, NULL, 1, 1, 300, 'Activo', 0, 0, 0, 11, 'lnxni0230', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(284, 0, 'SIR.sh', 'Shell FTP de Cartera SIR', '/home/appextractor/Director/Sh', 'to_char(sysdate,''yyyymmdd'')', NULL, NULL, NULL, 1, 5, 60, 'Inactivo', 0, 0, 0, 11, 'sunni005', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(283, 3, 'RPT_SIR_clientes.sql', 'Reporte Cartera Clientes', '/home/appextractor/Director/Sql', '/home/appextractor/Director/Entrada/SCL_NI_', 'clientes.txt', NULL, NULL, 1, 10, 60, 'Inactivo', 1, 11, 0, 11, 'sunni005', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(282, 3, 'RPT_SIR_cartera_nociclo.sql', 'Reporte Cartera No Ciclo', '/home/appextractor/Director/Sql', '/home/appextractor/Director/Entrada/SCL_NI_', 'consumos.txt', NULL, NULL, 1, 10, 60, 'Inactivo', 1, 11, 0, 11, 'sunni005', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(281, 3, 'RPT_SIR_cartera_ciclo.sql', 'Reporte Cartera Ciclo', '/home/appextractor/Director/Sql', '/home/appextractor/Director/Entrada/SCL_NI_', 'cartera.txt', NULL, NULL, 0, 10, 60, 'Inactivo', 1, 11, 0, 15, 'sunni005', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(280, 3, 'RPT_VENTAS_POSTPAGO_SINTRAFICO.sql', 'Ventas Postpago Sin Tráfico', '/home/appextractor/Director/Sql', '/home/appextractor/Director/Entrada/RPT_VENTAS_POSTPAGO_SINTRAFICO_', NULL, NULL, NULL, 1, 10, 60, 'Inactivo', 1, 7, 0, 11, 'sunni005', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(279, 3, 'rpt_imsi_apolo_inv.sql', 'PROCESO TRAF IMSI PARA FRAUDE', '/home/appextractor/Director/Sql', '/home/appextractor/Director/Entrada/rpt_imsi_apolo_inv_', NULL, NULL, NULL, 1, 5, 60, 'Inactivo', 1, 7, 0, 11, 'sunni005', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(278, 3, 'notif_altas_x_hora.sql', 'NOTIFICACIONES EMAIL', '/home/appextractor/Director/Sql', NULL, NULL, NULL, NULL, 1, 600, 60, 'Inactivo', 0, 0, 0, 23, 'sunni005', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(277, 0, 'ftp_tdr_fraud.sh', 'FTP', '/home/appextractor/Director/Sh', 'TDR_n_', '/home/appextractor/Director/Entrada', NULL, NULL, 1, 600, 60, 'Inactivo', 0, 0, 0, 11, 'sunni005', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(276, 3, 'RPT_PLANES_CC_ALTAMIRA.sql', 'SALIDA del  REPORTE PLANES ALTAMIRA', '/home/appextractor/Director/Sql', '/home/appextractor/Director/Entrada/REPORTE_PLANES_ALTAMIRA_CC_', NULL, NULL, NULL, 1, 600, 60, 'Inactivo', 0, 0, 0, 11, 'sunni005', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(275, 3, 'PRC_USUARIOS_ACTIVOS.sql', 'Proceso', '${PATH_DIRECTOR_SQL}', NULL, NULL, NULL, NULL, 0, 1, 0, 'Activo', 0, 0, 0, 11, 'lnxni0230', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(274, 3, 'PRC_TIPOLOGIA_A_BUZON_NUEVO.sql', 'Proceso', '/home/appextractor/Director/Sql', NULL, NULL, NULL, NULL, 0, 10, 60, 'Inactivo', 0, 0, 0, 11, 'sunni005', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(273, 3, 'PRC_RPT_PLANCES_CC_ALTAMIRA.sql', 'PROCESO DE REPORTE PLANES ALTAMIRA', '/home/appextractor/Director/Sql', NULL, NULL, NULL, NULL, 1, 600, 60, 'Inactivo', 0, 0, 0, 11, 'sunni005', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(272, 5, 'GA_LIMITE_CLIABO_TO', 'Extractor SCL', 'Extractor Full', NULL, NULL, NULL, NULL, 1, 1, 300, 'Activo', 0, 0, 0, 11, 'lnxni0230', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(271, 5, 'GA_USUAMIST', 'Extractor SCL', 'Extractor Full', NULL, NULL, NULL, NULL, 1, 1, 300, 'Activo', 0, 0, 0, 11, 'lnxni0230', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(270, 5, 'CO_INMUNES', 'Extractor SCL', 'Extractor Full', NULL, NULL, NULL, NULL, 1, 1, 300, 'Activo', 0, 0, 0, 11, 'lnxni0230', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(269, 5, 'VE_VENDEALER', 'Extractor SCL', 'Extractor Full', NULL, NULL, NULL, NULL, 1, 1, 300, 'Activo', 0, 0, 0, 11, 'lnxni0230', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(268, 5, 'CO_UNIPAC', 'Extractor SCL', 'Extractor Full', NULL, NULL, NULL, NULL, 1, 1, 300, 'Activo', 0, 0, 0, 11, 'lnxni0230', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(267, 5, 'GA_CAUSUSP', 'Extractor SCL', 'Extractor Full', NULL, NULL, NULL, NULL, 1, 1, 300, 'Activo', 0, 0, 0, 11, 'lnxni0230', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(266, 5, 'GA_SUSPREHABO', 'Extractor SCL', 'Extractor Full', NULL, NULL, NULL, NULL, 1, 1, 300, 'Activo', 0, 0, 0, 11, 'lnxni0230', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(265, 3, 'web_Altas_Prepago.sql', 'Reporte INTRANET', '/home/appextractor/Director/Sql', NULL, NULL, NULL, NULL, 1, 600, 60, 'Inactivo', 1, 8, 0, 11, 'sunni005', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(264, 3, 'FRAUDVIEW_TDR.SQL', 'PROCESO EXTRAE TDR para FraudView', '/home/appextractor/Director/Sql', 'to_char(sysdate-1,''yyyymmdd'')', '/home/appextractor/Director/Entrada', NULL, NULL, 1, 600, 60, 'Inactivo', 0, 0, 0, 11, 'sunni005', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(263, 3, 'rpt_imei_apolo_inv.sql', 'PROCESO TRAF IMEI PARA FRAUDE', '/home/appextractor/Director/Sql', '/home/appextractor/Director/Entrada/traf_imei_apolo_', NULL, NULL, NULL, 1, 600, 60, 'Inactivo', 1, 7, 0, 11, 'sunni005', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(262, 6, 'GA_CELNUM_USO', 'Extractor SCL', 'Extractor Full', NULL, NULL, NULL, NULL, 1, 1, 300, 'Activo', 0, 0, 0, 26, 'lnxni0230', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(261, 6, 'GA_CATNUMER', 'Extractor SCL', 'Extractor Full', NULL, NULL, NULL, NULL, 1, 1, 300, 'Activo', 0, 0, 0, 26, 'lnxni0230', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(260, 3, 'agenda_expandida.sql', 'PROCESO GENERA REPORTE AGENDA EXPANDIDA COBRANZA', '/home/appextractor/Director/Sql', 'to_char(sysdate-1,''yyyymm'')', '/home/appextractor/Director/Entrada/AGENDA_EXPANDIDA_', NULL, NULL, 1, 600, 60, 'Inactivo', 1, 7, 0, 11, 'sunni005', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(259, 2, 'FRAUDVIEW_BC.SQL', 'PROCESO genera interfaz Balance checking paara FraudView', '/home/appextractor/Director/Sql', 'to_char(sysdate-1,''yyyymmdd'')', '/home/appextractor/Director/Entrada/', NULL, NULL, 1, 600, 60, 'Inactivo', 0, 0, 0, 11, 'sunni005', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(255, 3, 'RPT_COMPARACION_FOTOS_MOVIMIENTOS.sql', 'Reporte', '/home/appextractor/Director/Sql', '/home/appextractor/Director/Entrada/RPT_COMPARACION_FOTOS_MOVIMIENTOS.txt', NULL, NULL, NULL, 1, 60, 10, 'Inactivo', 1, 7, 1, 11, 'sunni005', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(254, 3, 'RPT_COMPARACION_FOTOS_ABONADO.sql', 'Reporte', '/home/appextractor/Director/Sql', '/home/appextractor/Director/Entrada/RPT_COMPARACION_FOTOS_ABONADO.txt', NULL, NULL, NULL, 1, 60, 10, 'Inactivo', 1, 7, 1, 11, 'sunni005', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(253, 3, 'PRC_COMPARACION_FOTOS.sql', 'Proceso', '/home/appextractor/Director/Sql', 'TO_NUMBER(TO_CHAR(SYSDATE-2,''YYYYMMDD''))', 'TO_NUMBER(TO_CHAR(SYSDATE-1,''YYYYMMDD''))', NULL, NULL, 1, 60, 10, 'Inactivo', 0, 0, 0, 11, 'sunni005', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(252, 3, 'ultima_recarga.sql', 'PROCESO EXTRAE ULTIMA REC COMPRADA ABONADOS', '/home/appextractor/Director/Sql', NULL, NULL, NULL, NULL, 1, 600, 60, 'Inactivo', 0, 0, 0, 11, 'sunni005', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(251, 3, 'RPT_SIMCARD_BODEGA_TRAFICO.sql', 'Reporte Finanzas', '/home/appextractor/Director/Sql', '/home/appextractor/Director/Entrada/SIMCARD_BODEGA_TRAFICO.txt', NULL, NULL, NULL, 1, 10, 60, 'Inactivo', 1, 7, 0, 11, 'sunni005', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(250, 6, 'GED_PARAMETROS', 'Extractor SCL', 'Extractor Full', NULL, NULL, NULL, NULL, 1, 1, 300, 'Activo', 0, 0, 0, 26, 'lnxni0230', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(249, 6, 'CO_PAGOSCONC', 'Extractor SCL', 'Extractor Full', NULL, NULL, NULL, NULL, 1, 60, 60, 'Inactivo', 0, 0, 0, 26, 'sunni005', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(248, 17, 'BDDWH.DWD_TIPO_ENVIO', 'Extractor DWH', 'Extractor Full', NULL, NULL, NULL, NULL, 1, 60, 60, 'Inactivo', 0, 0, 0, 11, 'sunni005', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(247, 3, 'DWD_TIPO_SERVICIO.sql', 'Extractor DWH', '/home/appextractor/Director/Sql', NULL, NULL, NULL, NULL, 1, 600, 60, 'Inactivo', 0, 0, 0, 11, 'sunni005', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(245, 3, 'RPT_SALDO_SUSPENDIDO.sql', 'Reporte de Finanzas', '/home/appextractor/Director/Sql', '/home/appextractor/Director/Entrada/RPT_SALDO_SUSPENDIDO_', NULL, NULL, NULL, 1, 10, 60, 'Inactivo', 1, 7, 1, 11, 'sunni005', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(244, 3, 'PRC_SALDO_SUSPENDIDO.sql', 'Proceso', '/home/appextractor/Director/Sql', NULL, NULL, NULL, NULL, 0, 5, 60, 'Inactivo', 0, 0, 0, 11, 'sunni005', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(243, 2, 'PRC_NUMEROS_HIBERNADOE.sql', 'Proceso', '/home/appextractor/Director/Sql', NULL, NULL, NULL, NULL, 1, 5, 60, 'Inactivo', 0, 0, 0, 11, 'sunni005', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(242, 3, 'PRC_NUMEROS_HIBERNADOD.sql', 'Proceso', '/home/appextractor/Director/Sql', NULL, NULL, NULL, NULL, 1, 5, 60, 'Inactivo', 0, 0, 0, 11, 'sunni005', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(241, 2, 'PRC_NUMEROS_HIBERNADOC.sql', 'Proceso', '/home/appextractor/Director/Sql', NULL, NULL, NULL, NULL, 1, 5, 60, 'Inactivo', 0, 0, 0, 11, 'sunni005', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(240, 2, 'PRC_NUMEROS_HIBERNADOS.sql', 'Proceso', '/home/appextractor/Director/Sql', NULL, NULL, NULL, NULL, 1, 5, 60, 'Inactivo', 0, 0, 0, 11, 'sunni005', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(239, 3, 'RPT_PARQUE_ENTRETONOS.sql', 'Reporte de Servicio Valor Agregado Aleman Saddy', '/home/appextractor/Director/Sql', '/home/appextractor/Director/Entrada/RPT_PARQUE_ENTRETONOS_', NULL, NULL, NULL, 1, 10, 60, 'Inactivo', 1, 7, 1, 11, 'sunni005', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(238, 3, 'PRC_PARQUE_ENTRETONOS.sql', 'Proceso', '${PATH_DIRECTOR_SQL}', NULL, NULL, NULL, NULL, 1, 1, 0, 'Inactivo', 0, 0, 0, 11, 'lnxni0230', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(237, 1, 'PRC_CHG000000029437E.sql', 'Proceso', '/home/appextractor/Director/Sql', NULL, NULL, NULL, NULL, 1, 5, 60, 'Inactivo', 0, 0, 0, 11, 'sunni005', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(236, 3, 'PRC_CHG000000029437D.sql', 'Proceso', '/home/appextractor/Director/Sql', NULL, NULL, NULL, NULL, 1, 5, 60, 'Inactivo', 0, 0, 0, 11, 'sunni005', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(235, 1, 'PRC_CHG000000029437C.sql', 'Proceso', '/home/appextractor/Director/Sql', NULL, NULL, NULL, NULL, 1, 5, 60, 'Inactivo', 0, 0, 0, 11, 'sunni005', 0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS
(IDPROC, IDCONEX, NOMBRE, DESCRIPCION, "PATH", PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, DEPENDENCIA, INTENTOS, ESPERA_INTENTO, ESTADO, FTP, IDHOST, COMPRESION, IDCRONTAB, NODE, IDNOTIF)
VALUES(233, 3, 'PRC_CHG000000029437B.sql', 'Proceso', '/home/appextractor/Director/Sql', NULL, NULL, NULL, NULL, 1, 5, 60, 'Inactivo', 0, 0, 0, 11, 'sunni005', 0);