-- APP_SCL_ALTAMIRA.CP_PROCESOS definition

CREATE TABLE "APP_SCL_ALTAMIRA"."CP_PROCESOS" 
   (	"IDPROC" NUMBER, 
	"IDCONEX" NUMBER, 
	"NOMBRE" VARCHAR2(100), 
	"DESCRIPCION" VARCHAR2(100), 
	"PATH" VARCHAR2(100), 
	"PARAMETRO1" VARCHAR2(150), 
	"PARAMETRO2" VARCHAR2(150), 
	"PARAMETRO3" VARCHAR2(150), 
	"PARAMETRO4" VARCHAR2(150), 
	"DEPENDENCIA" NUMBER NOT NULL ENABLE, 
	"INTENTOS" NUMBER NOT NULL ENABLE, 
	"ESPERA_INTENTO" NUMBER NOT NULL ENABLE, 
	"ESTADO" VARCHAR2(10) DEFAULT 'Activo', 
	"FTP" NUMBER DEFAULT 0, 
	"IDHOST" NUMBER DEFAULT 0, 
	"COMPRESION" NUMBER DEFAULT 0, 
	"IDCRONTAB" NUMBER DEFAULT 11, 
	"NODE" VARCHAR2(10), 
	 CONSTRAINT "CP_PROCESOS_PK" PRIMARY KEY ("IDCONEX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCL_DATA" ;

CREATE SEQUENCE cp_procesos_sequence;

CREATE OR REPLACE TRIGGER "APP_SCL_ALTAMIRA"."CP_PROCESOS_ON_INSERT"   BEFORE INSERT ON "APP_SCL_ALTAMIRA"."CP_PROCESOS"  FOR EACH ROWBEGIN
  SELECT cp_procesos_sequence.nextval
  INTO :new.IDPROC
  FROM dual;
END;

/
ALTER TRIGGER "APP_SCL_ALTAMIRA"."CP_PROCESOS_ON_INSERT" ENABLE;

CREATE UNIQUE INDEX "APP_SCL_ALTAMIRA"."PK_PROCESOS_NOMBRE" ON "APP_SCL_ALTAMIRA"."CP_PROCESOS" ("NOMBRE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCL_DATA" ;
  CREATE UNIQUE INDEX "APP_SCL_ALTAMIRA"."PK_PROCESOS_IDPROC" ON "APP_SCL_ALTAMIRA"."CP_PROCESOS" ("IDPROC") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCL_DATA" ;
  CREATE UNIQUE INDEX "APP_SCL_ALTAMIRA"."CP_PROCESOS_PK" ON "APP_SCL_ALTAMIRA"."CP_PROCESOS" ("IDCONEX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

GRANT SELECT ON "APP_SCL_ALTAMIRA"."CP_PROCESOS" TO "URLTUXEDO";
  GRANT SELECT ON "APP_SCL_ALTAMIRA"."CP_PROCESOS" TO "APP_APLICACIONES";