INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS (IDPROC,IDCONEX,NOMBRE,DESCRIPCION,"PATH",PARAMETRO1,PARAMETRO2,PARAMETRO3,PARAMETRO4,DEPENDENCIA,INTENTOS,ESPERA_INTENTO,ESTADO,FTP,IDHOST,COMPRESION,IDCRONTAB,NODE,IDNOTIF) VALUES
	 (457,5,'lol','dwes','srggsd','er','tgrtg','ert5wer','ertwe',1,4,2,'Activo',0,6,0,69,'node',0),
	 (456,1,'nombre','desc','path',NULL,NULL,NULL,NULL,0,3,5,'Activo',0,1,0,63,'node',3),
	 (455,4,'name','desc','path',NULL,NULL,NULL,NULL,1,3,1,'Activo',0,2,0,69,'node',2),
	 (454,0,'RPT_BUZONEROS_GAC.sh','Reporte Buzoneros GAC - Solicita: Fidelizacion 1/04/2024','${PATH_DIRECTOR_SH}','${PATH_DIRECTOR_ENTRADA}','to_char(''RPT_BUZONEROS_GAC_'' || to_char(sysdate - 2, ''YYYYMM'') || ''.txt'')',NULL,NULL,0,1,0,'Activo',0,0,0,56,'lnxni0230',0),
	 (453,0,'RPT_MTH_COUNT_TRANSACTIONS.sh','Conteo mensual transacciones fallidas,no validas, exitosas  MTH - AppSupport (GDRC-45752)','${PATH_DIRECTOR_SH}','${PATH_DIRECTOR_ENTRADA}','RPT_MTH_ConteoTransacciones_','To_Char(Add_Months(Sysdate, -1),''YYYYMM'')',NULL,0,1,0,'Activo',0,0,0,59,'LNXNI0230',0),
	 (452,0,'RPT_MTH_FAILED_TRANSACTIONS.sh','Reporte mensual transacciones fallidas MTH - AppSupport','${PATH_DIRECTOR_SH}','${PATH_DIRECTOR_ENTRADA}','RPT_MTH_TransaccionesFallidas_','to_char(add_months(sysdate, -1),''YYYYMM'')',NULL,0,1,0,'Activo',0,0,0,42,'LNXNI0230',0),
	 (451,0,'SOX_11_2_start.sh','Proceso de conciliacion ROAMING VS TRAFICO','/home/appextractor/Director/Sh/EXTRACTORES_SOX/SOX_11_2',NULL,NULL,NULL,NULL,0,1,0,'Inactivo',0,0,0,36,'sunni005',0),
	 (450,0,'ELT_SiteInfoMerge.sh','ETL from 01ni0148 to Venus, MergeSiteInfo GDRC-44812','/sharenfs02/procs/etls/Digital_SiteInfoMerge/scripts',NULL,NULL,NULL,NULL,0,2,3600,'Internal',0,0,0,28,'lnxni0230',0),
	 (449,0,'ETL_Digital_PaymGtwy_S3.sh','ETL Digital_PaymGtwy from S3 to SMB(01ni040a) GDRC-44899','/sharenfs02/procs/etls/Digital_PaymGtwy/scripts',NULL,NULL,NULL,NULL,0,2,3600,'Activo',0,0,0,34,'lnxni0230',0),
	 (448,0,'rpt_fact_nociclo_rao_month.sh','Proceso RAO de facturacion no ciclos MES','${PATH_DIRECTOR_SH}',NULL,NULL,NULL,NULL,0,1,0,'Activo',0,0,0,36,'lnxni0230',0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS (IDPROC,IDCONEX,NOMBRE,DESCRIPCION,"PATH",PARAMETRO1,PARAMETRO2,PARAMETRO3,PARAMETRO4,DEPENDENCIA,INTENTOS,ESPERA_INTENTO,ESTADO,FTP,IDHOST,COMPRESION,IDCRONTAB,NODE,IDNOTIF) VALUES
	 (447,0,'rpt_fact_ciclo_rao_month.sh','Proceso RAO de los ciclos de facturacion MES','${PATH_DIRECTOR_SH}',NULL,NULL,NULL,NULL,0,1,0,'Activo',1,0,0,36,'lnxni0230',0),
	 (446,0,'rpt_fact_ciclo_rao.sh','Proceso RAO DE los ciclos de facturacion','${PATH_DIRECTOR_SH}',NULL,NULL,NULL,NULL,0,1,0,'Activo',0,0,0,36,'lnxni0230',0),
	 (445,0,'base_bancarizada_start.sh','Proceso Base Bancarizada','/export/home/appextractor/Director/Sh/PROC_BASE_BANCARIZADA',NULL,NULL,NULL,NULL,0,5,60,'Activo',0,0,0,36,'sunni005',0),
	 (444,0,'Test.sh','Conexión','${PATH_DIRECTOR_SH}','to_char(sysdate-1,''yyyymmdd'')','to_char(sysdate-1,''mmyyyy'')',NULL,NULL,0,5,60,'Internal',0,0,0,40,'lnxni0230',0),
	 (443,0,'SOX_2_2_CONCILIADOR.sh','Proceso que genera los csv conciliados.','/home/appextractor/Director/Sh/EXTRACTORES_SOX/SOX_2_2',NULL,NULL,NULL,NULL,1,5,60,'Activo',0,0,0,36,'sunni005',0),
	 (442,0,'SOX_2_2_CARGA_SCL_CBS.sh','Proceso que extrae abonados de SCL y CBS y sus planes','/home/appextractor/Director/Sh/EXTRACTORES_SOX/SOX_2_2',NULL,NULL,NULL,NULL,1,5,60,'Activo',0,0,0,32,'sunni005',0),
	 (441,0,'SOX_2_2_CARGA_HSS.sh','Proceso que extrae archivo DUMP de RAO y lo carga en VENUS','/home/appextractor/Director/Sh/EXTRACTORES_SOX/SOX_2_2',NULL,NULL,NULL,NULL,0,5,60,'Activo',0,0,0,17,'sunni005',0),
	 (439,6,'GSM_DET_SIMCARD_TO_SPOOL.sql','Extracción tabla GSM_DET_SIMCARD_TO','/home/appextractor/Director/Sql',NULL,NULL,NULL,NULL,0,600,60,'Inactivo',0,7,0,26,'sunni005',0),
	 (438,17,'EXPORT_ACTIVACIONES.sql','Exportacion Reporte Activaciones','${PATH_DIRECTOR_SQL}','to_char(sysdate-3,''yyyymm'')','${PATH_DIRECTOR_ENTRADA}/ACTIVACIONES_',NULL,NULL,0,3,3600,'Activo',1,7,0,31,'lnxni0230',0),
	 (437,0,'ALARMA_SOX.sh','ALARMA CONTROL SOX 12.1 Y 15.1','/home/appextractor/Director/Sh/EXTRACTORES_SOX/ALARMA_SOX',NULL,NULL,NULL,NULL,1,5,60,'Activo',0,0,0,32,'sunni005',0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS (IDPROC,IDCONEX,NOMBRE,DESCRIPCION,"PATH",PARAMETRO1,PARAMETRO2,PARAMETRO3,PARAMETRO4,DEPENDENCIA,INTENTOS,ESPERA_INTENTO,ESTADO,FTP,IDHOST,COMPRESION,IDCRONTAB,NODE,IDNOTIF) VALUES
	 (436,0,'EXECUTE_SOX_15_1.sh','CONTROL SOX 15.1','/home/appextractor/Director/Sh/EXTRACTORES_SOX/SOX_15_1',NULL,NULL,NULL,NULL,0,5,60,'Inactivo',0,0,0,32,'sunni005',0),
	 (435,0,'EXECUTE_SOX_11_1.sh','Reporte SOX 11.1 GDRC-39917','/export/home/appextractor/Director/Sh/EXTRACTORES_SOX/SOX_11_1',NULL,NULL,NULL,NULL,0,10,60,'Activo',0,0,0,31,'sunni005',0),
	 (434,0,'EXECUTE_SOX_12_1.SH','CONTROL SOX 12.1','/home/appextractor/Director/Sh/EXTRACTORES_SOX/SOX_12_1',NULL,NULL,NULL,NULL,0,5,60,'Activo',0,0,0,32,'sunni005',0),
	 (433,6,'activaciones_completacioncam.sql','Reporte Activaciones Completacion de Campos. GDRC-40353','${PATH_DIRECTOR_SQL}','to_char(sysdate-3,''yyyymm'')','${PATH_DIRECTOR_ENTRADA}/ACTIVACIONESCAMPOS_',NULL,NULL,1,1,0,'Activo',1,7,0,26,'lnxni0230',0),
	 (432,3,'TRAFROAM_ENCUESTASNPS.sql','Extractor Full TRAFROAM_ENCUESTASNPS. GDRC-37999 ','${PATH_DIRECTOR_SQL}',NULL,NULL,NULL,NULL,1,1,300,'Activo',0,0,0,33,'lnxni0230',0),
	 (431,3,'DWD_CATEGORIA_CLIENTE.sql','Extractor Full DWD_CATEGORIA_CLIENTE solicita JosueV. GDRC-38004','${PATH_DIRECTOR_SQL}',NULL,NULL,NULL,NULL,1,1,300,'Activo',0,0,0,28,'lnxni0230',0),
	 (430,3,'script_reciclados.sh','Proceso para armas bases lineas a reciclar en CBS','/oradata1/aplicaciones/VENUS/PRO_RECICLADOS_CBS',NULL,NULL,NULL,NULL,1,12,60,'Inactivo',0,0,0,24,'sunni005',0),
	 (429,3,'PRC_SEGMENTO_SAP_DWH_COPY.sql','Proceso migrado ControlM TCN_SEGMENTACION/segmentacion.sh ahora para uso DWH','${PATH_DIRECTOR_SQL}',NULL,NULL,NULL,NULL,1,1,0,'Activo',0,0,0,26,'lnxni0230',0),
	 (428,6,'PRC_SEGMENTO_SAP_DWH_TRUNCATE.sql','Proceso migrado ControlM TCN_SEGMENTACION/segmentacion.sh ahora para uso DWH','${PATH_DIRECTOR_SQL}',NULL,NULL,NULL,NULL,1,1,0,'Activo',0,0,0,26,'lnxni0230',0),
	 (427,3,'PRC_SEGMENTO_SAP_DWH.sql','Proceso migrado ControlM TCN_SEGMENTACION/segmentacion.sh ahora para uso DWH','${PATH_DIRECTOR_SQL}',NULL,NULL,NULL,NULL,1,2,5400,'Activo',0,0,0,26,'lnxni0230',0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS (IDPROC,IDCONEX,NOMBRE,DESCRIPCION,"PATH",PARAMETRO1,PARAMETRO2,PARAMETRO3,PARAMETRO4,DEPENDENCIA,INTENTOS,ESPERA_INTENTO,ESTADO,FTP,IDHOST,COMPRESION,IDCRONTAB,NODE,IDNOTIF) VALUES
	 (426,3,'PRC_RISK_CHURN.sql','Procedimiento Utilizado para riesgo de churn- APP_DGTL_MAN_CHURN','${PATH_DIRECTOR_SQL}',NULL,NULL,NULL,NULL,0,1,0,'Activo',0,0,0,14,'lnxni0230',0),
	 (425,0,'PRUEBA_VEN_PROD.sh','Shell de Prueba en Venus Produccion','/home/appextractor/Director/Sh',NULL,NULL,NULL,NULL,0,10,60,'Activo',0,0,0,11,'sunni005',0),
	 (424,5,'RPT_TRASPASOS_MENSUAL.sql','Reporte de Traspasos Mensual SCL','/home/appextractor/Director/Sql','/home/appextractor/Director/Entrada/REPORTE_DE_TRASPASOS_MENSUAL_','TO_CHAR(sysdate,''yyyymmdd'')',NULL,NULL,1,10,60,'Activo',1,7,0,11,'sunni005',0),
	 (423,0,'REP_TCN_TIPO_CAMBIO_PREP_AA.sh','Crea replica de TCN_TIPO_CAMBIO_PREP en RLPPGAN y RLPPCSN','/home/appextractor/Director/Sh',NULL,NULL,NULL,NULL,1,1,60,'Inactivo',0,0,0,11,'sunni005',0),
	 (422,0,'sftp_brightstar.sh','Copia reportes de log a server sftp brightstar','/home/appextractor/Director/Sh','/users/TigoNicaragua/Inventario','TO_CHAR(sysdate-1,''yyyymmdd'')','/users/TigoNicaragua/Movimientos','TO_CHAR(sysdate-1,''yyyymm'')',1,20,10,'Activo',0,0,0,11,'sunni005',0),
	 (420,18,'TCN_RPT_PERMISO_ROL_MS.sql','Reporte de Permisos por Rol Modulo de seguridad','${PATH_DIRECTOR_SQL}','${PATH_DIRECTOR_ENTRADA}/REPORTE_PERMISOS_ROL_','TO_CHAR(sysdate,''YYYYMM'')',NULL,NULL,0,1,0,'Activo',1,7,1,11,'lnxni0230',0),
	 (419,5,'RPT_TRASPASOS.sql','Reporte de Traspasos SCL','/home/appextractor/Director/Sql','/home/appextractor/Director/Entrada/REPORTE_DE_TRASPASOS_DIARIOS_','TO_CHAR(sysdate,''yyyymmdd'')',NULL,NULL,1,10,60,'Activo',1,7,0,11,'sunni005',0),
	 (418,3,'RPT_SALIDAS_SIMCARD.sh','Reporte Salida Definitiva de Simcard','${PATH_DIRECTOR_SH}','${PATH_DIRECTOR_ENTRADA}/RPT_SALIDAS_SIMCARD_','to_char(sysdate-1,''yyyymm'')',NULL,NULL,1,1,0,'Activo',1,7,1,11,'lnxni0230',0),
	 (417,3,'PRC_SALIDAS_SIMCARD.sql','Proceso Salida Definitiva de Simcard','${PATH_DIRECTOR_SQL}','to_char(sysdate-1,''yyyymm'')',NULL,NULL,NULL,1,1,0,'Activo',0,0,0,11,'lnxni0230',0),
	 (416,6,'AL_VENTAS','Extractor SCL','Extractor Full',NULL,NULL,NULL,NULL,1,1,300,'Activo',0,0,0,26,'lnxni0230',0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS (IDPROC,IDCONEX,NOMBRE,DESCRIPCION,"PATH",PARAMETRO1,PARAMETRO2,PARAMETRO3,PARAMETRO4,DEPENDENCIA,INTENTOS,ESPERA_INTENTO,ESTADO,FTP,IDHOST,COMPRESION,IDCRONTAB,NODE,IDNOTIF) VALUES
	 (415,5,'RPT_SUSPENSIONES_DIA.sql','Reporte de Suspensiones diarias por cobro','/home/appextractor/Director/Sql','/home/appextractor/Director/Entrada/20_REPORTE_DE_SUSPENSIONES_DIARIAS_','TO_CHAR(sysdate,''yyyymmdd'')',NULL,NULL,0,10,60,'Inactivo',1,7,0,15,'sunni005',0),
	 (412,3,'dwd_celda.sql','Proceso de Celdas DWH por DBLINK','${PATH_DIRECTOR_SQL}',NULL,NULL,NULL,NULL,1,1,0,'Activo',0,0,0,11,'lnxni0230',0),
	 (411,0,'Abonado_Nicaragua_prueba.sh','spool abonado','/home/appextractor/Director/Sh',NULL,NULL,NULL,NULL,0,5,60,'Inactivo',0,0,0,11,'sunni005',0),
	 (410,17,'APP_VALIDADWH_NIC.DWD_PQ_FACT_PARA_VENUS','Catalogo Parque para FACT NPW','Extractor Full',NULL,NULL,NULL,NULL,1,1,0,'Activo',0,0,0,11,'lnxni0230',0),
	 (409,3,'DWD_PQ_FACT_PARA_VENUS.sql','Interfaz','${PATH_DIRECTOR_SQL}','TO_CHAR(sysdate-2,''yyyymmdd'')',NULL,NULL,NULL,1,1,0,'Activo',0,0,0,11,'lnxni0230',0),
	 (408,0,'ConexionDWHCAM.sh','Conexión','${PATH_DIRECTOR_SH}','TO_CHAR(sysdate-2,''yyyymmdd'')',NULL,NULL,NULL,0,1,0,'Activo',0,0,0,11,'lnxni0230',0),
	 (407,17,'BDDWH.DWD_DIA','Dimension de tiempo del SIEM por dia.','Extractor Full',NULL,NULL,NULL,NULL,1,1,0,'Activo',0,0,0,11,'lnxni0230',0),
	 (406,17,'APP_VALIDADWH_NIC.DWD_EQUIPOS_GSMA','Catalogo GSMA de equipos por TAC','Extractor Full',NULL,NULL,NULL,NULL,1,1,0,'Activo',0,0,0,11,'lnxni0230',0),
	 (405,15,'PAY_SALDO_INICIAL_RECARGA.sql','Proceso obtiene el saldo inicial de recarga por punto de venta en Payment','${PATH_DIRECTOR_SQL}',NULL,NULL,NULL,NULL,1,1,0,'Activo',0,0,0,11,'lnxni0230',0),
	 (404,15,'PAY_SALDO_RETIRADO_RECARGA.sql','Proceso obtiene el saldo retirado de recarga por punto de venta en Payment','${PATH_DIRECTOR_SQL}',NULL,NULL,NULL,NULL,1,1,0,'Activo',0,0,0,11,'lnxni0230',0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS (IDPROC,IDCONEX,NOMBRE,DESCRIPCION,"PATH",PARAMETRO1,PARAMETRO2,PARAMETRO3,PARAMETRO4,DEPENDENCIA,INTENTOS,ESPERA_INTENTO,ESTADO,FTP,IDHOST,COMPRESION,IDCRONTAB,NODE,IDNOTIF) VALUES
	 (403,15,'PAY_SALDO_ASIGNADO.sql','Proceso obtiene el saldo asignado al punto de venta en Payment','${PATH_DIRECTOR_SQL}',NULL,NULL,NULL,NULL,1,1,0,'Activo',0,0,0,11,'lnxni0230',0),
	 (402,15,'PAY_SALDO_TRASPASADO.sql','Proceso obtiene el saldo traspasado por punto de venta en Payment','${PATH_DIRECTOR_SQL}',NULL,NULL,NULL,NULL,1,1,0,'Activo',0,0,0,11,'lnxni0230',0),
	 (401,15,'PAY_ULTIMO_TRASPASO.sql','Proceso encargado de crear el ultimo traspaso de Payment por punto de venta','${PATH_DIRECTOR_SQL}',NULL,NULL,NULL,NULL,1,1,0,'Activo',0,0,0,28,'lnxni0230',0),
	 (400,15,'PAY_ULTIMA_RECARGA.sql','Proceso encargado de crear la ultima recarga de Payment por punto de venta','${PATH_DIRECTOR_SQL}',NULL,NULL,NULL,NULL,1,1,0,'Activo',0,0,0,28,'lnxni0230',0),
	 (399,6,'RPT_GARANTIAS_EN_CUENTA_CORRIENTE.sql','Reporte de Cobranza GARANTIAS_EN_CUENTA_CORRIENTE','${PATH_DIRECTOR_SQL}','${PATH_DIRECTOR_ENTRADA}/17_GARANTIAS_EN_CUENTA_CORRIENTE_','TO_CHAR(sysdate,''yyyymmdd'')',NULL,NULL,0,1,0,'Activo',1,7,1,38,'lnxni0230',0),
	 (398,6,'RPT_CARTA_DE_PAGOS.sql','Reporte de Cobranza CARTA_DE_PAGOS','${PATH_DIRECTOR_SQL}','${PATH_DIRECTOR_ENTRADA}/16_CARTA_DE_PAGOS_','TO_CHAR(sysdate,''yyyymmdd'')',NULL,NULL,0,1,0,'Activo',1,7,1,38,'lnxni0230',0),
	 (397,6,'RPT_GARANTIAS_ACTIVADAS.sql','Reporte de Cobranza GARANTIAS_ACTIVADAS','${PATH_DIRECTOR_SQL}','${PATH_DIRECTOR_ENTRADA}/15_GARANTIAS_ACTIVADAS_','TO_CHAR(sysdate,''yyyymmdd'')',NULL,NULL,0,1,0,'Activo',1,7,1,38,'lnxni0230',0),
	 (396,6,'RPT_FACTURA_CICLO.sql','Reporte de Cobranza FACTURA_CICLO','/home/appextractor/Director/Sql','/home/appextractor/Director/Entrada/14_FACTURA_CICLO_','TO_CHAR(sysdate,''yyyymmdd'')',NULL,NULL,0,10,60,'Inactivo',1,7,0,38,'sunni005',0),
	 (395,6,'RPT_RESPALDO_DE_INGRESOS.sql','Reporte de Cobranza RESPALDO_DE_INGRESOS','${PATH_DIRECTOR_SQL}','${PATH_DIRECTOR_ENTRADA}/13_RESPALDO_DE_INGRESOS_','TO_CHAR(sysdate,''yyyymmdd'')',NULL,NULL,0,1,0,'Activo',1,7,1,38,'lnxni0230',0),
	 (394,6,'RPT_PAGOS_MENSUALES.sql','Reporte de Cobranza PAGOS_MENSUALES','${PATH_DIRECTOR_SQL}','${PATH_DIRECTOR_ENTRADA}/12_PAGOS_MENSUALES_','TO_CHAR(sysdate,''yyyymmdd'')',NULL,NULL,0,1,0,'Activo',1,7,1,38,'lnxni0230',0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS (IDPROC,IDCONEX,NOMBRE,DESCRIPCION,"PATH",PARAMETRO1,PARAMETRO2,PARAMETRO3,PARAMETRO4,DEPENDENCIA,INTENTOS,ESPERA_INTENTO,ESTADO,FTP,IDHOST,COMPRESION,IDCRONTAB,NODE,IDNOTIF) VALUES
	 (393,6,'RPT_FACTURAS_DE_CONTADO.sql','Reporte de Cobranza FACTURAS_DE_CONTADO','${PATH_DIRECTOR_SQL}','${PATH_DIRECTOR_ENTRADA}/11_FACTURAS_DE_CONTADO_','TO_CHAR(sysdate,''yyyymmdd'')',NULL,NULL,0,1,0,'Activo',1,7,1,38,'lnxni0230',0),
	 (392,6,'RPT_NOTAS_CREDITO_DEBITO_INTERNA.sql','Reporte de Cobranza NOTAS_CREDITO_DEBITO_INTERNA','${PATH_DIRECTOR_SQL}','${PATH_DIRECTOR_ENTRADA}/10_NOTAS_CREDITO_DEBITO_INTERNA_','TO_CHAR(sysdate,''yyyymmdd'')',NULL,NULL,0,1,0,'Activo',1,7,1,38,'lnxni0230',0),
	 (391,6,'RPT_NOTAS_DE_CREDITO_Y_DEBITO.sql','Reporte de Cobranza NOTAS_DE_CREDITO_Y_DEBITO','${PATH_DIRECTOR_SQL}','${PATH_DIRECTOR_ENTRADA}/09_NOTAS_DE_CREDITO_Y_DEBITO_FACT_','TO_CHAR(sysdate,''yyyymmdd'')',NULL,NULL,0,1,0,'Activo',1,7,1,38,'lnxni0230',0),
	 (390,6,'RPT_REPORTE_DE_PRORROGAS.sql','Reporte de Cobranza REPORTE_DE_PRORROGAS','${PATH_DIRECTOR_SQL}','${PATH_DIRECTOR_ENTRADA}/06_REPORTE_DE_PRORROGAS_','TO_CHAR(sysdate,''yyyymmdd'')',NULL,NULL,0,1,0,'Activo',1,7,1,38,'lnxni0230',0),
	 (389,6,'RPT_REPORTE_DE_CLIENTES_SALTA.sql','Reporte de Cobranza REPORTE_DE_CLIENTES_SALTA','${PATH_DIRECTOR_SQL}','${PATH_DIRECTOR_ENTRADA}/05_REPORTE_DE_CLIENTES_SALTA_','TO_CHAR(sysdate,''yyyymmdd'')',NULL,NULL,0,1,0,'Activo',1,7,1,38,'lnxni0230',0),
	 (388,6,'RPT_RESUMEN_CARTERA_INACTIVA.sql','Reporte de Cobranza RESUMEN_CARTERA_INACTIVA','${PATH_DIRECTOR_SQL}','${PATH_DIRECTOR_ENTRADA}/04_RESUMEN_CARTERA_INACTIVA_','TO_CHAR(sysdate,''yyyymmdd'')',NULL,NULL,0,1,0,'Activo',1,7,1,38,'lnxni0230',0),
	 (387,6,'RPT_DETALLE_CARTERA_INACTIVA.sql','Reporte de Cobranza DETALLE_CARTERA_INACTIVA','${PATH_DIRECTOR_SQL}','${PATH_DIRECTOR_ENTRADA}/03_DETALLE_CARTERA_INACTIVA_','TO_CHAR(sysdate,''yyyymmdd'')',NULL,NULL,0,1,0,'Activo',1,7,1,38,'lnxni0230',0),
	 (386,6,'RPT_REPORTE_DE_FINANCIAMIENTO.sql','Reporte de Cobranza REPORTE_DE_FINANCIAMIENTO','${PATH_DIRECTOR_SQL}','${PATH_DIRECTOR_ENTRADA}/18_REPORTE_DE_FINANCIAMIENTO_','TO_CHAR(sysdate,''yyyymmdd'')',NULL,NULL,0,1,0,'Activo',1,7,1,38,'lnxni0230',0),
	 (385,6,'RPT_REPORTE_DE_CO_CARTERA.sql','Reporte de Cobranza REPORTE_DE_CO_CARTERA','${PATH_DIRECTOR_SQL}','${PATH_DIRECTOR_ENTRADA}/07_REPORTE_DE_CO_CARTERA_','TO_CHAR(sysdate,''yyyymmdd'')',NULL,NULL,0,1,0,'Activo',1,7,1,38,'lnxni0230',0),
	 (384,6,'RPT_DETALLE_CARTERA_ACTIVA.sql','Reporte de Cobranza DETALLE_CARTERA_ACTIVA','${PATH_DIRECTOR_SQL}','${PATH_DIRECTOR_ENTRADA}/01_DETALLE_CARTERA_ACTIVA_','TO_CHAR(sysdate,''yyyymmdd'')',NULL,NULL,0,1,0,'Activo',1,7,1,38,'lnxni0230',0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS (IDPROC,IDCONEX,NOMBRE,DESCRIPCION,"PATH",PARAMETRO1,PARAMETRO2,PARAMETRO3,PARAMETRO4,DEPENDENCIA,INTENTOS,ESPERA_INTENTO,ESTADO,FTP,IDHOST,COMPRESION,IDCRONTAB,NODE,IDNOTIF) VALUES
	 (383,6,'RPT_Resumen_Cartera_Activa.sql','Reporte de Cobranza Resumen_Cartera_Activa','${PATH_DIRECTOR_SQL}','${PATH_DIRECTOR_ENTRADA}/02_RESUMEN_CARTERA_ACTIVA_','TO_CHAR(sysdate,''yyyymmdd'')',NULL,NULL,0,1,0,'Activo',1,7,1,38,'lnxni0230',0),
	 (382,6,'RPT_REPORTE_DE_PAGOS_DIARIOS.sql','Reporte de Cobranza REPORTE_DE_PAGOS_DIARIOS','/home/appextractor/Director/Sql','/home/appextractor/Director/Entrada/08_REPORTE_DE_PAGOS_DIARIOS_','TO_CHAR(sysdate,''yyyymmdd'')',NULL,NULL,0,10,60,'Inactivo',1,7,0,38,'sunni005',0),
	 (381,0,'MataProcesos.sh','Proceso encargado de dar kill a procesos en Unix','/home/appextractor/Director/Sh',NULL,NULL,NULL,NULL,0,5,60,'Inactivo',0,0,0,11,'sunni005',0),
	 (380,15,'RPT_IMAGEN_SALDO_PAYMENT.sql','Reporte de imagen de saldos Payment','${PATH_DIRECTOR_SQL}','${PATH_DIRECTOR_ENTRADA}/IMAGEN_SALDO_PAYMENT_','TO_CHAR(sysdate-1,''yyyymmdd'')',NULL,NULL,0,1,0,'Activo',1,7,1,28,'lnxni0230',0),
	 (379,15,'RPT_TRANSACCIONES_PAYMENT.sql','Reporte de transacciones de Payment','${PATH_DIRECTOR_SQL}','${PATH_DIRECTOR_ENTRADA}/TRANSACCIONES_','TO_CHAR(sysdate-1,''yyyymmdd'')',NULL,NULL,0,1,0,'Activo',1,7,1,28,'lnxni0230',0),
	 (378,0,'ConexionPMNIPayment.sh','Conexión','${PATH_DIRECTOR_SH}','to_char(sysdate-1,''yyyymmdd'')',NULL,NULL,NULL,0,1,0,'Activo',0,0,0,26,'lnxni0230',0),
	 (377,15,'RPT_ACTIVIDAD_PTOS_VENTA.sql','Reporte saldos de puntos de venta de distribuidores de Payment','${PATH_DIRECTOR_SQL}','${PATH_DIRECTOR_ENTRADA}/ACTIVIDAD_PTOS_VENTA_','TO_CHAR(sysdate-1,''yyyymmdd'')',NULL,NULL,0,1,0,'Activo',1,7,1,28,'lnxni0230',0),
	 (376,0,'DEPURA_BAJAS_CHIPITOS_VENUS.sh','Realiza bajas de chipitos por cambio de linea de negocio','/home/appextractor/Director/Sh',NULL,NULL,NULL,NULL,1,600,60,'Inactivo',0,0,0,11,'sunni005',0),
	 (375,0,'ACTUALIZA_CHIPITOS_RECARGAS_VENUS.sh','Actualiza las recargas para lineas en chipitos','/home/appextractor/Director/Sh',NULL,NULL,NULL,NULL,1,600,60,'Inactivo',0,0,0,11,'sunni005',0),
	 (374,3,'facturas_pendientes_proc','Alarma Facturas Pendientes SCL','/home/appextractor/Director/Sql',NULL,NULL,NULL,NULL,0,600,60,'Inactivo',0,0,0,27,'sunni005',0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS (IDPROC,IDCONEX,NOMBRE,DESCRIPCION,"PATH",PARAMETRO1,PARAMETRO2,PARAMETRO3,PARAMETRO4,DEPENDENCIA,INTENTOS,ESPERA_INTENTO,ESTADO,FTP,IDHOST,COMPRESION,IDCRONTAB,NODE,IDNOTIF) VALUES
	 (373,13,'TCN_CDR_GSM_NICMS_CRONOS2.sql','EXTRACTOR2 TRAFICO DE APOLO CDR','/home/appextractor/Director/Sql','TO_CHAR(sysdate-3,''yyyymmdd'')',NULL,NULL,NULL,0,600,60,'Inactivo',0,0,0,11,'sunni005',0),
	 (372,0,'RPT_FACT_RETAILERS.sh','Reporte de Facturas Retailers Payment (Ilse, Dina)','${PATH_DIRECTOR_SH}','${PATH_DIRECTOR_ENTRADA}/RPT_FACT_RETAILERS_PAYM_','TO_CHAR(sysdate-2,''yyyymm'')','TO_CHAR(sysdate-2,''yyyymm'')',NULL,1,1,0,'Activo',1,7,1,11,'lnxni0230',0),
	 (371,3,'RPT_ADS_VENUS.sql','Reporte ADS Conoceme, DWH - Mercadeo','/home/appextractor/Director/Sql','/home/appextractor/Director/Entrada/BASE_ADS_','TO_CHAR(sysdate-1,''yyyymm'')',NULL,NULL,1,10,60,'Inactivo',1,7,1,11,'sunni005',0),
	 (370,3,'PRC_ADS_VENUS.sql','Proceso ADS Conoceme, DWH - Mercadeo','/home/appextractor/Director/Sql',NULL,NULL,NULL,NULL,1,5,60,'Inactivo',0,0,0,11,'sunni005',0),
	 (369,0,'RPT_TARJETA_MOVISTAR_CREDOMATIC.sh','Reportes de tarjeta movistar credomatic','/oradata2/oracle/aplicaciones/Director/Sh','/oradata2/oracle/aplicaciones/Director/Entrada/','/RepDWH/Reportes_Tarjeta_Movistar_Credomatic','TO_CHAR(SYSDATE-1,''yyyymm'')','TO_CHAR(SYSDATE-1,''yyyymm'')',1,10,60,'Activo',0,0,0,11,'sunni005',0),
	 (367,0,'ALTAS_PREPAGO_SH.sh','Reporte de altas prepago SCL -- Activaciones','/home/appextractor/Director/Sh','/home/appextractor/Director/Entrada/ACTIVACION_PREPAGO_','TO_CHAR(sysdate-1,''yyyymm'')','TO_CHAR(sysdate-1,''yyyymm'')',NULL,1,10,60,'Inactivo',1,7,1,11,'sunni005',0),
	 (364,3,'RPT_SMS_MOVIL.sql','Reportes de Consulta por Móvil - Crédito','/home/appextractor/Director/Sql','/home/appextractor/Director/Entrada/','RPT_SMS_MOVIL_','TO_CHAR(sysdate-1,''yyyymm'')',NULL,0,10,60,'Inactivo',1,7,1,11,'sunni005',0),
	 (363,3,'RPT_SMS_IDENTIFICACION.sql','Reportes de Consulta por Identificación - Crédito','${PATH_DIRECTOR_SQL}','${PATH_DIRECTOR_ENTRADA}/','RPT_SMS_IDENTIFICACION_','TO_CHAR(sysdate-1,''yyyymm'')',NULL,0,1,0,'Activo',1,7,1,11,'lnxni0230',0),
	 (362,13,'TCN_CDR_GSM_NICMS_CRONOS.sh','EXTRACTOR TRAFICO DE APOLO CDR','${PATH_DIRECTOR_SH}','TO_CHAR(sysdate-1,''YYYYMMDD'')',NULL,NULL,NULL,0,1,0,'Activo',0,0,0,11,'lnxni0230',0),
	 (361,3,'RPT_ASIGNACION_CARTERA.sql','Reporte Asignaci¿n de cartera morosa - Cobranzas','${PATH_DIRECTOR_SQL}','${PATH_DIRECTOR_ENTRADA}/RPT_ASIGNACION_CARTERA_','TO_CHAR(sysdate-1,''yyyymm'')',NULL,NULL,1,1,0,'Activo',1,7,1,11,'lnxni0230',0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS (IDPROC,IDCONEX,NOMBRE,DESCRIPCION,"PATH",PARAMETRO1,PARAMETRO2,PARAMETRO3,PARAMETRO4,DEPENDENCIA,INTENTOS,ESPERA_INTENTO,ESTADO,FTP,IDHOST,COMPRESION,IDCRONTAB,NODE,IDNOTIF) VALUES
	 (360,3,'PRC_ASIGCARTERA_CORREO_VENUS.sql','Proceso de Asignaci¿n de Cartera Correo - Cobranzas','${PATH_DIRECTOR_SQL}',NULL,NULL,NULL,NULL,1,1,0,'Activo',0,0,0,11,'lnxni0230',0),
	 (359,6,'PRC_ASIGNACION_CARTERA_INACTIVA.sql','Proceso de Asignaci¿n de Cartera Morosa Inactiva - Cobranzas','${PATH_DIRECTOR_SQL}',NULL,NULL,NULL,NULL,1,1,0,'Activo',0,0,0,26,'lnxni0230',0),
	 (358,6,'PRC_ASIGNACION_CARTERA_ACTIVA.sql','Proceso de Asignaci¿n de Cartera Morosa activa - Cobranzas','${PATH_DIRECTOR_SQL}',NULL,NULL,NULL,NULL,1,1,0,'Activo',0,0,0,26,'lnxni0230',0),
	 (352,0,'CONCILIA_SISTEMA.sh','Proceso Shell de Conciliación de Sistemas SCL y Altamira - Área de Ingresos','/home/appextractor/Director/Sh',NULL,NULL,NULL,NULL,1,5,60,'Inactivo',0,0,0,24,'sunni005',0),
	 (347,6,'RPT_CONCILIA_SCL.sql','Reporte Concilia SCL','/home/appextractor/Director/Sql','/home/appextractor/Director/Entrada/RPT_CONCILIA_SCL_','to_char(sysdate-1,''yyyymmdd'')',NULL,NULL,1,10,60,'Inactivo',1,7,1,26,'sunni005',0),
	 (346,1,'RPT_CONCILIA_ALTAMIRA.sql','Reporte Concilia Altamira','/home/appextractor/Director/Sql','/home/appextractor/Director/Entrada/RPT_CONCILIA_ALTAMIRA_','to_char(sysdate-1,''yyyymmdd'')',NULL,NULL,1,10,60,'Inactivo',1,7,1,11,'sunni005',0),
	 (345,3,'VJ_PRC_GAC_BUZON_GESTION.sql','Proceso','${PATH_DIRECTOR_SQL}','to_char(sysdate-1, ''yyyymm'')||''01''','to_char(sysdate-1,''yyyymmdd'')',NULL,NULL,1,1,0,'Activo',0,0,0,11,'lnxni0230',0),
	 (344,3,'VJ_PRC_GAC_CALLBACK.sql','Proceso','/home/appextractor/Director/Sql','to_char(sysdate - 1, ''yyyymm'')||''01''','to_char(sysdate-1,''yyyymmdd'')',NULL,NULL,1,5,60,'Inactivo',0,0,0,11,'sunni005',0),
	 (342,3,'RPT_GAC_CASOSCERRADOS.sql','Reporte casos cerrados - Clientes','/home/appextractor/Director/Sql','/home/appextractor/Director/Entrada/','CasosCerradosGAC_','to_char(sysdate-1,''yyyymm'')',NULL,1,10,60,'Inactivo',1,7,1,11,'sunni005',0),
	 (341,3,'PRC_GAC_CASOSCERRADOS.sql','Proceso casos cerrados - Clientes','/home/appextractor/Director/Sql',NULL,NULL,NULL,NULL,0,5,60,'Inactivo',0,0,0,11,'sunni005',0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS (IDPROC,IDCONEX,NOMBRE,DESCRIPCION,"PATH",PARAMETRO1,PARAMETRO2,PARAMETRO3,PARAMETRO4,DEPENDENCIA,INTENTOS,ESPERA_INTENTO,ESTADO,FTP,IDHOST,COMPRESION,IDCRONTAB,NODE,IDNOTIF) VALUES
	 (340,3,'APP_VALIDADWH_NIC.TMP_TOP10PREPAGO.sql','Extractor DWH','/home/appextractor/Director/Sql',NULL,NULL,NULL,NULL,1,600,60,'Inactivo',0,0,0,11,'sunni005',0),
	 (339,3,'RPT_IVR_SERIES_EQUIPOS.sql','Reporte Series Equipos IVR Altas Postpago','${PATH_DIRECTOR_SQL}','${PATH_DIRECTOR_ENTRADA}/RPT_IVR_series_equipos_','TO_CHAR(sysdate-1,''yyyymm'')',NULL,NULL,0,1,0,'Activo',1,7,1,11,'lnxni0230',0),
	 (338,3,'RPT_IVR_STATUS_BURO.sql','Reporte Status Buró IVR Altas Postpago','/home/appextractor/Director/Sql','/home/appextractor/Director/Entrada/RPT_IVR_status_buro_','TO_CHAR(sysdate-1,''yyyymm'')',NULL,NULL,0,10,60,'Inactivo',1,7,1,11,'sunni005',0),
	 (337,3,'RPT_IVR_STATUS_CONSULTAS.sql','Reporte de Status Consultas IVR Altas Postpago','/home/appextractor/Director/Sql','/home/appextractor/Director/Entrada/RPT_IVR_status_consultas_','TO_CHAR(sysdate-1,''yyyymm'')',NULL,NULL,0,10,60,'Inactivo',1,7,1,11,'sunni005',0),
	 (336,3,'RPT_IVR_TIPO_CONSULTAS.sql','Reporte Tipos de Consulta IVR Altas Postpago','${PATH_DIRECTOR_SQL}','${PATH_DIRECTOR_ENTRADA}/RPT_IVR_tipo_consultas_','TO_CHAR(sysdate-1,''yyyymm'')',NULL,NULL,0,1,0,'Activo',1,7,1,11,'lnxni0230',0),
	 (335,0,'UNIDADESF_MOVGEO.sh','Proceso Shell Unidades Fijas Movilidad Geográfica','/home/appextractor/Director/Sh','/home/appextractor/Director/Entrada/','traf_fijo_celdas_','TO_CHAR(sysdate-1,''yyyymmdd'')','/RepDWH',1,5,60,'Inactivo',0,0,0,11,'sunni005',0),
	 (333,0,'PRC_PAYMENT_DIST_ALL.sh','Proceso de Payment','${PATH_DIRECTOR_SH}',NULL,NULL,NULL,NULL,0,1,0,'Activo',0,0,0,28,'lnxni0230',0),
	 (332,0,'CREDIT_BUREAU_SH.sh','Proceso Shell del Buró Crédito Sin Riesgos','/home/appextractor/Director/Sh','/home/appextractor/Director/Entrada/','RPT_SINRIESGOS_','TO_CHAR(sysdate-1,''yyyymmdd'')','/RepDWH/ARCHIVOS_BURO_CREDITO',1,10,60,'Inactivo',0,0,0,11,'sunni005',0),
	 (331,3,'RPT_CREDITBUREAU.sql','Reporte de crédito sin riesgos -  Área Crédito','/home/appextractor/Director/Sql','/home/appextractor/Director/Entrada/RPT_SINRIESGOS_','TO_CHAR(sysdate-1,''yyyymmdd'')','TO_CHAR(sysdate-1,''yyyymmdd'')',NULL,1,10,60,'Inactivo',1,7,1,11,'sunni005',0),
	 (330,3,'PRC_CLIENTSTATUS.sql','Proceso de crédito sin riesgos -  Área Crédito','/home/appextractor/Director/Sql',NULL,NULL,NULL,NULL,1,5,60,'Inactivo',0,0,0,11,'sunni005',0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS (IDPROC,IDCONEX,NOMBRE,DESCRIPCION,"PATH",PARAMETRO1,PARAMETRO2,PARAMETRO3,PARAMETRO4,DEPENDENCIA,INTENTOS,ESPERA_INTENTO,ESTADO,FTP,IDHOST,COMPRESION,IDCRONTAB,NODE,IDNOTIF) VALUES
	 (329,3,'RPT_AMIGOS_MOVISTAR.sql','Reporte Amigos Movistar Fide-Mercadeo','/home/appextractor/Director/Sql','/home/appextractor/Director/Entrada/RPT_Amigos_Movistar',NULL,NULL,NULL,1,10,60,'Inactivo',1,7,1,11,'sunni005',0),
	 (328,3,'RPT_IMEIS_DISTINTOS.sql','Reporte de Imeis Distintos - Area Fraude','${PATH_DIRECTOR_SQL}','${PATH_DIRECTOR_ENTRADA}/TRAF_LINEAS_DIVERSIDAD_IMEI_','TO_CHAR(sysdate-1,''yyyymmdd'')',NULL,NULL,1,1,0,'Inactivo',1,7,1,11,'lnxni0230',0),
	 (327,3,'PRC_IMEIS_DISTINTOS.sql','Proceso de Imeis Distintos - Area Fraude','${PATH_DIRECTOR_SQL}',NULL,NULL,NULL,NULL,0,1,0,'Inactivo',0,0,0,11,'lnxni0230',0),
	 (326,3,'RPT_SERIES_SIMCARD.sql','Reporte de Serie de Ventas Individuales','/home/appextractor/Director/Sql','/home/appextractor/Director/Entrada/RPT_FACT_NPW_SIMCARD_','TO_CHAR(sysdate-1,''yyyymm'')',NULL,NULL,1,10,60,'Inactivo',1,7,1,11,'sunni005',0),
	 (325,3,'PRC_SERIES_SIMCARD_2.sql','Proceso de Serie 2 de Ventas Individuales','/home/appextractor/Director/Sql','TO_CHAR(sysdate-1,''yyyymm'')',NULL,NULL,NULL,1,5,60,'Inactivo',0,0,0,11,'sunni005',0),
	 (324,6,'PRC_SERIES_SIMCARD_1.sql','Proceso de Serie 1 de Ventas Individuales','${PATH_DIRECTOR_SQL}','TO_CHAR(sysdate-1,''yyyymm'')',NULL,NULL,NULL,0,1,0,'Inactivo',0,0,0,26,'lnxni0230',0),
	 (323,3,'RPT_DETALLE_AMIGOS_MOVISTAR.sql','Reporte de Detalle del Servicio Amigos Movistar Fide','/home/appextractor/Director/Sql','/home/appextractor/Director/Entrada/RPT_Detalle_Amigos_Movistar_','TO_CHAR(sysdate-1,''yyyymm'')',NULL,NULL,0,10,60,'Inactivo',1,7,1,11,'sunni005',0),
	 (322,3,'RPT_RESUMEN_AMIGOS_MOVISTAR.sql','Reporte de Resumen del Servicio Amigos Movistar Fide','/home/appextractor/Director/Sql','/home/appextractor/Director/Entrada/RPT_Resumen_Amigos_Movistar_','TO_CHAR(sysdate-1,''yyyymm'')',NULL,NULL,0,10,60,'Inactivo',1,7,1,11,'sunni005',0),
	 (321,3,'RPT_BONOSANTIGUEDAD_PREPAGO.sql','Reporte Bonos de Antiguedad Mercadeo','/home/appextractor/Director/Sql','/home/appextractor/Director/Entrada/RPT_Seguimiento_BonosAntiguedad_','TO_CHAR(sysdate-1,''yyyymm'')',NULL,NULL,0,10,60,'Inactivo',1,7,0,11,'sunni005',0),
	 (320,3,'RPT_ESTATUS_PINES_PREPAGO.sql','Reporte Estado de Pines Mercadeo','/home/appextractor/Director/Sql','/home/appextractor/Director/Entrada/RPT_Seguimiento_PinesPrepago_','TO_CHAR(sysdate-1,''yyyymm'')',NULL,NULL,0,10,60,'Inactivo',1,7,0,11,'sunni005',0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS (IDPROC,IDCONEX,NOMBRE,DESCRIPCION,"PATH",PARAMETRO1,PARAMETRO2,PARAMETRO3,PARAMETRO4,DEPENDENCIA,INTENTOS,ESPERA_INTENTO,ESTADO,FTP,IDHOST,COMPRESION,IDCRONTAB,NODE,IDNOTIF) VALUES
	 (319,3,'RPT_SIMCARD_NPW_FACTURADAS.sql','Reporte Simcards NPW Facturadas','/home/appextractor/Director/Sql','/home/appextractor/Director/Entrada/RPT_SIMCARDS_NPW_FACTURADAS',NULL,NULL,NULL,1,10,60,'Inactivo',1,7,1,11,'sunni005',0),
	 (318,6,'PRC_SIMCARD_NPW_FACTURADAS.sql','Proceso Simcards NPW Facturadas','${PATH_DIRECTOR_SQL}',NULL,NULL,NULL,NULL,1,1,0,'Activo',0,0,0,26,'lnxni0230',0),
	 (315,6,'RPT_ABONADOS_POSPERSONALIZADOS.sql','Reporte de Clientes Post Personalizados','${PATH_DIRECTOR_SQL}','${PATH_DIRECTOR_ENTRADA}/Abonados_Postpersonalizados_','TO_CHAR(sysdate-1,''yyyymmdd'')',NULL,NULL,1,1,0,'Activo',1,7,1,26,'lnxni0230',0),
	 (314,6,'RPT_ABONADOS_PREPERSONALIZADOS.sql','Reporte de Clientes Pre Personalizados','${PATH_DIRECTOR_SQL}','${PATH_DIRECTOR_ENTRADA}/Abonados_Prepersonalizados_','TO_CHAR(sysdate-1,''yyyymmdd'')',NULL,NULL,1,1,0,'Activo',1,7,1,26,'lnxni0230',0),
	 (313,6,'RPT_SS_BAJAS_DIARIAS.sql','Reporte de Bajas Diarias','${PATH_DIRECTOR_SQL}','${PATH_DIRECTOR_ENTRADA}/SS_BajasAbonados_','TO_CHAR(sysdate-5,''yyyymm'')',NULL,NULL,1,1,0,'Activo',1,7,1,26,'lnxni0230',0),
	 (312,6,'RPT_SS_ALTAS_DIARIAS.sql','Reporte de Altas Diarias','${PATH_DIRECTOR_SQL}','${PATH_DIRECTOR_ENTRADA}/SS_AltasAbonados_','TO_CHAR(sysdate-1,''yyyymm'')',NULL,NULL,1,1,0,'Activo',1,7,1,26,'lnxni0230',0),
	 (311,6,'PRC_SSFACTURADOS.sql','Proceso','${PATH_DIRECTOR_SQL}',NULL,NULL,NULL,NULL,1,1,0,'Activo',0,0,0,26,'lnxni0230',0),
	 (310,0,'Carga_Posinfo_Xius.sh','Carga archivo Posinfo de Xius','/home/appextractor/Director/Sh','to_char(sysdate, ''ddmmyyyy'') ',NULL,NULL,NULL,1,600,60,'Inactivo',0,0,0,24,'sunni005',0),
	 (309,3,'valida_ult_evento.sql','VALIDA ULTIMO EVENTO EN APOLO ','/home/appextractor/Director/Sql',NULL,NULL,NULL,NULL,1,600,60,'Inactivo',0,0,0,11,'sunni005',0),
	 (308,6,'RPT_PAGOS_RECEXT_NOAPLICADOS.sql','Reporte de Pagos Recaudacion Externa No Aplicados','${PATH_DIRECTOR_SQL}','${PATH_DIRECTOR_ENTRADA}/PagosRecaudacionExternaNoAplicados_','TO_CHAR(sysdate-1,''yyyymmdd'')',NULL,NULL,1,1,0,'Activo',1,7,0,26,'lnxni0230',0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS (IDPROC,IDCONEX,NOMBRE,DESCRIPCION,"PATH",PARAMETRO1,PARAMETRO2,PARAMETRO3,PARAMETRO4,DEPENDENCIA,INTENTOS,ESPERA_INTENTO,ESTADO,FTP,IDHOST,COMPRESION,IDCRONTAB,NODE,IDNOTIF) VALUES
	 (307,6,'RPT_PAGOS_RECEXT_APLICADOS.sql','Reporte de Pagos Recaudacion Externa Aplicados','${PATH_DIRECTOR_SQL}','${PATH_DIRECTOR_ENTRADA}/PagosRecaudacionExternaAplicados_','TO_CHAR(sysdate-1,''yyyymm'')',NULL,NULL,1,1,0,'Activo',1,7,0,26,'lnxni0230',0),
	 (306,6,'RPT_PAGOS_RECEXT_ANOMALIAS.sql','Reporte de Pagos Recaudacion Externa Con Anomalías','${PATH_DIRECTOR_SQL}','${PATH_DIRECTOR_ENTRADA}/PagosRecaudacionExternaConAnomalias_','TO_CHAR(sysdate-1,''yyyymmdd'')',NULL,NULL,1,1,0,'Activo',1,7,0,26,'lnxni0230',0),
	 (305,3,'PRC_PREPAID_CUSTOMER_IVR.sql','Proceso','/home/appextractor/Director/Sql',NULL,NULL,NULL,NULL,1,5,60,'Inactivo',0,0,0,11,'sunni005',0),
	 (304,5,'AL_FABRICANTES','Extractor SCL','Extractor Full',NULL,NULL,NULL,NULL,1,1,300,'Activo',0,0,0,11,'lnxni0230',0),
	 (303,5,'GE_TIPDIRECCION','Extractor SCL','Extractor Full',NULL,NULL,NULL,NULL,1,1,300,'Activo',0,0,0,11,'lnxni0230',0),
	 (302,5,'GA_CATRIBUTCLIE','Extractor SCL','Extractor Full',NULL,NULL,NULL,NULL,1,1,300,'Activo',0,0,0,11,'lnxni0230',0),
	 (301,3,'RPT_PAGOSREV_SCL.sql','Reporte Pagos Revision SCL','/home/appextractor/Director/Sql','/home/appextractor/Director/Entrada/PagosRevSCL_','to_char(sysdate-1,''yyyymm'')',NULL,NULL,1,5,60,'Inactivo',1,7,0,11,'sunni005',0),
	 (300,3,'RPT_NUMBERS_NOTFOUND_ALTAMIRA.sql','Reporte números no encontrados Estados Numeración Altamira','/home/appextractor/Director/Sql','/home/appextractor/Director/Entrada/RPT_NumerosNoEncontrados_Altamira_',NULL,NULL,NULL,1,10,60,'Inactivo',1,7,1,11,'sunni005',0),
	 (299,3,'RPT_REVALUATION_INVENTORIES.sql','Reporte Revaluación Inventario','${PATH_DIRECTOR_SQL}','${PATH_DIRECTOR_ENTRADA}/RPT_Terminales_Revalorizacion',NULL,NULL,NULL,1,1,0,'Activo',1,7,1,11,'lnxni0230',0),
	 (298,3,'RPT_STATE_NUMBERING_ALTAMIRA.sql','Reporte estado de numeración Altamira','/home/appextractor/Director/Sql','/home/appextractor/Director/Entrada/RPT_Consolidado_Estados_Altamira_',NULL,NULL,NULL,1,10,60,'Inactivo',1,7,1,11,'sunni005',0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS (IDPROC,IDCONEX,NOMBRE,DESCRIPCION,"PATH",PARAMETRO1,PARAMETRO2,PARAMETRO3,PARAMETRO4,DEPENDENCIA,INTENTOS,ESPERA_INTENTO,ESTADO,FTP,IDHOST,COMPRESION,IDCRONTAB,NODE,IDNOTIF) VALUES
	 (297,3,'RPT_PAGOS_SCL.sql','Reporte Pagos SCL','${PATH_DIRECTOR_SQL}','${PATH_DIRECTOR_ENTRADA}/PagosSCL_','to_char(sysdate-1,''yyyymm'')',NULL,NULL,1,1,0,'Activo',1,7,0,11,'lnxni0230',0),
	 (296,6,'PRC_PAGOS_SCL.sql','Proceso','${PATH_DIRECTOR_SQL}','to_char(sysdate-1,''yyyymm'')',NULL,NULL,NULL,1,1,0,'Activo',0,0,0,26,'lnxni0230',0),
	 (295,3,'pagos_web.sql','REPORTE DE TELEPAGOS SE LE CONOCE COMO PagosAplicacionWEB','${PATH_DIRECTOR_SQL}','to_char(sysdate-1,''yyyymmdd'')','${PATH_DIRECTOR_ENTRADA}/',NULL,NULL,1,1,0,'Activo',1,7,0,11,'lnxni0230',0),
	 (294,3,'rpt_estado_chipitos.sql','Reporte genera listado de chipitos con su monto de recarga','/home/appextractor/Director/Sql','/home/appextractor/Director/Entrada/RPT_ESTADO_CHIPITOS_',NULL,NULL,NULL,1,600,60,'Inactivo',1,7,1,11,'sunni005',0),
	 (293,6,'RPT_NPW_DEVOLUCIONES.sql','Reporte de NPW Devoluciones','${PATH_DIRECTOR_SQL}','${PATH_DIRECTOR_ENTRADA}/RPT_NPW_DEVOLUCIONES','to_char(sysdate -1,''YYYY'')',NULL,NULL,1,1,0,'Activo',1,7,1,11,'lnxni0230',0),
	 (292,5,'GA_INFACCEL','Extractor SCL','Extractor Full',NULL,NULL,NULL,NULL,0,1,300,'Activo',0,0,0,11,'lnxni0230',0),
	 (291,5,'TA_NUMNACIONAL','Extractor SCL','Extractor Full',NULL,NULL,NULL,NULL,0,1,300,'Activo',0,0,0,11,'lnxni0230',0),
	 (290,5,'TOL_BOLSA_PLAN','Extractor SCL','Extractor Full',NULL,NULL,NULL,NULL,0,1,300,'Activo',0,0,0,11,'lnxni0230',0),
	 (289,3,'RPT_SALE_CHIPITOS.sql','Reporte Chipitos Marcados OUT','/home/appextractor/Director/Sql','to_char(sysdate-1,''yyyymmdd'')','/home/appextractor/Director/Entrada/CHIPITOS_MARCADOS_OUT_',NULL,NULL,1,600,60,'Inactivo',1,7,0,11,'sunni005',0),
	 (288,3,'EXTRACT_GPRS_APOLO.sql','EXTRACTOR TRAFICO DE APOLO GPRS','/home/appextractor/Director/Sql','to_char(sysdate-1,''yyyymmdd'')',NULL,NULL,NULL,1,600,60,'Inactivo',0,0,0,11,'sunni005',0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS (IDPROC,IDCONEX,NOMBRE,DESCRIPCION,"PATH",PARAMETRO1,PARAMETRO2,PARAMETRO3,PARAMETRO4,DEPENDENCIA,INTENTOS,ESPERA_INTENTO,ESTADO,FTP,IDHOST,COMPRESION,IDCRONTAB,NODE,IDNOTIF) VALUES
	 (287,6,'debito_automatico.sql','Reporte de debito automatico para ventas individuales','${PATH_DIRECTOR_SQL}','to_char(sysdate-1,''yyyymm'')','${PATH_DIRECTOR_ENTRADA}/ALTAS_DEBITO_ATUO_',NULL,NULL,1,1,0,'Activo',1,7,0,26,'lnxni0230',0),
	 (286,3,'RPT_VENTAS_FINANCIADAS.sql','Reporte de ventas financiadas','/home/appextractor/Director/Sql','/home/appextractor/Director/Entrada/RPT_VENTAS_FINANCIADAS_',NULL,NULL,NULL,1,10,60,'Inactivo',1,7,1,11,'sunni005',0),
	 (285,5,'CO_CANCELADOS','Extractor SCL','Extractor Full',NULL,NULL,NULL,NULL,1,1,300,'Activo',0,0,0,11,'lnxni0230',0),
	 (284,0,'SIR.sh','Shell FTP de Cartera SIR','/home/appextractor/Director/Sh','to_char(sysdate,''yyyymmdd'')',NULL,NULL,NULL,1,5,60,'Inactivo',0,0,0,11,'sunni005',0),
	 (283,3,'RPT_SIR_clientes.sql','Reporte Cartera Clientes','/home/appextractor/Director/Sql','/home/appextractor/Director/Entrada/SCL_NI_','clientes.txt',NULL,NULL,1,10,60,'Inactivo',1,11,0,11,'sunni005',0),
	 (282,3,'RPT_SIR_cartera_nociclo.sql','Reporte Cartera No Ciclo','/home/appextractor/Director/Sql','/home/appextractor/Director/Entrada/SCL_NI_','consumos.txt',NULL,NULL,1,10,60,'Inactivo',1,11,0,11,'sunni005',0),
	 (281,3,'RPT_SIR_cartera_ciclo.sql','Reporte Cartera Ciclo','/home/appextractor/Director/Sql','/home/appextractor/Director/Entrada/SCL_NI_','cartera.txt',NULL,NULL,0,10,60,'Inactivo',1,11,0,15,'sunni005',0),
	 (280,3,'RPT_VENTAS_POSTPAGO_SINTRAFICO.sql','Ventas Postpago Sin Tráfico','/home/appextractor/Director/Sql','/home/appextractor/Director/Entrada/RPT_VENTAS_POSTPAGO_SINTRAFICO_',NULL,NULL,NULL,1,10,60,'Inactivo',1,7,0,11,'sunni005',0),
	 (279,3,'rpt_imsi_apolo_inv.sql','PROCESO TRAF IMSI PARA FRAUDE','/home/appextractor/Director/Sql','/home/appextractor/Director/Entrada/rpt_imsi_apolo_inv_',NULL,NULL,NULL,1,5,60,'Inactivo',1,7,0,11,'sunni005',0),
	 (278,3,'notif_altas_x_hora.sql','NOTIFICACIONES EMAIL','/home/appextractor/Director/Sql',NULL,NULL,NULL,NULL,1,600,60,'Inactivo',0,0,0,23,'sunni005',0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS (IDPROC,IDCONEX,NOMBRE,DESCRIPCION,"PATH",PARAMETRO1,PARAMETRO2,PARAMETRO3,PARAMETRO4,DEPENDENCIA,INTENTOS,ESPERA_INTENTO,ESTADO,FTP,IDHOST,COMPRESION,IDCRONTAB,NODE,IDNOTIF) VALUES
	 (277,0,'ftp_tdr_fraud.sh','FTP','/home/appextractor/Director/Sh','TDR_n_','/home/appextractor/Director/Entrada',NULL,NULL,1,600,60,'Inactivo',0,0,0,11,'sunni005',0),
	 (276,3,'RPT_PLANES_CC_ALTAMIRA.sql','SALIDA del  REPORTE PLANES ALTAMIRA','/home/appextractor/Director/Sql','/home/appextractor/Director/Entrada/REPORTE_PLANES_ALTAMIRA_CC_',NULL,NULL,NULL,1,600,60,'Inactivo',0,0,0,11,'sunni005',0),
	 (275,3,'PRC_USUARIOS_ACTIVOS.sql','Proceso','${PATH_DIRECTOR_SQL}',NULL,NULL,NULL,NULL,0,1,0,'Activo',0,0,0,11,'lnxni0230',0),
	 (274,3,'PRC_TIPOLOGIA_A_BUZON_NUEVO.sql','Proceso','/home/appextractor/Director/Sql',NULL,NULL,NULL,NULL,0,10,60,'Inactivo',0,0,0,11,'sunni005',0),
	 (273,3,'PRC_RPT_PLANCES_CC_ALTAMIRA.sql','PROCESO DE REPORTE PLANES ALTAMIRA','/home/appextractor/Director/Sql',NULL,NULL,NULL,NULL,1,600,60,'Inactivo',0,0,0,11,'sunni005',0),
	 (272,5,'GA_LIMITE_CLIABO_TO','Extractor SCL','Extractor Full',NULL,NULL,NULL,NULL,1,1,300,'Activo',0,0,0,11,'lnxni0230',0),
	 (271,5,'GA_USUAMIST','Extractor SCL','Extractor Full',NULL,NULL,NULL,NULL,1,1,300,'Activo',0,0,0,11,'lnxni0230',0),
	 (270,5,'CO_INMUNES','Extractor SCL','Extractor Full',NULL,NULL,NULL,NULL,1,1,300,'Activo',0,0,0,11,'lnxni0230',0),
	 (269,5,'VE_VENDEALER','Extractor SCL','Extractor Full',NULL,NULL,NULL,NULL,1,1,300,'Activo',0,0,0,11,'lnxni0230',0),
	 (268,5,'CO_UNIPAC','Extractor SCL','Extractor Full',NULL,NULL,NULL,NULL,1,1,300,'Activo',0,0,0,11,'lnxni0230',0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS (IDPROC,IDCONEX,NOMBRE,DESCRIPCION,"PATH",PARAMETRO1,PARAMETRO2,PARAMETRO3,PARAMETRO4,DEPENDENCIA,INTENTOS,ESPERA_INTENTO,ESTADO,FTP,IDHOST,COMPRESION,IDCRONTAB,NODE,IDNOTIF) VALUES
	 (267,5,'GA_CAUSUSP','Extractor SCL','Extractor Full',NULL,NULL,NULL,NULL,1,1,300,'Activo',0,0,0,11,'lnxni0230',0),
	 (266,5,'GA_SUSPREHABO','Extractor SCL','Extractor Full',NULL,NULL,NULL,NULL,1,1,300,'Activo',0,0,0,11,'lnxni0230',0),
	 (265,3,'web_Altas_Prepago.sql','Reporte INTRANET','/home/appextractor/Director/Sql',NULL,NULL,NULL,NULL,1,600,60,'Inactivo',1,8,0,11,'sunni005',0),
	 (264,3,'FRAUDVIEW_TDR.SQL','PROCESO EXTRAE TDR para FraudView','/home/appextractor/Director/Sql','to_char(sysdate-1,''yyyymmdd'')','/home/appextractor/Director/Entrada',NULL,NULL,1,600,60,'Inactivo',0,0,0,11,'sunni005',0),
	 (263,3,'rpt_imei_apolo_inv.sql','PROCESO TRAF IMEI PARA FRAUDE','/home/appextractor/Director/Sql','/home/appextractor/Director/Entrada/traf_imei_apolo_',NULL,NULL,NULL,1,600,60,'Inactivo',1,7,0,11,'sunni005',0),
	 (262,6,'GA_CELNUM_USO','Extractor SCL','Extractor Full',NULL,NULL,NULL,NULL,1,1,300,'Activo',0,0,0,26,'lnxni0230',0),
	 (261,6,'GA_CATNUMER','Extractor SCL','Extractor Full',NULL,NULL,NULL,NULL,1,1,300,'Activo',0,0,0,26,'lnxni0230',0),
	 (260,3,'agenda_expandida.sql','PROCESO GENERA REPORTE AGENDA EXPANDIDA COBRANZA','/home/appextractor/Director/Sql','to_char(sysdate-1,''yyyymm'')','/home/appextractor/Director/Entrada/AGENDA_EXPANDIDA_',NULL,NULL,1,600,60,'Inactivo',1,7,0,11,'sunni005',0),
	 (259,2,'FRAUDVIEW_BC.SQL','PROCESO genera interfaz Balance checking paara FraudView','/home/appextractor/Director/Sql','to_char(sysdate-1,''yyyymmdd'')','/home/appextractor/Director/Entrada/',NULL,NULL,1,600,60,'Inactivo',0,0,0,11,'sunni005',0),
	 (255,3,'RPT_COMPARACION_FOTOS_MOVIMIENTOS.sql','Reporte','/home/appextractor/Director/Sql','/home/appextractor/Director/Entrada/RPT_COMPARACION_FOTOS_MOVIMIENTOS.txt',NULL,NULL,NULL,1,60,10,'Inactivo',1,7,1,11,'sunni005',0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS (IDPROC,IDCONEX,NOMBRE,DESCRIPCION,"PATH",PARAMETRO1,PARAMETRO2,PARAMETRO3,PARAMETRO4,DEPENDENCIA,INTENTOS,ESPERA_INTENTO,ESTADO,FTP,IDHOST,COMPRESION,IDCRONTAB,NODE,IDNOTIF) VALUES
	 (254,3,'RPT_COMPARACION_FOTOS_ABONADO.sql','Reporte','/home/appextractor/Director/Sql','/home/appextractor/Director/Entrada/RPT_COMPARACION_FOTOS_ABONADO.txt',NULL,NULL,NULL,1,60,10,'Inactivo',1,7,1,11,'sunni005',0),
	 (253,3,'PRC_COMPARACION_FOTOS.sql','Proceso','/home/appextractor/Director/Sql','TO_NUMBER(TO_CHAR(SYSDATE-2,''YYYYMMDD''))','TO_NUMBER(TO_CHAR(SYSDATE-1,''YYYYMMDD''))',NULL,NULL,1,60,10,'Inactivo',0,0,0,11,'sunni005',0),
	 (252,3,'ultima_recarga.sql','PROCESO EXTRAE ULTIMA REC COMPRADA ABONADOS','/home/appextractor/Director/Sql',NULL,NULL,NULL,NULL,1,600,60,'Inactivo',0,0,0,11,'sunni005',0),
	 (251,3,'RPT_SIMCARD_BODEGA_TRAFICO.sql','Reporte Finanzas','/home/appextractor/Director/Sql','/home/appextractor/Director/Entrada/SIMCARD_BODEGA_TRAFICO.txt',NULL,NULL,NULL,1,10,60,'Inactivo',1,7,0,11,'sunni005',0),
	 (250,6,'GED_PARAMETROS','Extractor SCL','Extractor Full',NULL,NULL,NULL,NULL,1,1,300,'Activo',0,0,0,26,'lnxni0230',0),
	 (249,6,'CO_PAGOSCONC','Extractor SCL','Extractor Full',NULL,NULL,NULL,NULL,1,60,60,'Inactivo',0,0,0,26,'sunni005',0),
	 (248,17,'BDDWH.DWD_TIPO_ENVIO','Extractor DWH','Extractor Full',NULL,NULL,NULL,NULL,1,60,60,'Inactivo',0,0,0,11,'sunni005',0),
	 (247,3,'DWD_TIPO_SERVICIO.sql','Extractor DWH','/home/appextractor/Director/Sql',NULL,NULL,NULL,NULL,1,600,60,'Inactivo',0,0,0,11,'sunni005',0),
	 (245,3,'RPT_SALDO_SUSPENDIDO.sql','Reporte de Finanzas','/home/appextractor/Director/Sql','/home/appextractor/Director/Entrada/RPT_SALDO_SUSPENDIDO_',NULL,NULL,NULL,1,10,60,'Inactivo',1,7,1,11,'sunni005',0),
	 (244,3,'PRC_SALDO_SUSPENDIDO.sql','Proceso','/home/appextractor/Director/Sql',NULL,NULL,NULL,NULL,0,5,60,'Inactivo',0,0,0,11,'sunni005',0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS (IDPROC,IDCONEX,NOMBRE,DESCRIPCION,"PATH",PARAMETRO1,PARAMETRO2,PARAMETRO3,PARAMETRO4,DEPENDENCIA,INTENTOS,ESPERA_INTENTO,ESTADO,FTP,IDHOST,COMPRESION,IDCRONTAB,NODE,IDNOTIF) VALUES
	 (243,2,'PRC_NUMEROS_HIBERNADOE.sql','Proceso','/home/appextractor/Director/Sql',NULL,NULL,NULL,NULL,1,5,60,'Inactivo',0,0,0,11,'sunni005',0),
	 (242,3,'PRC_NUMEROS_HIBERNADOD.sql','Proceso','/home/appextractor/Director/Sql',NULL,NULL,NULL,NULL,1,5,60,'Inactivo',0,0,0,11,'sunni005',0),
	 (241,2,'PRC_NUMEROS_HIBERNADOC.sql','Proceso','/home/appextractor/Director/Sql',NULL,NULL,NULL,NULL,1,5,60,'Inactivo',0,0,0,11,'sunni005',0),
	 (240,2,'PRC_NUMEROS_HIBERNADOS.sql','Proceso','/home/appextractor/Director/Sql',NULL,NULL,NULL,NULL,1,5,60,'Inactivo',0,0,0,11,'sunni005',0),
	 (239,3,'RPT_PARQUE_ENTRETONOS.sql','Reporte de Servicio Valor Agregado Aleman Saddy','/home/appextractor/Director/Sql','/home/appextractor/Director/Entrada/RPT_PARQUE_ENTRETONOS_',NULL,NULL,NULL,1,10,60,'Inactivo',1,7,1,11,'sunni005',0),
	 (238,3,'PRC_PARQUE_ENTRETONOS.sql','Proceso','${PATH_DIRECTOR_SQL}',NULL,NULL,NULL,NULL,1,1,0,'Inactivo',0,0,0,11,'lnxni0230',0),
	 (237,1,'PRC_CHG000000029437E.sql','Proceso','/home/appextractor/Director/Sql',NULL,NULL,NULL,NULL,1,5,60,'Inactivo',0,0,0,11,'sunni005',0),
	 (236,3,'PRC_CHG000000029437D.sql','Proceso','/home/appextractor/Director/Sql',NULL,NULL,NULL,NULL,1,5,60,'Inactivo',0,0,0,11,'sunni005',0),
	 (235,1,'PRC_CHG000000029437C.sql','Proceso','/home/appextractor/Director/Sql',NULL,NULL,NULL,NULL,1,5,60,'Inactivo',0,0,0,11,'sunni005',0),
	 (233,3,'PRC_CHG000000029437B.sql','Proceso','/home/appextractor/Director/Sql',NULL,NULL,NULL,NULL,1,5,60,'Inactivo',0,0,0,11,'sunni005',0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS (IDPROC,IDCONEX,NOMBRE,DESCRIPCION,"PATH",PARAMETRO1,PARAMETRO2,PARAMETRO3,PARAMETRO4,DEPENDENCIA,INTENTOS,ESPERA_INTENTO,ESTADO,FTP,IDHOST,COMPRESION,IDCRONTAB,NODE,IDNOTIF) VALUES
	 (232,1,'PRC_CHG000000029437A.sql','Proceso','/home/appextractor/Director/Sql',NULL,NULL,NULL,NULL,1,5,60,'Inactivo',0,0,0,11,'sunni005',0),
	 (231,3,'PRC_HIST_REP_INVENT.sql','PROCESO PARA APLICACION','${PATH_DIRECTOR_SQL}',NULL,NULL,NULL,NULL,1,1,0,'Activo',0,0,0,11,'lnxni0230',0),
	 (230,3,'VJ_RTP_GAC_BUZON_GESTION.sql','REPORTE GAC BUZON GESTION','/home/appextractor/Director/Sql','/home/appextractor/Director/Entrada/RPT_GAC_BUZON_GESTION_NEW_','to_char(sysdate-1,''yyyymm'')',NULL,NULL,1,600,60,'Inactivo',1,7,1,11,'sunni005',0),
	 (229,3,'RPT_REPORTE_DE_SIMCARDS_FACTURADOS.sql','Reporte Ventas Individuales','/home/appextractor/Director/Sql','/home/appextractor/Director/Entrada/RPT_REPORTE_DE_SIMCARDS_FACTURADOS_',NULL,NULL,NULL,1,10,60,'Inactivo',1,7,1,11,'sunni005',0),
	 (228,3,'PRC_REPORTE_DE_SIMCARDS_FACTURADOS.sql','Proceso','/home/appextractor/Director/Sql',NULL,NULL,NULL,NULL,0,5,60,'Inactivo',0,0,0,11,'sunni005',0),
	 (227,3,'RPT_EQUIPOS_CANJEADOS_POR_GARANTIAS.SQL','Reporte Logistica','/home/appextractor/Director/Sql','/home/appextractor/Director/Entrada/RPT_EQUIPOS_CANJEADOS_POR_GARANTIAS_',NULL,NULL,NULL,1,10,60,'inactivo',1,7,1,11,'sunni005',0),
	 (226,3,'PRC_EQUIPOS_CANJEADOS_POR_GARANTIAS.SQL','Proceso','/home/appextractor/Director/Sql',NULL,NULL,NULL,NULL,0,5,60,'inactivo',0,0,0,34,'sunni005',0),
	 (225,3,'RPT_CASOS_NO_CERRADOS_GAC.sql','Reporte Clientes','/home/appextractor/Director/Sql','/home/appextractor/Director/Entrada/RPT_CASOS_NO_CERRADOS_GAC_',NULL,NULL,NULL,1,10,60,'Inactivo',1,7,1,11,'sunni005',0),
	 (224,3,'PRC_CASOS_NO_CERRADOS_GAC.sql','Proceso','/home/appextractor/Director/Sql',NULL,NULL,NULL,NULL,0,5,60,'Inactivo',0,0,0,11,'sunni005',0),
	 (223,3,'VJ_RPT_GAC_CASOS_TIPOLOGIA.sql','Reporte GAC','/home/appextractor/Director/Sql','to_char(sysdate - 1, ''yyyymm'')||''01''','to_char(sysdate-1,''yyyymmdd'')','/home/appextractor/Director/Entrada/RPT_GAC_CASOS_TIPOLOGIA_NEW_',NULL,1,600,60,'Inactivo',1,7,1,11,'sunni005',0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS (IDPROC,IDCONEX,NOMBRE,DESCRIPCION,"PATH",PARAMETRO1,PARAMETRO2,PARAMETRO3,PARAMETRO4,DEPENDENCIA,INTENTOS,ESPERA_INTENTO,ESTADO,FTP,IDHOST,COMPRESION,IDCRONTAB,NODE,IDNOTIF) VALUES
	 (222,3,'VJ_RPT_GAC_CALLBACK.sql','Reporte GAC','/home/appextractor/Director/Sql','/home/appextractor/Director/Entrada/RPT_GAC_CALLBACK_NEW_','to_char(sysdate-1,''yyyymm'')',NULL,NULL,0,600,60,'Inactivo',1,7,1,11,'sunni005',0),
	 (221,3,'VJ_RPT_GAC_BACKOFFICE.sql','Reporte GAC','/home/appextractor/Director/Sql','to_char(sysdate - 1, ''yyyymm'')||''01''','to_char(sysdate-1,''yyyymmdd'')','/home/appextractor/Director/Entrada/RPT_GAC_BACKOFFICE_NEW_',NULL,1,600,60,'Inactivo',1,7,1,11,'sunni005',0),
	 (220,3,'VJ_RPT_GAC_NUMERO_DE_CONTACTO.sql','Reporte GAC','/home/appextractor/Director/Sql','to_char(sysdate - 1, ''yyyymm'')||''01''','to_char(sysdate - 1,  ''yyyymmdd'')','/home/appextractor/Director/Entrada/RPT_GAC_NUMERO_CONTACTO_NEW_',NULL,1,600,60,'Inactivo',1,7,1,11,'sunni005',0),
	 (219,3,'RPT_NUMEROS_HIBERNADOS.sql','Reporte Logistica','/home/appextractor/Director/Sql','/home/appextractor/Director/Entrada/RPT_NUMEROS_HIBERNADOS_',NULL,NULL,NULL,1,10,60,'Inactivo',1,7,1,11,'sunni005',0),
	 (218,3,'RPT_ESTADOS_NUMERACION.sql','Reporte Logistica','/home/appextractor/Director/Sql','/home/appextractor/Director/Entrada/RPT_ESTADOS_NUMERACION_',NULL,NULL,NULL,1,10,60,'Inactivo',1,7,1,11,'sunni005',0),
	 (217,10,'EXEC_CERRAR_CASOS_GAC.sql','Proceso Puntual','/home/appextractor/Director/Sql',NULL,NULL,NULL,NULL,0,0,0,'Inactivo',0,0,0,22,'sunni005',0),
	 (216,6,'AL_COMPONENTE_KIT','Extractor SCL','Extractor Full',NULL,NULL,NULL,NULL,1,1,300,'Activo',0,0,0,26,'lnxni0230',0),
	 (215,3,'RPT_CONSOLIDADO_ESTADOS.sql','Reporte Logistica','/home/appextractor/Director/Sql','/home/appextractor/Director/Entrada/RPT_Consolidado_Estados_',NULL,NULL,NULL,1,10,60,'Inactivo',1,7,1,11,'sunni005',0),
	 (214,3,'EXEC_REPORT_GENERATOR_PRC.sql','Proceso','/home/appextractor/Director/Sql',NULL,NULL,NULL,NULL,1,5,60,'Inactivo',0,0,0,11,'sunni005',0),
	 (213,3,'RPT_INVENTARIOS_DE_ARTICULOS.sql','Reporte Logistica','${PATH_DIRECTOR_SQL}','${PATH_DIRECTOR_ENTRADA}/Inventario_de_Articulos_',NULL,NULL,NULL,1,1,0,'Activo',1,7,1,11,'lnxni0230',0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS (IDPROC,IDCONEX,NOMBRE,DESCRIPCION,"PATH",PARAMETRO1,PARAMETRO2,PARAMETRO3,PARAMETRO4,DEPENDENCIA,INTENTOS,ESPERA_INTENTO,ESTADO,FTP,IDHOST,COMPRESION,IDCRONTAB,NODE,IDNOTIF) VALUES
	 (211,3,'TCN_CB_PLANES_IVR.sql','Interfaz IVR - REVISAR ELIMINACION - REVISAR ELIMINACION','${PATH_DIRECTOR_SQL}',NULL,NULL,NULL,NULL,1,1,0,'Activo',0,0,0,11,'lnxni0230',0),
	 (210,3,'TCN_ALTAS_IPHONE_IVR.sql','Interfaz IVR - REVISAR ELIMINACION','${PATH_DIRECTOR_SQL}',NULL,NULL,NULL,NULL,1,1,0,'Activo',0,0,0,11,'lnxni0230',0),
	 (209,3,'TCN_PARQUE_UMTS_IVR_ACTIVO.sql','Interfaz IVR','/home/appextractor/Director/Sql',NULL,NULL,NULL,NULL,1,60,60,'Inactivo',0,0,0,11,'sunni005',0),
	 (208,6,'SC_GRPCONCEPTO_TD','Extractor SCL','Extractor Full',NULL,NULL,NULL,NULL,1,1,300,'Activo',0,0,0,26,'lnxni0230',0),
	 (207,6,'RET_ENTIDAD_TRAD','Extractor SCL','Extractor Full',NULL,NULL,NULL,NULL,1,1,300,'Activo',0,0,0,26,'lnxni0230',0),
	 (206,6,'GE_TIPTARJETAS','Extractor SCL','Extractor Full',NULL,NULL,NULL,NULL,1,1,300,'Activo',0,0,0,26,'lnxni0230',0),
	 (205,6,'GE_TIPDOCUMEN','Extractor SCL','Extractor Full',NULL,NULL,NULL,NULL,1,1,300,'Activo',0,0,0,26,'lnxni0230',0),
	 (204,6,'GE_SEG_USUARIO','Extractor SCL','Extractor Full',NULL,NULL,NULL,NULL,1,1,300,'Activo',0,0,0,26,'lnxni0230',0),
	 (203,6,'GE_PRODUCTOS','Extractor SCL','Extractor Full',NULL,NULL,NULL,NULL,1,1,300,'Activo',0,0,0,26,'lnxni0230',0),
	 (202,6,'GE_OFICINAS','Extractor SCL','Extractor Full',NULL,NULL,NULL,NULL,1,1,300,'Activo',0,0,0,26,'lnxni0230',0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS (IDPROC,IDCONEX,NOMBRE,DESCRIPCION,"PATH",PARAMETRO1,PARAMETRO2,PARAMETRO3,PARAMETRO4,DEPENDENCIA,INTENTOS,ESPERA_INTENTO,ESTADO,FTP,IDHOST,COMPRESION,IDCRONTAB,NODE,IDNOTIF) VALUES
	 (201,6,'GE_MONEDAS','Extractor SCL','Extractor Full',NULL,NULL,NULL,NULL,1,1,300,'Activo',0,0,0,26,'lnxni0230',0),
	 (200,6,'GE_MODULOS','Extractor SCL','Extractor Full',NULL,NULL,NULL,NULL,1,1,300,'Activo',0,0,0,26,'lnxni0230',0),
	 (199,6,'GE_COMUNAS','Extractor SCL','Extractor Full',NULL,NULL,NULL,NULL,1,1,300,'Activo',0,0,0,26,'lnxni0230',0),
	 (198,6,'GA_TARIFAS','Extractor SCL','Extractor Full',NULL,NULL,NULL,NULL,1,1,300,'Activo',0,0,0,26,'lnxni0230',0),
	 (197,6,'GA_SERVSUPL','Extractor SCL','Extractor Full',NULL,NULL,NULL,NULL,1,1,300,'Activo',0,0,0,26,'lnxni0230',0),
	 (196,6,'FA_TIPCONCEPTOS','Extractor SCL','Extractor Full',NULL,NULL,NULL,NULL,1,1,300,'Activo',0,0,0,26,'lnxni0230',0),
	 (195,6,'FA_CICLOS','Extractor SCL','Extractor Full',NULL,NULL,NULL,NULL,1,1,300,'Activo',0,0,0,26,'lnxni0230',0),
	 (194,6,'FA_AJUSTES','Extractor SCL','Extractor Full',NULL,NULL,NULL,NULL,1,1,300,'Activo',0,0,0,26,'lnxni0230',0),
	 (193,6,'CO_SALDOCONS_TO','Extractor SCL','Extractor Full',NULL,NULL,NULL,NULL,1,1,300,'Activo',0,0,0,26,'lnxni0230',0),
	 (192,6,'CO_PAGOSPAC','Extractor SCL','Extractor Full',NULL,NULL,NULL,NULL,1,1,300,'Inactivo',0,0,0,26,'lnxni0230',0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS (IDPROC,IDCONEX,NOMBRE,DESCRIPCION,"PATH",PARAMETRO1,PARAMETRO2,PARAMETRO3,PARAMETRO4,DEPENDENCIA,INTENTOS,ESPERA_INTENTO,ESTADO,FTP,IDHOST,COMPRESION,IDCRONTAB,NODE,IDNOTIF) VALUES
	 (191,6,'CO_ORIGENPAGO','Extractor SCL','Extractor Full',NULL,NULL,NULL,NULL,1,1,300,'Activo',0,0,0,26,'lnxni0230',0),
	 (190,6,'CO_INTERFAZ_EXTERNA','Extractor SCL','Extractor Full',NULL,NULL,NULL,NULL,1,1,300,'Activo',0,0,0,26,'lnxni0230',0),
	 (189,6,'CO_ANOMALIA_EXTERNA','Extractor SCL','Extractor Full',NULL,NULL,NULL,NULL,1,1,300,'Activo',0,0,0,26,'lnxni0230',0),
	 (188,6,'CO_AJUSTECONC','Extractor SCL','Extractor Full',NULL,NULL,NULL,NULL,1,1,300,'Activo',0,0,0,26,'lnxni0230',0),
	 (187,6,'AL_PROMFACT','Extractor SCL','Extractor Full',NULL,NULL,NULL,NULL,1,1,300,'Activo',0,0,0,26,'lnxni0230',0),
	 (185,6,'AL_HCABECERA_ORDENES2','Extractor SCL','Extractor Full',NULL,NULL,NULL,NULL,1,1,300,'Activo',0,0,0,26,'lnxni0230',0),
	 (184,6,'AL_ANTIGUEDAD','Extractor SCL','Extractor Full',NULL,NULL,NULL,NULL,1,1,300,'Activo',0,0,0,26,'lnxni0230',0),
	 (183,1,'PPGA_TIPBONO','Extractor Altamira','Extractor Full',NULL,NULL,NULL,NULL,1,1,0,'Inactivo',0,0,0,11,'lnxni0230',0),
	 (182,1,'PPGA_BONOS','Extractor Altamira','Extractor Full',NULL,NULL,NULL,NULL,1,1,0,'Inactivo',0,0,0,11,'lnxni0230',0),
	 (181,3,'RPT_GAC_TIPOLOGIAS_BUZON.sql','Reporte','/home/appextractor/Director/Sql','/home/appextractor/Director/Entrada/RPT_GAC_TIPOLOGIAS_BUZON_',NULL,NULL,NULL,1,60,60,'Inactivo',1,7,1,11,'sunni005',0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS (IDPROC,IDCONEX,NOMBRE,DESCRIPCION,"PATH",PARAMETRO1,PARAMETRO2,PARAMETRO3,PARAMETRO4,DEPENDENCIA,INTENTOS,ESPERA_INTENTO,ESTADO,FTP,IDHOST,COMPRESION,IDCRONTAB,NODE,IDNOTIF) VALUES
	 (179,3,'RPT_GAC_NUMERO_DE_CONTACTO.sql','Reporte','/home/appextractor/Director/Sql','/home/appextractor/Director/Entrada/RPT_GAC_NUMERO_DE_CONTACTO_',NULL,NULL,NULL,1,60,60,'Inactivo',1,7,1,11,'sunni005',0),
	 (178,3,'RPT_GAC_GESTION.sql','Reporte','/home/appextractor/Director/Sql','/home/appextractor/Director/Entrada/RPT_GAC_GESTION_',NULL,NULL,NULL,1,60,60,'Inactivo',1,7,1,11,'sunni005',0),
	 (177,3,'RPT_GAC_CASOS_POR_TIPOLOGIA.sql','Reporte','/home/appextractor/Director/Sql','/home/appextractor/Director/Entrada/RPT_GAC_CASOS_POR_TIPOLOGIA_',NULL,NULL,NULL,1,60,60,'Inactivo',1,7,1,11,'sunni005',0),
	 (176,3,'RPT_GAC_CALLBACK.sql','Reporte','/home/appextractor/Director/Sql','/home/appextractor/Director/Entrada/RPT_GAC_CALLBACK_',NULL,NULL,NULL,1,60,60,'Inactivo',1,7,1,11,'sunni005',0),
	 (175,3,'RPT_GAC_USUARIOS_ACTIVOS.sql','Reporte','/home/appextractor/Director/Sql','/home/appextractor/Director/Entrada/RPT_GAC_USUARIOS_ACTIVOS_',NULL,NULL,NULL,1,60,60,'Inactivo',1,7,1,11,'sunni005',0),
	 (174,3,'RPT_GAC_BACKOFFICE.sql','Reporte','/home/appextractor/Director/Sql','/home/appextractor/Director/Entrada/RPT_GAC_BACKOFFICE_',NULL,NULL,NULL,1,60,60,'Inactivo',1,7,1,11,'sunni005',0),
	 (173,3,'T_CUSTOMER_SERVICE.sql','Interfaz T_CUSTOMER_SERVICE para WEDO','/home/appextractor/Director/Sql','to_number(to_char(trunc(sysdate,''MM'')-2,''YYYYMM''))','/home/appextractor/Director/Entrada/NIC_T_CUSTOMER_SERVICE_',NULL,NULL,1,600,60,'Inactivo',0,0,0,11,'sunni005',0),
	 (172,3,'Call_CAV_CTA_CTE.sql','Ejecuta proceso que carga saldos de los clientes para el CAV','/home/appextractor/Director/Sql',NULL,NULL,NULL,NULL,1,600,60,'Inactivo',0,0,0,11,'sunni005',0),
	 (171,3,'PRC_GAC_CASOS_POR_TIPOLOGIA.sql','Proceso','/home/appextractor/Director/Sql',NULL,NULL,NULL,NULL,1,10,60,'Inactivo',0,0,0,11,'sunni005',0),
	 (169,3,'PRC_GAC_CALLBACK.sql','Proceso','/home/appextractor/Director/Sql',NULL,NULL,NULL,NULL,1,10,60,'Inactivo',0,0,0,11,'sunni005',0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS (IDPROC,IDCONEX,NOMBRE,DESCRIPCION,"PATH",PARAMETRO1,PARAMETRO2,PARAMETRO3,PARAMETRO4,DEPENDENCIA,INTENTOS,ESPERA_INTENTO,ESTADO,FTP,IDHOST,COMPRESION,IDCRONTAB,NODE,IDNOTIF) VALUES
	 (168,3,'PRC_GAC_GESTION.sql','Proceso','/home/appextractor/Director/Sql',NULL,NULL,NULL,NULL,1,10,60,'Inactivo',0,0,0,11,'sunni005',0),
	 (167,3,'PRC_GAC_NUMERO_DE_CONTACTO.sql','Proceso','/home/appextractor/Director/Sql',NULL,NULL,NULL,NULL,1,10,60,'Inactivo',0,0,0,11,'sunni005',0),
	 (166,3,'GAC_USUARIOS_ACTIVOS.sql','Proceso','/home/appextractor/Director/Sql',NULL,NULL,NULL,NULL,1,10,60,'Inactivo',0,0,0,11,'sunni005',0),
	 (165,3,'PRC_GAC_TIPOLOGIAS_BUZON.sql','Proceso','/home/appextractor/Director/Sql',NULL,NULL,NULL,NULL,1,10,60,'Inactivo',0,0,0,11,'sunni005',0),
	 (164,3,'PRC_GAC_BACKOFFICE.sql','Proceso','/home/appextractor/Director/Sql',NULL,NULL,NULL,NULL,0,0,0,'Inactivo',0,0,0,11,'sunni005',0),
	 (163,5,'GA_CELNUM_REUTIL','Extractor SCL','Extractor Full',NULL,NULL,NULL,NULL,0,1,300,'Activo',0,0,0,11,'lnxni0230',0),
	 (162,0,'ConexionRLPPCSN.sh','Conexión','/home/appextractor/Director/Sh','to_char(sysdate,''yyyymmdd'')',NULL,NULL,NULL,0,5,60,'Inactivo',0,0,0,11,'sunni005',0),
	 (161,3,'NOTIF_INGRESOS_X_DIA.sql','Notificación','/home/appextractor/Director/Sql',NULL,NULL,NULL,NULL,1,600,60,'Inactivo',0,0,0,11,'sunni005',0),
	 (160,3,'NOTIF_RECARGAS_RESUMEN.sql','Notificación','/home/appextractor/Director/Sql',NULL,NULL,NULL,NULL,1,600,60,'Inactivo',0,0,0,11,'sunni005',0),
	 (159,3,'NOTIF_RECARGAS_X_HORA.sql','Notificación','/home/appextractor/Director/Sql',NULL,NULL,NULL,NULL,1,600,60,'Inactivo',0,0,0,19,'sunni005',0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS (IDPROC,IDCONEX,NOMBRE,DESCRIPCION,"PATH",PARAMETRO1,PARAMETRO2,PARAMETRO3,PARAMETRO4,DEPENDENCIA,INTENTOS,ESPERA_INTENTO,ESTADO,FTP,IDHOST,COMPRESION,IDCRONTAB,NODE,IDNOTIF) VALUES
	 (158,3,'GSM_DET_SIMCARD_TO.sql','Extractor SCL','${PATH_DIRECTOR_SQL}',NULL,NULL,NULL,NULL,1,1,300,'Activo',0,0,0,11,'lnxni0230',0),
	 (157,3,'RPT_SALDOMOVICS_MOV.sql','Reporte','/home/appextractor/Director/Sql','/home/appextractor/Director/Entrada/SaldosMovics_Mov','to_char(sysdate,''yyyymm'')',NULL,NULL,1,10,60,'Inactivo',1,7,0,14,'sunni005',0),
	 (156,3,'RPT_SALDOMOVICS.sql','Reporte','/home/appextractor/Director/Sql','/home/appextractor/Director/Entrada/SaldosMovics_',NULL,NULL,NULL,0,0,0,'Inactivo',1,7,1,14,'sunni005',0),
	 (155,3,'RPT_CUMPLEANOS.sql','REPORTE CUMPLEAÑEROS','/home/appextractor/Director/Sql','/home/appextractor/Director/Entrada/REPORTE_CUMPLEANOS_',NULL,NULL,NULL,1,600,60,'Inactivo',1,7,0,11,'sunni005',0),
	 (154,3,'SMS_entrante_6113.sql','REPORTE SMS Entrante 6113','/home/appextractor/Director/Sql','to_char(sysdate-1,''yyyymmdd'')','/home/appextractor/Director/Entrada/RPT_SMS_6113_',NULL,NULL,1,600,60,'Inactivo',1,7,1,11,'sunni005',0),
	 (153,3,'Rpt_lineas_faltanPyme.sql','REPORTE Lineas Faltan en Pyme','${PATH_DIRECTOR_SQL}','to_char(sysdate-1,''yyyymm'')','${PATH_DIRECTOR_ENTRADA}/RPT_Lineas_Faltan_Pyme_',NULL,NULL,1,1,0,'Activo',1,7,0,11,'lnxni0230',0),
	 (152,6,'Rpt_Acreedores_Deudores.sql','REPORTE ACREEDORES DEUDORES INGRESOS','/home/appextractor/Director/Sql','/home/appextractor/Director/Entrada/CLIENTES_SALDO_DEUDOR_Y_ACREEDOR_',NULL,NULL,NULL,1,600,60,'inactivo',1,7,1,24,'sunni005',0),
	 (151,3,'SCL_SERVICIO_DATOS.sql','Interfaz','${PATH_DIRECTOR_SQL}',NULL,NULL,NULL,NULL,1,1,0,'Activo',0,0,0,11,'lnxni0230',0),
	 (150,6,'CREA_DBLINK_RSCLNIC.sql','Proceso','${PATH_DIRECTOR_SQL}',NULL,NULL,NULL,NULL,1,1,0,'Activo',0,0,0,26,'lnxni0230',0),
	 (149,3,'ult_prc_articulo.sql','Genera Reporte Ultimo precio x articulo','${PATH_DIRECTOR_SQL}','${PATH_DIRECTOR_ENTRADA}/Rpt_ultimo_Precio_articulo_',NULL,NULL,NULL,1,1,0,'Activo',1,7,0,11,'lnxni0230',0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS (IDPROC,IDCONEX,NOMBRE,DESCRIPCION,"PATH",PARAMETRO1,PARAMETRO2,PARAMETRO3,PARAMETRO4,DEPENDENCIA,INTENTOS,ESPERA_INTENTO,ESTADO,FTP,IDHOST,COMPRESION,IDCRONTAB,NODE,IDNOTIF) VALUES
	 (148,3,'TCN_CDR_GSM_NICMS.sql','EXTRACTOR TRAFICO DE APOLO CDR','/home/appextractor/Director/Sql','to_char(sysdate-1,''yyyymmdd'')',NULL,NULL,NULL,0,600,60,'Inactivo',0,0,0,24,'sunni005',0),
	 (147,1,'PPGA_LITERALES','Extractor Altamira','Extractor Full',NULL,NULL,NULL,NULL,1,1,0,'Inactivo',0,0,0,11,'lnxni0230',0),
	 (146,3,'MARCACIONES_CORTAS.sql','Interfaz','/home/appextractor/Director/Sql','NOMBRE_PARTICION_APOLO(sysdate-1)','to_char(sysdate-1,''yyyymmdd'')',NULL,NULL,0,0,0,'Inactivo',0,0,0,11,'sunni005',0),
	 (145,6,'EQUIPOS_FACT_CICLO.sql','PROCESO EXTRAE FACT EQ CICLO REPORTE NPW','${PATH_DIRECTOR_SQL}','TO_CHAR(sysdate-2,''yyyymm'')',NULL,NULL,NULL,1,1,0,'Activo',0,0,0,26,'lnxni0230',0),
	 (144,3,'EXTRAE_CARGA_DWD_ABONADO.sql','Proceso copia abonado SIEMCAM AWS','${PATH_DIRECTOR_SQL}',NULL,NULL,NULL,NULL,1,1,0,'Activo',0,0,0,11,'lnxni0230',0),
	 (143,0,'rpt_lista_gris.sh','REPORTE LISTA GRIS','/home/appextractor/Director/Sh','/home/appextractor/Director',NULL,NULL,NULL,1,600,60,'Inactivo',0,0,0,11,'sunni005',0),
	 (142,3,'CONSOLIDADO_MOVIMIENTOS.sql','Interfaz','/home/appextractor/Director/Sql','to_char(sysdate-2,''yyyymm'')',NULL,NULL,NULL,1,600,60,'Inactivo',0,0,0,11,'sunni005',0),
	 (141,3,'Calculo_de_Comisiones.sql','Interfaz','/home/appextractor/Director/Sql','to_char(sysdate-2,''yyyymm'')',NULL,NULL,NULL,1,600,60,'Inactivo',0,0,0,11,'sunni005',0),
	 (140,0,'dwh.sh','INTERFACES DATA WAREHOUSE','/home/appextractor/Director/Sh',NULL,NULL,NULL,NULL,1,600,60,'Inactivo',0,0,0,11,'sunni005',0),
	 (139,3,'mora_temprana.sql','REPORTE MORA TEMPRANA','${PATH_DIRECTOR_SQL}','${PATH_DIRECTOR_ENTRADA}/MORA_TEMPRANA_',NULL,NULL,NULL,1,1,0,'Activo',1,7,0,11,'lnxni0230',0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS (IDPROC,IDCONEX,NOMBRE,DESCRIPCION,"PATH",PARAMETRO1,PARAMETRO2,PARAMETRO3,PARAMETRO4,DEPENDENCIA,INTENTOS,ESPERA_INTENTO,ESTADO,FTP,IDHOST,COMPRESION,IDCRONTAB,NODE,IDNOTIF) VALUES
	 (138,3,'Script_crea_vista_inv.sql','SCRIPT VISTA MOV INV','${PATH_DIRECTOR_SQL}','to_char (sysdate-2,''yymm'')',NULL,NULL,NULL,1,1,0,'Activo',0,0,0,11,'lnxni0230',0),
	 (137,0,'CHIPITOS_FINAL_VENUS.sh','PROCESO DE CHIPITOS PARTE 3','/home/appextractor/Director/Sh',NULL,NULL,NULL,NULL,1,600,60,'Inactivo',0,0,0,11,'sunni005',0),
	 (136,0,'CREA_CHIPITOS_03_RLPPGAN.sh','PROCESO DE CHIPITOS PARTE 3','/home/appextractor/Director/Sh',NULL,NULL,NULL,NULL,1,600,60,'Inactivo',0,0,0,11,'sunni005',0),
	 (135,0,'CHIPITOS_01_VENUS.sh','PROCESO DE CHIPITOS PARTE 2','/home/appextractor/Director/Sh',NULL,NULL,NULL,NULL,1,600,60,'Inactivo',0,0,0,11,'sunni005',0),
	 (134,1,'CREA_TMP_CHIPITOS_01_RLPPGAN.sql','PROCESO DE CHIPITOS PARTE 1','/home/appextractor/Director/Sql',NULL,NULL,NULL,NULL,1,600,60,'Inactivo',0,0,0,11,'sunni005',0),
	 (133,3,'CREA_ICC_HISTMOV.sql','CREA O ACTUALIZA LA TABLA icc_histmov de le mes en curso','${PATH_DIRECTOR_SQL}',NULL,NULL,NULL,NULL,1,1,0,'Activo',0,0,0,11,'lnxni0230',0),
	 (132,5,'VE_TIPCOMIS','Extractor SCL','Extractor Full',NULL,NULL,NULL,NULL,1,1,300,'Activo',0,0,0,11,'lnxni0230',0),
	 (131,5,'GA_USUARIOS','Extractor SCL','Extractor Full',NULL,NULL,NULL,NULL,1,1,300,'Activo',0,0,0,11,'lnxni0230',0),
	 (130,5,'ICG_ACTUACION','Extractor SCL','Extractor Full',NULL,NULL,NULL,NULL,1,1,300,'Activo',0,0,0,11,'lnxni0230',0),
	 (129,3,'TCN_BOLSAS_BREAKAGE_VENUS.sql','Proceso 2 de TCN_BOLSAS_BREAKAGE','/home/appextractor/Director/Sql',NULL,NULL,NULL,NULL,1,600,60,'Inactivo',0,0,0,11,'sunni005',0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS (IDPROC,IDCONEX,NOMBRE,DESCRIPCION,"PATH",PARAMETRO1,PARAMETRO2,PARAMETRO3,PARAMETRO4,DEPENDENCIA,INTENTOS,ESPERA_INTENTO,ESTADO,FTP,IDHOST,COMPRESION,IDCRONTAB,NODE,IDNOTIF) VALUES
	 (128,1,'TCN_BOLSAS_BREAKAGE_RLPPGAN.sql','Proceso 1 de TCN_BOLSAS_BREAKAGE','/home/appextractor/Director/Sql','to_char(sysdate-1,''yyyymm"01000000"'')','to_char(sysdate-1,''yyyymmdd"235959"'')',NULL,NULL,1,600,60,'Inactivo',0,0,0,11,'sunni005',0),
	 (127,0,'Bolsas_SDP.sh','Proceso BOLSAS SDP','/home/appextractor/Director/Sh','to_char(sysdate,''ddmmyy'')','to_char(sysdate-1,''yyyymmdd'')',NULL,NULL,1,600,60,'Inactivo',0,0,0,11,'sunni005',0),
	 (126,9,'POGE_TARJETAS','Extractor Altamira','Extractor Full',NULL,NULL,NULL,NULL,1,1,0,'Inactivo',0,0,0,11,'lnxni0230',0),
	 (125,3,'TOL_RANNUME.sql','Proceso Extractor SCL','${PATH_DIRECTOR_SQL}',NULL,NULL,NULL,NULL,1,1,300,'Activo',0,0,0,11,'lnxni0230',0),
	 (124,5,'CO_CODIGOS','Extractor SCL','Extractor Full',NULL,NULL,NULL,NULL,1,1,300,'Activo',0,0,0,11,'lnxni0230',0),
	 (123,5,'GE_TIPIDENT','Extractor SCL','Extractor Full',NULL,NULL,NULL,NULL,1,1,300,'Activo',0,0,0,11,'lnxni0230',0),
	 (122,5,'GA_SITUABO','Extractor SCL','Extractor Full',NULL,NULL,NULL,NULL,1,1,300,'Activo',0,0,0,11,'lnxni0230',0),
	 (121,5,'CO_PAGOS','Extractor SCL','Extractor Full',NULL,NULL,NULL,NULL,1,1,300,'Inactivo',0,0,0,11,'lnxni0230',0),
	 (120,5,'CO_HINTERFAZ_EXTERNA','Extractor SCL','Extractor Full',NULL,NULL,NULL,NULL,1,1,300,'Activo',0,0,0,11,'lnxni0230',0),
	 (119,3,'PREC_INIC_TARJETA.sql','Interfaz','/home/appextractor/Director/Sql','TO_CHAR(sysdate-1,''yyyymm'')',NULL,NULL,NULL,1,600,60,'Inactivo',0,0,0,11,'sunni005',0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS (IDPROC,IDCONEX,NOMBRE,DESCRIPCION,"PATH",PARAMETRO1,PARAMETRO2,PARAMETRO3,PARAMETRO4,DEPENDENCIA,INTENTOS,ESPERA_INTENTO,ESTADO,FTP,IDHOST,COMPRESION,IDCRONTAB,NODE,IDNOTIF) VALUES
	 (117,6,'AL_MOVIMIENTOS_TIP_10_TARJ.sql','Extractor SCL','/home/appextractor/Director/Sql',NULL,NULL,NULL,NULL,1,600,60,'Inactivo',0,0,0,26,'sunni005',0),
	 (116,3,'PPGA_PROMOCIONES.sql','Interfaz','/home/appextractor/Director/Sql',NULL,NULL,NULL,NULL,0,600,60,'Inactivo',0,0,0,29,'sunni005',0),
	 (115,5,'GE_CONVERSION','Extractor SCL','Extractor Full',NULL,NULL,NULL,NULL,0,1,300,'Activo',0,0,0,11,'lnxni0230',0),
	 (114,3,'prc_web_obsolescencia.sql','Procedimiento Utilizado por Web Obsolescencia','${PATH_DIRECTOR_SQL}',NULL,NULL,NULL,NULL,1,1,0,'Activo',0,0,0,11,'lnxni0230',0),
	 (113,3,'Parque_INOPAC.sql','REPORTE PARQUE INOPAC','/home/appextractor/Director/Sql','/home/appextractor/Director/Entrada/Parque_Inopac_',NULL,NULL,NULL,1,600,60,'Inactivo',1,12,1,11,'sunni005',0),
	 (112,5,'FA_CONCEPTOS','Extractor SCL','Extractor Full',NULL,NULL,NULL,NULL,0,1,300,'Activo',0,0,0,11,'lnxni0230',0),
	 (111,3,'rpt_web_prepsaldo.sql','REPORTE INTRANET PREPAGO CON SALDO','/home/appextractor/Director/Sql',NULL,NULL,NULL,NULL,1,600,60,'Inactivo',1,8,0,11,'sunni005',0),
	 (110,3,'rpt_web_pos_saldo_neg.sql','REPORTE INTRANTE POSTPAGO SALDO NEGATIVO','/home/appextractor/Director/Sql',NULL,NULL,NULL,NULL,1,600,60,'Inactivo',1,8,0,11,'sunni005',0),
	 (109,3,'rpt_det_bajas_postpago.sql','REPORTE DETALLE BAJAS POSTPAGO','/home/appextractor/Director/Sql','/home/appextractor/Director/Entrada/detalle_bajas_postpago',NULL,NULL,NULL,1,600,60,'Inactivo',1,7,0,11,'sunni005',0),
	 (108,3,'TCN_PREPAGO_TELEFONOS.sql','Interfaz','/home/appextractor/Director/Sql',NULL,NULL,NULL,NULL,1,600,60,'Inactivo',0,0,0,11,'sunni005',0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS (IDPROC,IDCONEX,NOMBRE,DESCRIPCION,"PATH",PARAMETRO1,PARAMETRO2,PARAMETRO3,PARAMETRO4,DEPENDENCIA,INTENTOS,ESPERA_INTENTO,ESTADO,FTP,IDHOST,COMPRESION,IDCRONTAB,NODE,IDNOTIF) VALUES
	 (107,1,'PPAC_USUARIOS','Extractor Altamira','Extractor Full',NULL,NULL,NULL,NULL,1,1,0,'Inactivo',0,0,0,11,'lnxni0230',0),
	 (106,1,'PPGA_TIPPREPA','Extractor Altamira','Extractor Full',NULL,NULL,NULL,NULL,1,1,0,'Inactivo',0,0,0,11,'lnxni0230',0),
	 (105,1,'PPGA_ESTAPREP','Extractor Altamira','Extractor Full',NULL,NULL,NULL,NULL,1,1,0,'Inactivo',0,0,0,11,'lnxni0230',0),
	 (103,1,'PPGA_ABOPREPCOM','Extractor Altamira','Extractor Full',NULL,NULL,NULL,NULL,1,1,0,'Inactivo',0,0,0,11,'lnxni0230',0),
	 (102,3,'GenerarArpu.sql','PROCESO INSERTE ARPU Y PASA A HISTORICO','/home/appextractor/Director/Sql',NULL,NULL,NULL,NULL,0,600,60,'Inactivo',0,0,0,11,'sunni005',0),
	 (101,3,'CALCULO_ARPU.sql','PROCESO CALCULA ARPU','/home/appextractor/Director/Sql',NULL,NULL,NULL,NULL,0,600,60,'Inactivo',0,0,0,11,'sunni005',0),
	 (100,3,'CARGA_FA_HISTCONC_19010102.sql','Extractor SCL','${PATH_DIRECTOR_SQL}',NULL,NULL,NULL,NULL,0,1,300,'Activo',0,0,0,11,'lnxni0230',0),
	 (99,5,'FA_HISTDOCU','Extractor SCL','Extractor Full',NULL,NULL,NULL,NULL,0,1,300,'Activo',0,0,0,11,'lnxni0230',0),
	 (98,5,'GA_CAUCASER','Extractor SCL','Extractor Full',NULL,NULL,NULL,NULL,0,1,300,'Activo',0,0,0,11,'lnxni0230',0),
	 (97,5,'GA_MODABOCEL','Extractor SCL','Extractor Full',NULL,NULL,NULL,NULL,0,1,300,'Activo',0,0,0,11,'lnxni0230',0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS (IDPROC,IDCONEX,NOMBRE,DESCRIPCION,"PATH",PARAMETRO1,PARAMETRO2,PARAMETRO3,PARAMETRO4,DEPENDENCIA,INTENTOS,ESPERA_INTENTO,ESTADO,FTP,IDHOST,COMPRESION,IDCRONTAB,NODE,IDNOTIF) VALUES
	 (96,3,'GA_EQUIPABOSER.sql','Extractor SCL','${PATH_DIRECTOR_SQL}',NULL,NULL,NULL,NULL,0,1,300,'Activo',0,0,0,11,'lnxni0230',0),
	 (95,0,'carga_lqnts.sh','PROCESO CARGA DATOS LQNTS','/home/appextractor/Director/Sh',NULL,NULL,NULL,NULL,0,600,60,'Inactivo',0,0,0,11,'sunni005',0),
	 (94,0,'ftp_director_rpt_prueba.sh','Servicio de Transferencia','/home/appextractor/Director/Sh',NULL,NULL,NULL,NULL,0,100,600,'Activo',0,0,0,11,'sunni005',0),
	 (93,3,'cambio_equipo_gtia_no_fact.sql','REPORTE EQUIPOS GARANTIA NO EN INVENTARIO','${PATH_DIRECTOR_SQL}','${PATH_DIRECTOR_ENTRADA}/equipos_garantia_no_fact_COMENTARIO_OS_',NULL,NULL,NULL,1,1,0,'Activo',1,7,0,11,'lnxni0230',0),
	 (92,3,'genera_salida_npwfact.sql','REPORTE NPW_FACT','${PATH_DIRECTOR_SQL}','${PATH_DIRECTOR_ENTRADA}/RPT_FACT_NPW_DIRECT_','TO_CHAR(sysdate-3,''yyyymm'')',NULL,NULL,1,1,0,'Activo',1,7,1,11,'lnxni0230',0),
	 (91,3,'EXT_FACT_NPW_VENUS.sql','PROCESO CALCULO PARA REPORTE FACT_NPW','${PATH_DIRECTOR_SQL}','TO_CHAR(sysdate-2,''yyyymm'')',NULL,NULL,NULL,1,1,0,'Activo',0,0,0,11,'lnxni0230',0),
	 (90,6,'venta_directa_RSCLNIC.sql','EXTRACTOR PARA REPORTE DE FACT','${PATH_DIRECTOR_SQL}','TO_CHAR(sysdate-2,''yyyymm'')',NULL,NULL,NULL,1,1,0,'Activo',0,0,0,26,'lnxni0230',0),
	 (89,3,'PREC_INIC_SERIE.sql','Interfaz','${PATH_DIRECTOR_SQL}',NULL,NULL,NULL,NULL,1,1,0,'Activo',0,0,0,11,'lnxni0230',0),
	 (88,6,'KITS_RSCLNIC.sql','EXTRACTOR PARA REPORTE DE FACT','${PATH_DIRECTOR_SQL}','TO_CHAR(sysdate-2,''yyyymm'')',NULL,NULL,NULL,1,1,0,'Activo',0,0,0,26,'lnxni0230',0),
	 (86,6,'AL_MOVIMIENTOS_TIP10.sql','Extractor SCL','${PATH_DIRECTOR_SQL}',NULL,NULL,NULL,NULL,1,1,300,'Activo',0,0,0,26,'lnxni0230',0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS (IDPROC,IDCONEX,NOMBRE,DESCRIPCION,"PATH",PARAMETRO1,PARAMETRO2,PARAMETRO3,PARAMETRO4,DEPENDENCIA,INTENTOS,ESPERA_INTENTO,ESTADO,FTP,IDHOST,COMPRESION,IDCRONTAB,NODE,IDNOTIF) VALUES
	 (85,3,'TCN_CUENTAS_ALL.sql','Interfaz','${PATH_DIRECTOR_SQL}',NULL,NULL,NULL,NULL,1,1,0,'Activo',0,0,0,11,'lnxni0230',0),
	 (84,3,'roaming_altamira.sql','REPORTE','/home/appextractor/Director/Sql','''/home/appextractor/Director/Entrada/TRAFICO_ROAMING_ALTAMIRA_''',NULL,NULL,NULL,1,600,60,'Inactivo',1,7,0,11,'sunni005',0),
	 (83,0,'INV_DETMOV_SH.sh','Shell de Reporte de Detalle de Movimiento de Inventario','/home/appextractor/Director/Sh','/home/appextractor/Director/Entrada/','/RepDWH','TO_CHAR(sysdate -1,''yyyymmdd'')',NULL,1,10,60,'Activo',0,0,0,34,'sunni005',0),
	 (82,0,'INV_DETGSM_SH.sh','Shell de Reporte de Inventario GSM','/home/appextractor/Director/Sh','/home/appextractor/Director/Entrada/','/RepDWH','to_char(sysdate -1,''yyyymmdd'')',NULL,1,10,60,'Activo',0,0,0,11,'sunni005',0),
	 (81,3,'inventario_tablas.sql','Reporte','${PATH_DIRECTOR_SQL}',NULL,NULL,NULL,NULL,1,1,0,'Activo',0,0,0,11,'lnxni0230',0),
	 (80,1,'PPGA_ABOPREPTAR','Extractor Altamira','Extractor Full',NULL,NULL,NULL,NULL,1,1,0,'Inactivo',0,0,0,11,'lnxni0230',0),
	 (79,6,'prc_activacionesopo.sh','Activaciones OPO - SQL launch','${PATH_DIRECTOR_SH}','to_char(sysdate-3,''yyyymm'')',NULL,NULL,NULL,0,1,0,'Activo',0,0,0,26,'lnxni0230',0),
	 (76,5,'GA_DIRECCLI','Extractor SCL','Extractor Full',NULL,NULL,NULL,NULL,0,1,300,'Activo',0,0,0,11,'lnxni0230',0),
	 (75,5,'TA_CARGOSBASICO','Extractor SCL','Extractor Full',NULL,NULL,NULL,NULL,0,1,300,'Activo',0,0,0,11,'lnxni0230',0),
	 (71,5,'GA_PERCONTRATO','Extractor SCL','Extractor Full',NULL,NULL,NULL,NULL,0,1,300,'Activo',0,0,0,11,'lnxni0230',0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS (IDPROC,IDCONEX,NOMBRE,DESCRIPCION,"PATH",PARAMETRO1,PARAMETRO2,PARAMETRO3,PARAMETRO4,DEPENDENCIA,INTENTOS,ESPERA_INTENTO,ESTADO,FTP,IDHOST,COMPRESION,IDCRONTAB,NODE,IDNOTIF) VALUES
	 (70,3,'BDDWH.DWD_RANGO_SALDO.sql','Extractor DWH','/home/appextractor/Director/Sql',NULL,NULL,NULL,NULL,1,600,60,'Inactivo',0,0,0,11,'sunni005',0),
	 (69,3,'DWD_PLAN_TARIFARIO.sql','Extractor DWH','/home/appextractor/Director/Sql',NULL,NULL,NULL,NULL,1,600,60,'Inactivo',0,0,0,11,'sunni005',0),
	 (68,3,'DWD_ESTATUS_OPERACION.sql','Extractor DWH','${PATH_DIRECTOR_SQL}',NULL,NULL,NULL,NULL,1,1,300,'Activo',0,0,0,11,'lnxni0230',0),
	 (67,17,'BDDWH.DWD_ESTATUS_GESTION','Extractor DWH','Extractor Full',NULL,NULL,NULL,NULL,1,1,300,'Activo',0,0,0,11,'lnxni0230',0),
	 (64,17,'BDDWH.DWD_LINEA_NEGOCIO','Extractor DWH','Extractor Full',NULL,NULL,NULL,NULL,1,1,300,'Activo',0,0,0,11,'lnxni0230',0),
	 (63,5,'GE_CIUDADES','Extractor SCL','Extractor Full',NULL,NULL,NULL,NULL,0,1,300,'Activo',0,0,0,11,'lnxni0230',0),
	 (62,5,'GE_PROVINCIAS','Extractor SCL','Extractor Full',NULL,NULL,NULL,NULL,0,1,300,'Activo',0,0,0,11,'lnxni0230',0),
	 (61,5,'GE_DIRECCIONES','Extractor SCL','Extractor Full',NULL,NULL,NULL,NULL,0,1,300,'Activo',0,0,0,11,'lnxni0230',0),
	 (60,5,'GA_TIPCONTRATO','Extractor SCL','Extractor Full',NULL,NULL,NULL,NULL,0,1,300,'Activo',0,0,0,11,'lnxni0230',0),
	 (59,5,'GE_REGIONES','Extractor SCL','Extractor Full',NULL,NULL,NULL,NULL,0,1,300,'Activo',0,0,0,11,'lnxni0230',0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS (IDPROC,IDCONEX,NOMBRE,DESCRIPCION,"PATH",PARAMETRO1,PARAMETRO2,PARAMETRO3,PARAMETRO4,DEPENDENCIA,INTENTOS,ESPERA_INTENTO,ESTADO,FTP,IDHOST,COMPRESION,IDCRONTAB,NODE,IDNOTIF) VALUES
	 (58,5,'GA_VENTAS','Extractor SCL','Extractor Full',NULL,NULL,NULL,NULL,0,1,300,'Activo',0,0,0,11,'lnxni0230',0),
	 (55,5,'VE_VENDEDORES','Extractor SCL','Extractor Full',NULL,NULL,NULL,NULL,0,1,300,'Activo',0,0,0,11,'lnxni0230',0),
	 (54,5,'TA_PLANTARIF','Extractor SCL','Extractor Full',NULL,NULL,NULL,NULL,0,1,300,'Activo',0,0,0,11,'lnxni0230',0),
	 (53,5,'GE_CATEGORIAS','Extractor SCL','Extractor Full',NULL,NULL,NULL,NULL,0,1,300,'Activo',0,0,0,11,'lnxni0230',0),
	 (52,5,'GA_CUENTAS','Extractor SCL','Extractor Full',NULL,NULL,NULL,NULL,0,1,300,'Activo',0,0,0,11,'lnxni0230',0),
	 (51,5,'AL_ARTICULOS','Extractor SCL','Extractor Full',NULL,NULL,NULL,NULL,0,1,300,'Activo',0,0,0,11,'lnxni0230',0),
	 (50,0,'ConexionRSCLNIC.sh','Conexión','${PATH_DIRECTOR_SH}','to_char(sysdate-1,''yyyymmdd'')','to_char(sysdate-1,''mmyyyy'')',NULL,NULL,0,1,0,'Activo',0,0,0,11,'lnxni0230',0),
	 (49,3,'AL_MOVIMIENTOS.sql','Extractor SCL','${PATH_DIRECTOR_SQL}','to_char(sysdate-1,''yyyymmdd'')',NULL,NULL,NULL,0,1,300,'Activo',0,0,0,11,'lnxni0230',0),
	 (48,5,'AL_STOCK','Extractor SCL','Extractor Full',NULL,NULL,NULL,NULL,0,1,300,'Activo',0,0,0,11,'lnxni0230',0),
	 (47,5,'AL_TIPOS_BODEGAS','Extractor SCL','Extractor Full',NULL,NULL,NULL,NULL,0,1,300,'Activo',0,0,0,11,'lnxni0230',0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS (IDPROC,IDCONEX,NOMBRE,DESCRIPCION,"PATH",PARAMETRO1,PARAMETRO2,PARAMETRO3,PARAMETRO4,DEPENDENCIA,INTENTOS,ESPERA_INTENTO,ESTADO,FTP,IDHOST,COMPRESION,IDCRONTAB,NODE,IDNOTIF) VALUES
	 (46,5,'AL_SERIES','Extractor SCL','Extractor Full',NULL,NULL,NULL,NULL,0,1,300,'Activo',0,0,0,11,'lnxni0230',0),
	 (45,5,'AL_ESTADOS','Extractor SCL','Extractor Full',NULL,NULL,NULL,NULL,0,1,300,'Activo',0,0,0,11,'lnxni0230',0),
	 (44,5,'AL_BODEGAS','Extractor SCL','Extractor Full',NULL,NULL,NULL,NULL,0,1,300,'Activo',0,0,0,11,'lnxni0230',0),
	 (43,5,'AL_TIPOS_MOVIMIENTOS','Extractor SCL','Extractor Full',NULL,NULL,NULL,NULL,0,1,300,'Activo',0,0,0,11,'lnxni0230',0),
	 (42,5,'AL_USOS','Extractor SCL','Extractor Full',NULL,NULL,NULL,NULL,0,1,300,'Activo',0,0,0,11,'lnxni0230',0),
	 (41,5,'FA_CICLFACT','Extractor SCL','Extractor Full',NULL,NULL,NULL,NULL,0,1,300,'Activo',0,0,0,11,'lnxni0230',0),
	 (40,5,'CO_CARTERA','Extractor SCL','Extractor Full',NULL,NULL,NULL,NULL,0,1,300,'Activo',0,0,0,11,'lnxni0230',0),
	 (39,5,'GE_CLIENTES','Extractor SCL','Extractor Full',NULL,NULL,NULL,NULL,0,1,300,'Activo',0,0,0,11,'lnxni0230',0),
	 (38,0,'Abonado_Nicaragua_Spool.sh','Proceso copia abonado SIEMCAM Parte 1','/home/appextractor/Director/Sh',NULL,NULL,NULL,NULL,1,600,60,'Inactivo',0,0,0,11,'sunni005',0),
	 (37,3,'CARGA_SEGMENTACION.sql','Interfaz','/home/appextractor/Director/Sql',NULL,NULL,NULL,NULL,0,0,0,'Petición',0,0,0,11,'sunni005',0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS (IDPROC,IDCONEX,NOMBRE,DESCRIPCION,"PATH",PARAMETRO1,PARAMETRO2,PARAMETRO3,PARAMETRO4,DEPENDENCIA,INTENTOS,ESPERA_INTENTO,ESTADO,FTP,IDHOST,COMPRESION,IDCRONTAB,NODE,IDNOTIF) VALUES
	 (35,3,'ULTIMO_EVENTO_COMPETENCIA.sql','Interfaz','/home/appextractor/Director/Sql','TO_CHAR(ADD_MONTHS(SYSDATE,-3),''YYYYMMDD'')',NULL,NULL,NULL,1,600,60,'Inactivo',0,0,0,11,'sunni005',0),
	 (14,6,'GA_ABOAMIST','Extractor SCL','Extractor Full',NULL,NULL,NULL,NULL,0,1,300,'Activo',0,0,0,26,'lnxni0230',0),
	 (13,6,'GA_ABOCEL','Extractor SCL','Extractor Full',NULL,NULL,NULL,NULL,0,1,300,'Activo',0,0,0,26,'lnxni0230',0),
	 (10,0,'ConexionSIEMCAM_PRE.sh','Conexión','/home/appextractor/Director/Sh','to_char(sysdate-1,''yyyymmdd'')','to_char(sysdate-2,''yyyymmdd'')',NULL,NULL,0,5,60,'Inactivo',0,0,0,11,'sunni005',0),
	 (7,0,'ConexionROPGE.sh','PROCESO VALIDADOR CONEXION OPGE COPIA','/home/appextractor/Director/Sh','to_char(sysdate,''yyyymmdd'')',NULL,NULL,NULL,0,5,60,'Inactivo',0,0,0,11,'sunni005',0),
	 (6,3,'main_extrae_tablas.sh','Extractores','/home/appextractor/Director/Sh',NULL,NULL,NULL,NULL,1,600,60,'Inactivo',0,0,0,11,'sunni005',0),
	 (5,0,'ConexionRLPPGAN.sh','Conexión','/home/appextractor/Director/Sh','to_char(sysdate,''yyyymmdd'')',NULL,NULL,NULL,0,5,60,'Inactivo',0,0,0,11,'sunni005',0),
	 (4,0,'ConexionDWH.sh','Conexión','/home/appextractor/Director/Sh','to_char(sysdate-1,''yyyymmdd'')','to_char(sysdate-2,''yyyymmdd'')',NULL,NULL,0,5,60,'Inactivo',0,0,0,11,'sunni005',0),
	 (3,3,'Numeros_Frecuentes.sql','Interfaz','${PATH_DIRECTOR_SQL}','to_char(sysdate-15,''yyyymmdd'')','to_char(sysdate-2,''yyyymmdd'')',NULL,NULL,1,1,0,'Activo',0,0,0,32,'lnxni0230',0),
	 (2,0,'FSMaintenance.sh','Script for Filesystem Maintenance lnxni0230','${PATH_DIRECTOR_SH}','to_char(sysdate-1,&amp;#x27;yyyymmdd&amp;#x27;)',NULL,'Luis','Eduardo',0,1,2,'Internal',1,4,0,13,'lnxni0230',0);
INSERT INTO APP_SCL_ALTAMIRA.CP_PROCESOS (IDPROC,IDCONEX,NOMBRE,DESCRIPCION,"PATH",PARAMETRO1,PARAMETRO2,PARAMETRO3,PARAMETRO4,DEPENDENCIA,INTENTOS,ESPERA_INTENTO,ESTADO,FTP,IDHOST,COMPRESION,IDCRONTAB,NODE,IDNOTIF) VALUES
	 (1,0,'KillJob.sh','Script for killing a job','${PATH_DIRECTOR_SH}',NULL,NULL,NULL,NULL,0,1,0,'Internal',0,0,0,11,'lnxni0230',0);