-- APP_SCL_ALTAMIRA.CP_REGISTRO definition

CREATE TABLE "APP_SCL_ALTAMIRA"."CP_REGISTRO" 
   (	"IDREG" NUMBER, 
	"IDPROC" NUMBER, 
	"FEC_INICIO" DATE, 
	"FEC_EJECUCION" DATE, 
	"FEC_FINALIZO" DATE, 
	"ESTADO" VARCHAR2(200), 
	"FLAG_ALARMA" NUMBER DEFAULT 0, 
	 CONSTRAINT "CP_REGISTRO_PK" PRIMARY KEY ("IDREG")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 458752 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCL_DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 2097152 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCL_DATA" ;

CREATE SEQUENCE cp_registro_sequence;

CREATE OR REPLACE TRIGGER "APP_SCL_ALTAMIRA"."CP_REGISTRO_ON_INSERT"   BEFORE INSERT ON "APP_SCL_ALTAMIRA"."CP_REGISTRO"  FOR EACH ROWBEGIN
  SELECT cp_registro_sequence.nextval
  INTO :new.IDREG
  FROM dual;
END;
/
ALTER TRIGGER "APP_SCL_ALTAMIRA"."CP_REGISTRO_ON_INSERT" ENABLE;

CREATE UNIQUE INDEX "APP_SCL_ALTAMIRA"."PK_REGISTRO_IDREG" ON "APP_SCL_ALTAMIRA"."CP_REGISTRO" ("IDREG") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 458752 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCL_DATA" ;
  CREATE INDEX "APP_SCL_ALTAMIRA"."PK_REGISTRO_IDPROC" ON "APP_SCL_ALTAMIRA"."CP_REGISTRO" ("IDPROC") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 589824 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCL_DATA" ;

GRANT SELECT ON "APP_SCL_ALTAMIRA"."CP_REGISTRO" TO "URLTUXEDO";
  GRANT SELECT ON "APP_SCL_ALTAMIRA"."CP_REGISTRO" TO "APP_APLICACIONES";