CREATE OR REPLACE PROCEDURE APP_SCL_ALTAMIRA.getCrontabs (
     p_idcrontab IN CP_CRONTAB.IDCRONTAB%TYPE, 
     p_recordset OUT SYS_REFCURSOR
  ) AS 
  BEGIN 
    OPEN p_recordset FOR
      SELECT IDCRONTAB, FECHA,HORA_INICIO,HORA_FIN,RECURRENCIA,WDAY_M2S_EX,DAY_EX,MONTH_EX,REPEAT_EVERY_MINS,REPEAT_AFTER_FINISH
      FROM  APP_SCL_ALTAMIRA.CP_CRONTAB
      WHERE IDCRONTAB >0
      ORDER BY IDCRONTAB ASC;
  END getCrontabs;