INSERT INTO APP_SCL_ALTAMIRA.CP_NOTIFICATIONS
(IDNOTIF, RECIPIENTS, NOTIFYSUCCESS, NOTIFYFAILURE, NAME)
VALUES(0, 'recipient01@tigo.com.ni,recipient02@tigo.com.ni', 0, 0, 'Dummy Notification');
INSERT INTO APP_SCL_ALTAMIRA.CP_NOTIFICATIONS
(IDNOTIF, RECIPIENTS, NOTIFYSUCCESS, NOTIFYFAILURE, NAME)
VALUES(1, 'luiseduardo.alvarado@tigo.com.ni', 1, 1, 'Notification Success/Failure to BI members');
INSERT INTO APP_SCL_ALTAMIRA.CP_NOTIFICATIONS
(IDNOTIF, RECIPIENTS, NOTIFYSUCCESS, NOTIFYFAILURE, NAME)
VALUES(2, 'luiseduardo.alvarado@tigo.com.ni', 1, 0, 'Notification Success Only to BI members');
INSERT INTO APP_SCL_ALTAMIRA.CP_NOTIFICATIONS
(IDNOTIF, RECIPIENTS, NOTIFYSUCCESS, NOTIFYFAILURE, NAME)
VALUES(3, 'luiseduardo.alvarado@tigo.com.ni', 0, 0, 'Notification Failure Only to BI members');